### ISSUE TITLE
Rendering Mimicube helmet causing crash

### ISSUE THREAD

**Issue by Sylvezar** [Alex-the-666/AlexsMobs#1016]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.client.model.HumanoidModel net.minecraftforge.client.ForgeHooksClient.getArmorModel(net.minecraft.world.entity.LivingEntity, net.minecraft.world.item.ItemStack, net.minecraft.world.entity.EquipmentSlot, net.minecraft.client.model.HumanoidModel)'

at com.github.alexthe666.alexsmobs.client.render.layer.LayerMimicubeHelmet.getArmorModelHook(LayerMimicubeHelmet.java:146) ~[alexsmobs-1.15.1%20(1).jar%2353!/:1.15.1]
    at com.github.alexthe666.alexsmobs.client.render.layer.LayerMimicubeHelmet.render(LayerMimicubeHelmet.java:69) ~[alexsmobs-1.15.1%20(1).jar%2353!/:1.15.1]
    at com.github.alexthe666.alexsmobs.client.render.layer.LayerMimicubeHelmet.m_6494_(LayerMimicubeHelmet.java:27) ~[alexsmobs-1.15.1%20(1).jar%2353!/:1.1

located at https://github.com/Alex-the-666/AlexsMobs/blob/1.18/src/main/java/com/github/alexthe666/alexsmobs/client/render/layer/LayerMimicubeHelmet.java line 147

as soon as i log on to the server with the mimicube my game crashes.

**Comment by g33sys** [comment]
Same here. I autocrash on logon. 

Btw: It's trying to mimic a simple diamond helmet which crashes the client.
https://pastebin.com/Tma5Yw6e

**Comment by AlexModGuy** [comment]
fixed
