### ISSUE TITLE
Froststalker crash

### ISSUE THREAD

**Issue by Reshy** [Alex-the-666/AlexsMobs#1057]
Seemed to have happened when a whale got under a frostalker.

https://pastebin.com/PcG2f6bG

**Comment by mactso** [comment]
Server Crash 1.18.1

Pertinent details...

	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (amd64) version 3.10.0-957.21.2.el7.x86_64
	Java Version: 17.0.1, Oracle Corporation
	alexsmobs-1.18.4.jar                              |Alex's Mobs                   |alexsmobs                     |1.18.4              |DONE      |Manifest: NOSIGNATURE

---
	at net.minecraft.world.entity.Mob.m_21391_(Mob.java:740) ~[server-1.18.1-20211210.034407-srg.jar%23109!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:mobpc:MobEntity,re:mixin,pl:accesstransformer:B,xf:fml:mobpc:MobEntity}
	at com.github.alexthe666.alexsmobs.entity.ai.FroststalkerAIMelee.m_8037_(FroststalkerAIMelee.java:117) ~[alexsmobs-1.18.4.jar%2338!/:1.18.4] {re:classloading}
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8037_(WrappedGoal.java:65) ~[server-1.18.1-20211210.034407-srg.jar%23109!/:?] {re:classloading}
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_186081_(GoalSelector.java:119) ~[server-1.18.1-20211210.034407-srg.jar%23109!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_25373_(GoalSelector.java:110) ~[server-1.18.1-20211210.034407-srg.jar%23109!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:698) ~[server-1.18.1-20211210.034407-srg.jar%23109!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:mobpc:MobEntity,re:mixin,pl:accesstransformer:B,xf:fml:mobpc:MobEntity}



java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.m20185()" because "p21392" is null
    at net.minecraft.world.entity.Mob.m21391(Mob.java:740) ~[server-1.18.1-20211210.034407-srg.jar%23109!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:mobpc:MobEntity,re:mixin,pl:accesstransformer:B,xf:fml:mobpc:MobEntity}
    at com.github.alexthe666.alexsmobs.entity.ai.FroststalkerAIMelee.m8037(FroststalkerAIMelee.java:117) ~[alexsmobs-1.18.4.jar%2338!/:1.18.4] {re:classloading}

    Entity Type: alexsmobs:froststalker (com.github.alexthe666.alexsmobs.entity.EntityFroststalker)
    Entity ID: 278016
    Entity Name: Froststalker
    Entity's Exact location: 1340.63, 69.14, 4732.10
    Entity's Block location: World: (1340,69,4732), Section: (at 12,5,12 in 83,4,295; chunk contains blocks 1328,-64,4720 to 1343,319,4735), Region: (2,9; contains chunks 64,288 to 95,319, blocks 1024,-64,4608 to 1535,319,5119)
    Entity's Momentum: -0.25, 0.52, -0.36
    Entity's Passengers: []
    Entity's Vehicle: null

Love the mod!  Cheers.

**Comment by mactso** [comment]
I've disabled the froststalker for now by changing the json file to have no biomes.  Testing to make sure the server comes up with that fix.

Okay, server started fine.
