### ISSUE TITLE
Lava sight hard crashing my game and keeping me out of servers

### ISSUE THREAD

**Issue by MrFreddle** [Alex-the-666/AlexsMobs#1131]
I crash and can't get back in whenever I use the lava slight potion. This is on the 1.18.2 version and should be up to date.
I have no idea what's going on and have tried to get support elsewhere with no real success.

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 6/17/22, 10:17 PM
Description: Unexpected error

java.lang.IllegalStateException: Render layers can only be set during client loading! This might ideally be done from `FMLClientSetupEvent`.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:502) ~[guava-31.0.1-jre.jar%2328!/:?] {}
	at net.minecraft.client.renderer.ItemBlockRenderTypes.checkClientLoading(ItemBlockRenderTypes.java:401) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:quark.mixins.json:client.ItemBlockRenderTypesMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemBlockRenderTypes.setRenderLayer(ItemBlockRenderTypes.java:396) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:quark.mixins.json:client.ItemBlockRenderTypesMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemBlockRenderTypes.setRenderLayer(ItemBlockRenderTypes.java:392) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:quark.mixins.json:client.ItemBlockRenderTypesMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.github.alexthe666.alexsmobs.client.event.ClientEvents.onRenderWorldLastEvent(ClientEvents.java:356) ~[alexsmobs-1.18.5.jar%2355!/:1.18.5] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_823_ClientEvents_onRenderWorldLastEvent_RenderLevelLastEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:229) ~[forge-1.18.2-40.1.48-universal.jar%23135!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1063) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:835) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:chat_heads.mixins.json:MinecraftMixin,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:chat_heads.mixins.json:MinecraftMixin,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.48.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.common.base.Preconditions.checkState(Preconditions.java:502) ~[guava-31.0.1-jre.jar%2328!/:?] {}
	at net.minecraft.client.renderer.ItemBlockRenderTypes.checkClientLoading(ItemBlockRenderTypes.java:401) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:quark.mixins.json:client.ItemBlockRenderTypesMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemBlockRenderTypes.setRenderLayer(ItemBlockRenderTypes.java:396) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:quark.mixins.json:client.ItemBlockRenderTypesMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemBlockRenderTypes.setRenderLayer(ItemBlockRenderTypes.java:392) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:quark.mixins.json:client.ItemBlockRenderTypesMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.github.alexthe666.alexsmobs.client.event.ClientEvents.onRenderWorldLastEvent(ClientEvents.java:356) ~[alexsmobs-1.18.5.jar%2355!/:1.18.5] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_823_ClientEvents_onRenderWorldLastEvent_RenderLevelLastEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:229) ~[forge-1.18.2-40.1.48-universal.jar%23135!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1063) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Data_Freddle'/3081, l='ClientLevel', x=-3.35, y=49.25, z=29.88]]
	Chunk stats: 1225, 809
	Level dimension: minecraft:the_nether
	Level spawn location: World: (51,91,-20), Section: (at 3,11,12 in 3,5,-2; chunk contains blocks 48,0,-32 to 63,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1375139 game time, 74863 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:407) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:starlight.mixins.json:client.world.ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2260) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:chat_heads.mixins.json:MinecraftMixin,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:chat_heads.mixins.json:MinecraftMixin,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.48.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources, Supplementaries Generated Pack, quark-emote-pack

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 858621424 bytes (818 MiB) / 2617245696 bytes (2496 MiB) up to 7415529472 bytes (7072 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Radeon RX 580 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=30.0.13023.4001
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 26818.82
	Virtual memory used (MB): 21586.19
	Swap memory total (MB): 10485.30
	Swap memory used (MB): 644.24
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7072m -Xms256m
	Launched Version: forge-40.1.48
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: Radeon RX 580 Series GL version 3.2.14761 Core Profile Forward-Compatible Context 21.30.23.04 30.0.13023.4001, ATI Technologies Inc.
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		Kiwi-1.18.2-forge-6.1.2.jar                       |Kiwi                          |kiwi                          |6.1.2               |DONE      |Manifest: NOSIGNATURE
		YungsBetterDungeons-1.18.2-Forge-2.1.0.jar        |YUNG's Better Dungeons        |betterdungeons                |1.18.2-Forge-2.1.0  |DONE      |Manifest: NOSIGNATURE
		habitat-1.1.3.jar                                 |Habitat                       |habitat                       |1.1.3               |DONE      |Manifest: NOSIGNATURE
		YungsBetterWitchHuts-1.18.2-Forge-1.0.jar         |YUNG's Better Witch Huts      |betterwitchhuts               |1.18.2-Forge-1.0    |DONE      |Manifest: NOSIGNATURE
		bigbrain-1.5.3.jar                                |Big Brain                     |bigbrain                      |1.5.3               |DONE      |Manifest: NOSIGNATURE
		Origins-1.18.2-1.4.1.1-unified.jar                |Additional Entity Attributes  |additionalentityattributes    |1.18.2-1.4.1.1      |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-9.5.5.174.jar                          |Just Enough Items             |jei                           |9.5.5.174           |DONE      |Manifest: NOSIGNATURE
		the-conjurer-1.18.2-1.1.1.jar                     |The Conjurer                  |conjurer_illager              |1.1.1               |DONE      |Manifest: NOSIGNATURE
		Pehkui-3.3.2+1.18.2-forge.jar                     |Pehkui                        |pehkui                        |3.3.2+1.18.2-forge  |DONE      |Manifest: NOSIGNATURE
		BreakingBadMeth_Mod_Forge1.18.2_v1.1.jar          |Breaking Bad Meth Mod         |brekingbadmethandmoredrugs    |1.0.0               |DONE      |Manifest: NOSIGNATURE
		goblintraders-1.7.2-1.18.2.jar                    |Goblin Traders                |goblintraders                 |1.7.2               |DONE      |Manifest: NOSIGNATURE
		caelus-forge-1.18.1-3.0.0.2.jar                   |Caelus API                    |caelus                        |1.18.1-3.0.0.2      |DONE      |Manifest: NOSIGNATURE
		Strawgolem-forge-1.18.2-2.0.0b1.jar               |Straw Golem                   |strawgolem                    |2.0.0b1             |DONE      |Manifest: NOSIGNATURE
		kleeslabs-forge-1.18.2-11.1.1.jar                 |KleeSlabs                     |kleeslabs                     |11.1.1              |DONE      |Manifest: NOSIGNATURE
		duckling-1.0.5-forge.jar                          |Duckling                      |duckling                      |1.0.5               |DONE      |Manifest: NOSIGNATURE
		FastSuite-1.18.2-3.0.2.jar                        |Fast Suite                    |fastsuite                     |3.0.2               |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.18.2-8.0.0+10.jar                  |Clumps                        |clumps                        |8.0.0+10            |DONE      |Manifest: NOSIGNATURE
		Placebo-1.18.2-6.4.0.jar                          |Placebo                       |placebo                       |6.4.0               |DONE      |Manifest: NOSIGNATURE
		comforts-forge-1.18.2-5.0.0.4.jar                 |Comforts                      |comforts                      |1.18.2-5.0.0.4      |DONE      |Manifest: NOSIGNATURE
		tumbleweed-1.18-0.4.12.jar                        |Tumbleweed                    |tumbleweed                    |1.18-0.4.12         |DONE      |Manifest: NOSIGNATURE
		jumpboat-1.18.2-0.1.0.3.jar                       |Jumpy Boats                   |jumpboat                      |1.18.2-0.1.0.3      |DONE      |Manifest: NOSIGNATURE
		configured-1.5.3-1.18.2.jar                       |Configured                    |configured                    |1.5.3               |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.18.2-Forge-2.0.8.jar                   |YUNG's API                    |yungsapi                      |1.18.2-Forge-2.0.8  |DONE      |Manifest: NOSIGNATURE
		finsandtails-1.18.2-1.0.1.jar                     |Fins and Tails                |finsandtails                  |1.18.2-1.0.1        |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.18.2-13.2.21.jar                |Bookshelf                     |bookshelf                     |13.2.21             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		snowundertrees-1.18.2-1.2.1.jar                   |Snow Under Trees              |snowundertrees                |1.2.1               |DONE      |Manifest: NOSIGNATURE
		guardvillagers-1.18.2.1.4.3.jar                   |Guard Villagers               |guardvillagers                |1.4.3               |DONE      |Manifest: NOSIGNATURE
		lazydfu-1.0-1.18+.jar                             |LazyDFU                       |lazydfu                       |0.1.3               |DONE      |Manifest: NOSIGNATURE
		starlight-1.0.2+forge.546ae87.jar                 |Starlight                     |starlight                     |1.0.2+forge.83663de |DONE      |Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.18.2-Forge-1.1.0.jar   |YUNG's Better Desert Temples  |betterdeserttemples           |1.18.2-Forge-1.1.0  |DONE      |Manifest: NOSIGNATURE
		Rex's-AdditionalStructures-1.18.2-(v.3.1.0).jar   |Additional Structures         |additionalstructures          |3.1.0               |DONE      |Manifest: NOSIGNATURE
		catalogue-1.6.2-1.18.2.jar                        |Catalogue                     |catalogue                     |1.6.2               |DONE      |Manifest: NOSIGNATURE
		balm-3.1.0+0.jar                                  |Balm                          |balm                          |3.1.0+0             |DONE      |Manifest: NOSIGNATURE
		SnowRealMagic-1.18.2-forge-4.0.0.jar              |Snow! Real Magic!             |snowrealmagic                 |4.0.0               |DONE      |Manifest: NOSIGNATURE
		dynview-1.18.2-2.8.jar                            |Dynamic view distance         |dynview                       |2.3                 |DONE      |Manifest: NOSIGNATURE
		carryon-1.18.2-1.17.0.8.jar                       |Carry On                      |carryon                       |1.17.0.8            |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.18.2-0.14.1.171.jar         |Just Enough Resources         |jeresources                   |0.14.1.171          |DONE      |Manifest: NOSIGNATURE
		chat_heads-0.6.0-forge-1.18.1.jar                 |Chat Heads                    |chat_heads                    |0.6.0               |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.2.62-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.2.62              |DONE      |Manifest: NOSIGNATURE
		3dskinlayers-forge-1.4.6-mc1.18.2.jar             |3dSkinLayers                  |skinlayers3d                  |1.4.6               |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.48-universal.jar                |Forge                         |forge                         |40.1.48             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		structure_gel-1.18.2-2.4.3.jar                    |Structure Gel API             |structure_gel                 |2.4.3               |DONE      |Manifest: NOSIGNATURE
		selene-1.18.2-1.17.7.jar                          |Selene                        |selene                        |1.18.2-1.17.7       |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.18.2-1.4.6.jar                  |Supplementaries               |supplementaries               |1.18.2-1.4.6        |DONE      |Manifest: NOSIGNATURE
		Amplified_Nether_v1.1.1.jar                       |Amplified Nether              |amplifiednether               |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		voicechat-forge-1.18.2-2.2.45.jar                 |Simple Voice Chat             |voicechat                     |1.18.2-2.2.45       |DONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.18.2-10.0.4.jar   |EnchantmentDescriptions       |enchdesc                      |10.0.4              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		YungsBridges-1.18.2-Forge-2.1.0.jar               |YUNG's Bridges                |yungsbridges                  |1.18.2-Forge-2.1.0  |DONE      |Manifest: NOSIGNATURE
		spark-1.9.11-forge.jar                            |spark                         |spark                         |1.9.11              |DONE      |Manifest: NOSIGNATURE
		betterfpsdist-1.18.2-1.5.jar                      |betterfpsdist mod             |betterfpsdist                 |1.18.2-1.5          |DONE      |Manifest: NOSIGNATURE
		notenoughanimations-forge-1.6.0-mc1.18.2.jar      |NotEnoughAnimations Mod       |notenoughanimations           |1.6.0               |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.18.2-70.jar                           |Patchouli                     |patchouli                     |1.18.2-70           |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |DONE      |Manifest: NOSIGNATURE
		Quark-3.2-357.jar                                 |Quark                         |quark                         |3.2-357             |DONE      |Manifest: NOSIGNATURE
		YungsExtras-1.18.2-Forge-2.1.0.jar                |YUNG's Extras                 |yungsextras                   |1.18.2-Forge-2.1.0  |DONE      |Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.18.2-Forge-2.1.1.jar     |YUNG's Better Strongholds     |betterstrongholds             |1.18.2-Forge-2.1.1  |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.10.jar                          |WorldEdit                     |worldedit                     |7.2.10+1742f98      |DONE      |Manifest: NOSIGNATURE
		HunterIllager-1.18.2-4.0.1.jar                    |Hunter Illager                |hunterillager                 |1.18.2-4.0.1        |DONE      |Manifest: NOSIGNATURE
		illagersweararmor-1.1.5.jar                       |Illagers Wear Armor           |zillagersweararmor            |1.1.5               |DONE      |Manifest: NOSIGNATURE
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		Wandering Trapper-forge-1.18.2-1.2.0.jar          |Wandering Trapper             |wandering_trapper             |1.2.0               |DONE      |Manifest: NOSIGNATURE
		architectury-4.5.74-forge.jar                     |Architectury                  |architectury                  |4.5.74              |DONE      |Manifest: NOSIGNATURE
		friendsandfoes-forge-mc1.18.2-1.4.3.jar           |Friends&Foes                  |friendsandfoes                |1.4.3               |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.18-2.4.0.jar                  |AppleSkin                     |appleskin                     |2.4.0+mc1.18        |DONE      |Manifest: NOSIGNATURE
		alexsdelight-1.18.2-1.2.3.jar                     |Alex's Delight                |alexsdelight                  |1.2.3               |DONE      |Manifest: NOSIGNATURE
		citadel-1.11.3-1.18.2.jar                         |Citadel                       |citadel                       |1.11.3              |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.18.5.jar                              |Alex's Mobs                   |alexsmobs                     |1.18.5              |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.18.2-1.1.2.jar                   |Farmer's Delight              |farmersdelight                |1.18.2-1.1.2        |DONE      |Manifest: NOSIGNATURE
		NethersDelight-1.18.2-2.2.0.jar                   |Nethers Delight               |nethersdelight                |2.2                 |DONE      |Manifest: NOSIGNATURE
		Cataclysm-0.19.jar                                |Cataclysm Mod                 |cataclysm                     |1.0                 |DONE      |Manifest: NOSIGNATURE
		AI-Improvements-1.18.2-0.5.0.jar                  |AI-Improvements               |aiimprovements                |0.5.0               |DONE      |Manifest: NOSIGNATURE
		FastLeafDecay-28.jar                              |FastLeafDecay                 |fastleafdecay                 |28                  |DONE      |Manifest: NOSIGNATURE
		YungsBetterMineshafts-1.18.2-Forge-2.1.3.jar      |YUNG's Better Mineshafts      |bettermineshafts              |1.18.2-Forge-2.1.3  |DONE      |Manifest: NOSIGNATURE
		valhelsia_core-1.18.2-0.3.1.jar                   |Valhelsia Core                |valhelsia_core                |1.18.2-0.3.1        |DONE      |Manifest: NOSIGNATURE
		valhelsia_structures-forge-1.18.2-0.1.0.jar       |Valhelsia Structures          |valhelsia_structures          |1.18.2-0.1.0        |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.18-3.0.24.jar                    |GeckoLib                      |geckolib3                     |3.0.24              |DONE      |Manifest: NOSIGNATURE
		ecologics-FORGE-1.18.2-1.6.9.jar                  |Ecologics                     |ecologics                     |1.6.9               |DONE      |Manifest: NOSIGNATURE
		OpenLoader-Forge-1.18.2-12.0.1.jar                |OpenLoader                    |openloader                    |12.0.1              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		domesticationinnovation-1.4.2-1.18.2.jar          |Domestication Innovation      |domesticationinnovation       |1.4.2               |DONE      |Manifest: NOSIGNATURE
		xptome-1.18.2-2.1.5.jar                           |XP Tome                       |xpbook                        |2.1.5               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 078dcb08-e395-412f-9e99-d46ec30c268b
	FML: 40.1
	Forge: net.minecraftforge:40.1.48
	Kiwi Modules: 
		kiwi:contributors
		kiwi:data
		snowrealmagic:core

**Comment by Kirishala** [comment]
I am getting the same problem on SP, when trying to use a Lava Vision potion or giving oneself the Lava Vision effect the game crashes immediately and attempts to reload the world will also crash.  I made a clean test install with Forge 40.1.52 (and had observed the crash on earlier versions but do not remember the numbers), Alex's Mobs 1.18.5, and Citidel 1.11.3-1.18.2 (the latest release versions on CurseForge) and got the same results generating the attached crash report 
[crash-2022-06-22_14.42.38-client.txt](https://github.com/Alex-the-666/AlexsMobs/files/8958380/crash-2022-06-22_14.42.38-client.txt)

**Comment by MrJorman** [comment]
+ too problem, my players is gg crashed. lava vision potion - CRASHHH

**Comment by AlexModGuy** [comment]
forge updated some shit that made the logic that the lava potion uses impossible. Either dont use the potion or downgrade forge.
