### ISSUE TITLE
Server crash on startup; com.google.gson.JsonParseException: Error loading registry data: 

### ISSUE THREAD

**Issue by AlexModGuy** [Alex-the-666/AlexsMobs#1340]
17.09 02:01:49 [Server] INFO Caused by: com.google.gson.JsonParseException: Error loading registry data: Unknown element: ResourceKey[minecraft:worldgen/configured_feature / minecraft:mega_jungle_tree]; Unknown element: ResourceKey[minecraft:worldgen/configured_feature / minecraft:jungle_bush]; Unknown element: ResourceKey[minecraft:worldgen/configured_feature / minecraft:fancy_oak]; Unknown element: ResourceKey[minecraft:worldgen/configured_feature / minecraft:spruce]; Unknown element: ResourceKey[minecraft:worldgen/configured_feature / minecraft:pine]
17.09 02:01:49 [Server] INFO 	at net.minecraft.core.RegistryAccess.m_206152_(RegistryAccess.java:211) ~[server-1.19.2-20220805.130853-srg.jar%23137!/:?] {re:classloading,re:mixin}
17.09 02:01:49 [Server] INFO 	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
17.09 02:01:49 [Server] INFO 	at net.minecraft.core.RegistryAccess.m_206159_(RegistryAccess.java:210) ~[server-1.19.2-20220805.130853-srg.jar%23137!/:?] {re:classloading,re:mixin}
17.09 02:01:49 [Server] INFO 	at net.minecraft.core.RegistryAccess.m_206171_(RegistryAccess.java:203) ~[server-1.19.2-20220805.130853-srg.jar%23137!/:?] {re:classloading,re:mixin}
17.09 02:01:49 [Server] INFO 	at net.minecraft.resources.RegistryOps.m_206817_(RegistryOps.java:32) ~[server-1.19.2-20220805.130853-srg.jar%23137!/:?] {re:classloading,pl:accesstransformer:B}
17.09 02:01:49 [Server] INFO 	at net.minecraft.core.RegistryAccess.m_206197_(RegistryAccess.java:183) ~[server-1.19.2-20220805.130853-srg.jar%23137!/:?] {re:classloading,re:mixin}
17.09 02:01:49 [Server] INFO 	at net.minecraft.server.Main.lambda$main$2(Main.java:159) ~[server-1.19.2-20220805.130853-srg.jar%23137!/:?] {re:classloading}
17.09 02:01:49 [Server] INFO 	at net.minecraft.server.WorldLoader.m_214362_(WorldLoader.java:24) ~[server-1.19.2-20220805.130853-srg.jar%23137!/:?] {re:classloading}
17.09 02:01:49 [Server] INFO 	at net.minecraft.server.WorldStem.m_214415_(WorldStem.java:18) ~[server-1.19.2-20220805.130853-srg.jar%23137!/:?] {re:classloading}
17.09 02:01:49 [Server] INFO 	at net.minecraft.server.Main.lambda$main$3(Main.java:158) ~[server-1.19.2-20220805.130853-srg.jar%23137!/:?] {re:classloading}
17.09 02:01:49 [Server] INFO 	at net.minecraft.Util.m_214652_(Util.java:774) ~[server-1.19.2-20220805.130853-srg.jar%23137!/:?] {re:mixin,re:classloading,pl:mixin:APP:bettermineshafts.mixins.json:SuppressLogMixin,pl:mixin:A}
17.09 02:01:49 [Server] INFO 	at net.minecraft.Util.m_214679_(Util.java:769) ~[server-1.19.2-20220805.130853-srg.jar%23137!/:?] {re:mixin,re:classloading,pl:mixin:APP:bettermineshafts.mixins.json:SuppressLogMixin,pl:mixin:A}
17.09 02:01:49 [Server] INFO 	at net.minecraft.server.Main.main(Main.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23137!/:?] {re:classloading}
17.09 02:01:49 [Server] INFO 	... 13 more
17.09 02:01:50 [Multicraft] Server shut down (starting)
17.09 02:01:50 [Multicraft] Restarting crashed server in 10 seconds
17.09 02:01:50 [Multicraft] Server stopped
17.09 02:01:58 [Multicraft] Received stop command
17.09 02:01:58 [Multicraft] Server stopped

**Comment by Daltaxy** [comment]
similar thing when I try to join my server as client : the game crashes.
1.19.2, latest mod version, latest forge version :


>`java.lang.ExceptionInInitializerError
	at TRANSFORMER/alexsmobs@1.12.0/com.github.alexthe666.alexsmobs.client.event.ClientEvents.onRenderWorldLastEvent(ClientEvents.java:358)
	at TRANSFORMER/alexsmobs@1.12.0/com.github.alexthe666.alexsmobs.client.event.__ClientEvents_onRenderWorldLastEvent_RenderLevelLastEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.1.25/net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:272)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1070)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:840)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:212)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.1.25/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.NullPointerException: Registry Object not present: alexsmobs:farseer
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at TRANSFORMER/forge@43.1.25/net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204)
	at TRANSFORMER/alexsmobs@1.12.0/com.github.alexthe666.alexsmobs.client.render.AMItemstackRenderer.lambda$static$0(AMItemstackRenderer.java:122)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.Util.m_137469_(Util.java:368)
	at TRANSFORMER/alexsmobs@1.12.0/com.github.alexthe666.alexsmobs.client.render.AMItemstackRenderer.<clinit>(AMItemstackRenderer.java:41)
	... 25 more
[15:02:59] [Render thread/ERROR]: Unreported exception thrown!
java.lang.ExceptionInInitializerError: null
	at com.github.alexthe666.alexsmobs.client.event.ClientEvents.onRenderWorldLastEvent(ClientEvents.java:358) ~[alexsmobs-1.12.0.jar%23158!/:1.12.0]
	at com.github.alexthe666.alexsmobs.client.event.__ClientEvents_onRenderWorldLastEvent_RenderLevelLastEvent.invoke(.dynamic) ~[alexsmobs-1.12.0.jar%23158!/:1.12.0]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:272) ~[forge-1.19.2-43.1.25-universal.jar%23486!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1070) ~[client-1.19.2-20220805.130853-srg.jar%23481!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:840) ~[client-1.19.2-20220805.130853-srg.jar%23481!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23481!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23481!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23481!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23481!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.25.jar%2395!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.NullPointerException: Registry Object not present: alexsmobs:farseer
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.19.2-43.1.25-universal.jar%23486!/:?]
	at com.github.alexthe666.alexsmobs.client.render.AMItemstackRenderer.lambda$static$0(AMItemstackRenderer.java:122) ~[alexsmobs-1.12.0.jar%23158!/:1.12.0]
	at net.minecraft.Util.m_137469_(Util.java:368) ~[client-1.19.2-20220805.130853-srg.jar%23481!/:?]
	at com.github.alexthe666.alexsmobs.client.render.AMItemstackRenderer.<clinit>(AMItemstackRenderer.java:41) ~[alexsmobs-1.12.0.jar%23158!/:1.12.0]
	... 25 more
[15:03:00] [Render thread/INFO]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggingOut
[15:03:00] [Render thread/INFO]: JEI StartEventObserver transitioning state from ENABLED to DISABLED
[15:03:00] [Render thread/INFO]: Clearing audio channels
[15:03:00] [Render thread/INFO]: Clearing unused audio channels
[15:03:00] [Render thread/FATAL]: Preparing crash report with UUID cfbcad2e-e421-4fc0-82a1-7541bb3e7e8e
[15:03:00] [Render thread/FATAL]: Preparing crash report with UUID e8212cdf-0d53-4312-90ea-1100c8dd8ffc`


server starts fine in my case. simply can't join the world. I thought the issue was related but I can open an issue if needed...

**Comment by AlexModGuy** [comment]
your issue is unrelated; there is a version mismatch between the client and the server, the server is outdated.

**Comment by Daltaxy** [comment]
> your issue is unrelated; there is a version mismatch between the client and the server, the server is outdated.

indeed, but it crashes either way. I deleted and installed the latest version for the mod. crashed at join. going back to the version before fixed the issue

**Comment by AlexModGuy** [comment]
> > your issue is unrelated; there is a version mismatch between the client and the server, the server is outdated.
> 
> indeed, but it crashes either way. I deleted and installed the latest version for the mod. crashed at join. going back to the version before fixed the issue

your issue was still valid; albiet caused by a seperate bug. both issues will be fixed in 1.20.1 which should be out later today or tomorrow.
