### ISSUE TITLE
Crash from cockroach drop?

### ISSUE THREAD

**Issue by Mayzone** [Alex-the-666/AlexsMobs#1369]
`[14:28:56] [Server thread/ERROR] [minecraft/MinecraftServer]:   Cause of unexpected exception was
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.item.ItemEntity.m_32060_()" because "dropped" is null
        at com.github.alexthe666.alexsmobs.entity.EntityCockroach.m_8119_(EntityCockroach.java:321) ~[alexsmobs-1.18.6.jar%2354!/:1.18.6] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:657) ~[server-1.18.2-20220404.173914-srg.jar%23143!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:A}
        at net.minecraft.world.level.Level.m_46653_(Level.java:702) ~[server-1.18.2-20220404.173914-srg.jar%23143!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:314) ~[server-1.18.2-20220404.173914-srg.jar%23143!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:A}
        at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.18.2-20220404.173914-srg.jar%23143!/:?] {re:classloading}
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:294) ~[server-1.18.2-20220404.173914-srg.jar%23143!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1056) ~[server-1.18.2-20220404.173914-srg.jar%23143!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:399) ~[server-1.18.2-20220404.173914-srg.jar%23143!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:975) ~[server-1.18.2-20220404.173914-srg.jar%23143!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:794) ~[server-1.18.2-20220404.173914-srg.jar%23143!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:254) ~[server-1.18.2-20220404.173914-srg.jar%23143!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}`

**Comment by wolflord212312** [comment]
[latest.log](https://github.com/AlexModGuy/AlexsMobs/files/9703287/latest.log)

**Comment by wolflord212312** [comment]
[crash-2022-10-03_23.01.42-server.txt](https://github.com/AlexModGuy/AlexsMobs/files/9703291/crash-2022-10-03_23.01.42-server.txt)

**Comment by Coolkc456** [comment]
I have the same crash due to something involving the cockroach.
https://pastebin.com/zxieUqyE

**Comment by wolflord212312** [comment]
Just to confirm somthing what server software are we all using, are we all using something like magma or somthing of the sorts?
As we are this could be a forge/bukkit/spigot issue that has went under the radar

**Comment by wolflord212312** [comment]
As if we can narrow that down then it is most likely not a mod issue and is a server issue to do with the server jar that was modified

**Comment by Coolkc456** [comment]
I'm using Magma API 1.18.2

**Comment by wolflord212312** [comment]
This issue has been fixed in new magma releases from what I heard, can I have you guys update and test.
