### ISSUE TITLE
Can't access a Trader Elephant's Inventory (Conflict with Wandering Pets)

### ISSUE THREAD

**Issue by Chewypuppielover** [Alex-the-666/AlexsMobs#147]
I get this error (I am also posting this on Wandering Pets).

[22:28:35] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: com.github.alexthe666.alexsmobs.entity.EntityElephant cannot be cast to com.outurnate.wanderingpets.interfaces.IFollowsAccessor
        Index: 10
        Listeners:
                0: HIGH
                1: ASM: class com.simibubi.create.content.contraptions.components.structureMovement.train.MinecartCouplingItem handleInteractionWithMinecart(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
                2: ASM: tschipp.carryon.common.event.ItemEntityEvents@21e95aa9 onEntityRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
                3: NORMAL
                4: net.minecraftforge.eventbus.EventBus$$Lambda$2702/387036735@1ffb2f4b
                5: net.minecraftforge.eventbus.EventBus$$Lambda$2702/387036735@a1ff223
                6: net.minecraftforge.eventbus.EventBus$$Lambda$2702/387036735@4110701e
                7: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
                8: ASM: class com.minecraftabnormals.abnormals_core.core.events.CompatEvents onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
                9: ASM: class com.natamus.moveminecarts.events.MinecartEvent onBoatClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
                10: ASM: com.outurnate.wanderingpets.WanderingPets@7eaed4c2 onEntityInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
                11: ASM: class knightminer.inspirations.tweaks.TweaksEvents milkCow(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
                12: ASM: class knightminer.inspirations.tweaks.TweaksEvents unsaddlePig(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
                13: ASM: class com.simibubi.create.content.contraptions.components.structureMovement.mounted.MinecartContraptionItem wrenchCanBeUsedToPickUpMinecartContraptions(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
                14: ASM: svenhjol.charm.module.BatBuckets@4336af58 onEntityInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
                15: ASM: com.natamus.villagernames.events.VillagerEvent@788fc62c onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
                16: ASM: class cofh.ensorcellation.event.CommonEvents handlePlayerRightClickEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
                17: ASM: class xratedjunior.betterdefaultbiomes.common.enchantment.EnchantmentEventSubscriber onPlayerTick(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
                18: LOWEST
                19: net.minecraftforge.eventbus.EventBus$$Lambda$2702/387036735@19f47cc3
java.lang.ClassCastException: com.github.alexthe666.alexsmobs.entity.EntityElephant cannot be cast to com.outurnate.wanderingpets.interfaces.IFollowsAccessor
        at com.outurnate.wanderingpets.WanderingPets.onEntityInteract(WanderingPets.java:94)
        at net.minecraftforge.eventbus.ASMEventHandler_654_WanderingPets_onEntityInteract_EntityInteract.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.common.ForgeHooks.onInteractEntity(ForgeHooks.java:774)
        at net.minecraft.entity.player.PlayerEntity.func_190775_a(PlayerEntity.java:936)
        at net.minecraft.network.play.ServerPlayNetHandler.func_147340_a(ServerPlayNetHandler.java:1194)
        at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:74)
        at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:13)
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733)
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159)
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716)
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710)
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645)
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232)
        at java.lang.Thread.run(Unknown Source)

[22:28:35] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.ClassCastException: com.github.alexthe666.alexsmobs.entity.EntityElephant cannot be cast to com.outurnate.wanderingpets.interfaces.IFollowsAccessor
        at com.outurnate.wanderingpets.WanderingPets.onEntityInteract(WanderingPets.java:94) ~[?:1.2] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_654_WanderingPets_onEntityInteract_EntityInteract.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.common.ForgeHooks.onInteractEntity(ForgeHooks.java:774) ~[?:?] {re:classloading,re:mixin}
        at net.minecraft.entity.player.PlayerEntity.func_190775_a(PlayerEntity.java:936) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:accessor.PlayerEntityAccessor,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:assets/offhandcombat/offhandcombat.mixins.json:PlayerHeldMixin,pl:mixin:APP:dankstorage.mixins.json:MixinPlayerEntity,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:APP:balancedenchanting.mixins.json:PlayerEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.network.play.ServerPlayNetHandler.func_147340_a(ServerPlayNetHandler.java:1194) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,xf:fml:astralsorcery:allow_entity_interaction,pl:mixin:APP:endergetic.mixins.json:ServerPlayNetHandlerMixin,pl:mixin:APP:performant.mixins.json:connection.ServerPlayNetHandlerMixin,pl:mixin:A}
        at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:74) ~[?:?] {re:classloading}
        at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:13) ~[?:?] {re:classloading}
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181] {}

**Comment by Alex-the-666** [comment]
issue is on wandering pet's side, they should not be casting ny entity to their interface without checking first
> wanderingpets.interfaces.IFollowsAccessor
at com.outurnate.wanderingpets.WanderingPets.onEntityInteract
