### ISSUE TITLE
Loot crash with creeper explosion

### ISSUE THREAD

**Issue by UltraCoolDude** [Alex-the-666/AlexsMobs#156]
When a creeper explodes, if the play has some extra looting level applied the game will crash.
It's not caused by any other mods, alex's mobs seems to be the only thing causing it in the log and when I removed the mod the crash did not occur.

Here's the crash from my log, sorry I didnt upload to pastebin I didnt have the time
`---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2/1/21 8:46 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.github.alexthe666.alexsmobs.event.ServerEvents.onLootLevelEvent(ServerEvents.java:102) ~[?:1.5.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_25_ServerEvents_onLootLevelEvent_LootingLevelEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2614/1862852188.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:391) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:assets/betterhurttimer/betterhurttimer.mixins.json:AttackEntityMixin,pl:mixin:APP:assets/enigmaticlegacy/enigmaticlegacy.mixins.json:MixinForgeHooks,pl:mixin:A}
	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:384) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:assets/betterhurttimer/betterhurttimer.mixins.json:AttackEntityMixin,pl:mixin:APP:assets/enigmaticlegacy/enigmaticlegacy.mixins.json:MixinForgeHooks,pl:mixin:A}
	at net.minecraft.loot.LootContext.getLootingModifier(LootContext.java:98) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.loot.conditions.RandomChanceWithLooting.test(RandomChanceWithLooting.java:36) ~[?:?] {re:classloading}
	at net.minecraft.loot.conditions.RandomChanceWithLooting.test(RandomChanceWithLooting.java:18) ~[?:?] {re:classloading}
	at java.util.function.Predicate.lambda$and$10(Predicate.java:69) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.function.Predicate$$Lambda$495/383810478.test(Unknown Source) ~[?:?] {}
	at net.minecraft.loot.LootPool.func_216091_a(LootPool.java:84) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.loot.LootTable.func_216114_a(LootTable.java:68) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.loot.TableLootEntry.func_216154_a(SourceFile:33) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.silentchaos512.scalinghealth.loot.TableGlobalModifier.doApply(TableGlobalModifier.java:30) ~[?:4.0.3+3] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:53) ~[?:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1262) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:assets/betterhurttimer/betterhurttimer.mixins.json:AttackEntityMixin,pl:mixin:APP:assets/enigmaticlegacy/enigmaticlegacy.mixins.json:MixinForgeHooks,pl:mixin:A}
	at net.minecraft.loot.LootTable.func_216113_a(LootTable.java:86) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.block.AbstractBlock.func_220076_a(AbstractBlock.java:214) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215693_a(AbstractBlock.java:634) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:betterweather.mixins.json:block.MixinAbstractBlockstate,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinAbstractBlockState,pl:mixin:A}
	at net.minecraft.world.Explosion.func_77279_a(Explosion.java:250) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ExplosionAccess,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_230546_a_(ServerWorld.java:1038) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterweather.mixins.json:server.MixinServerWorld,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinServerWorld,pl:mixin:A}
	at net.minecraft.world.World.func_217385_a(World.java:566) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterweather.mixins.json:MixinWorld,pl:mixin:APP:imm_ptl_mixins.json:common.MixinWorld,pl:mixin:A}
	at net.minecraft.entity.monster.CreeperEntity.func_146077_cc(CreeperEntity.java:222) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorCreeperEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.monster.CreeperEntity.func_70071_h_(CreeperEntity.java:146) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorCreeperEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterweather.mixins.json:server.MixinServerWorld,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinServerWorld,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld$$Lambda$18980/677764723.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterweather.mixins.json:MixinWorld,pl:mixin:APP:imm_ptl_mixins.json:common.MixinWorld,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterweather.mixins.json:server.MixinServerWorld,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinServerWorld,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$18046/68412702.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.alexsmobs.event.ServerEvents.onLootLevelEvent(ServerEvents.java:102) ~[?:1.5.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_25_ServerEvents_onLootLevelEvent_LootingLevelEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2614/1862852188.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:391) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:assets/betterhurttimer/betterhurttimer.mixins.json:AttackEntityMixin,pl:mixin:APP:assets/enigmaticlegacy/enigmaticlegacy.mixins.json:MixinForgeHooks,pl:mixin:A}
	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:384) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:assets/betterhurttimer/betterhurttimer.mixins.json:AttackEntityMixin,pl:mixin:APP:assets/enigmaticlegacy/enigmaticlegacy.mixins.json:MixinForgeHooks,pl:mixin:A}
	at net.minecraft.loot.LootContext.getLootingModifier(LootContext.java:98) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.loot.conditions.RandomChanceWithLooting.test(RandomChanceWithLooting.java:36) ~[?:?] {re:classloading}
	at net.minecraft.loot.conditions.RandomChanceWithLooting.test(RandomChanceWithLooting.java:18) ~[?:?] {re:classloading}
	at java.util.function.Predicate.lambda$and$10(Predicate.java:69) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.function.Predicate$$Lambda$495/383810478.test(Unknown Source) ~[?:?] {}
	at net.minecraft.loot.LootPool.func_216091_a(LootPool.java:84) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.loot.LootTable.func_216114_a(LootTable.java:68) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.loot.TableLootEntry.func_216154_a(SourceFile:33) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.silentchaos512.scalinghealth.loot.TableGlobalModifier.doApply(TableGlobalModifier.java:30) ~[?:4.0.3+3] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:53) ~[?:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1262) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:assets/betterhurttimer/betterhurttimer.mixins.json:AttackEntityMixin,pl:mixin:APP:assets/enigmaticlegacy/enigmaticlegacy.mixins.json:MixinForgeHooks,pl:mixin:A}
	at net.minecraft.loot.LootTable.func_216113_a(LootTable.java:86) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.block.AbstractBlock.func_220076_a(AbstractBlock.java:214) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215693_a(AbstractBlock.java:634) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:betterweather.mixins.json:block.MixinAbstractBlockstate,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinAbstractBlockState,pl:mixin:A}
	at net.minecraft.world.Explosion.func_77279_a(Explosion.java:250) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ExplosionAccess,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_230546_a_(ServerWorld.java:1038) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterweather.mixins.json:server.MixinServerWorld,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinServerWorld,pl:mixin:A}
	at net.minecraft.world.World.func_217385_a(World.java:566) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterweather.mixins.json:MixinWorld,pl:mixin:APP:imm_ptl_mixins.json:common.MixinWorld,pl:mixin:A}
	at net.minecraft.entity.monster.CreeperEntity.func_146077_cc(CreeperEntity.java:222) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorCreeperEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.monster.CreeperEntity.func_70071_h_(CreeperEntity.java:146) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorCreeperEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterweather.mixins.json:server.MixinServerWorld,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinServerWorld,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld$$Lambda$18980/677764723.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: minecraft:creeper (net.minecraft.entity.monster.CreeperEntity)
	Entity ID: 552
	Entity Name: Creeper
	Entity's Exact location: 7.50, 4.00, 9.50
	Entity's Block location: World: (7,4,9), Chunk: (at 7,0,9 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterweather.mixins.json:MixinWorld,pl:mixin:APP:imm_ptl_mixins.json:common.MixinWorld,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterweather.mixins.json:server.MixinServerWorld,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinServerWorld,pl:mixin:A}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Wakarimasen1'/550, l='ServerWorld minecraft:overworld World #2945-ES79', x=10.34, y=4.00, z=12.41]]
	Chunk stats: ServerChunkCache: 2209
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,4,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1412 game time, 1412 day time
	Level name: World #2945-ES79
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 114662 (now: false), thunder time: 0 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.alternate_dimension.MixinMinecraftServer_A,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$18046/68412702.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}
`

**Comment by recklessrider** [comment]
Crash log: https://filebin.net/tlu5m2q1clgri3ft/crash-2021-02-06_16.55.25-server.txt?t=qwqpocg6
