### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by Rezzerv** [Alex-the-666/AlexsMobs#1731]
crash report:
java.lang.NullPointerException: effect type cannot be null
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?] {re:mixin,re:mixin,re:mixin}
	at org.apache.commons.lang3.Validate.notNull(Validate.java:224) ~[commons-lang3-3.12.0.jar%2310!/:3.12.0] {}
	at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:47) ~[forge-1.18.2-40.2.10-universal.jar%23149!/:?] {re:classloading}
	at org.bukkit.potion.PotionEffect.<init>(PotionEffect.java:67) ~[forge-1.18.2-40.2.10-universal.jar%23149!/:?] {re:classloading}
	at org.bukkit.craftbukkit.v1_18_R2.potion.CraftPotionUtil.toBukkit(CraftPotionUtil.java:113) ~[forge-1.18.2-40.2.10-universal.jar%23149!/:?] {re:classloading}
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callEntityPotionEffectChangeEvent(CraftEventFactory.java:1523) ~[forge-1.18.2-40.2.10-universal.jar%23149!/:?] {re:classloading}
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callEntityPotionEffectChangeEvent(CraftEventFactory.java:1518) ~[forge-1.18.2-40.2.10-universal.jar%23149!/:?] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:981) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:obscure_api.mixins.json:LivingEntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:maxhealthfix.common.mixins.json:MixinLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:betterdeserttemples.mixins.json:PharaohKilledMixin,pl:mixin:APP:supplementaries.mixins.json:LivingEntityMixin,pl:mixin:APP:kitchenkarrot.mixins.json:MixinLivingEntity,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinLivingEntity,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:LavaSwimmingMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_147207_(LivingEntity.java:961) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:obscure_api.mixins.json:LivingEntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:maxhealthfix.common.mixins.json:MixinLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:betterdeserttemples.mixins.json:PharaohKilledMixin,pl:mixin:APP:supplementaries.mixins.json:LivingEntityMixin,pl:mixin:APP:kitchenkarrot.mixins.json:MixinLivingEntity,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinLivingEntity,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:LavaSwimmingMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_7292_(LivingEntity.java:957) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:obscure_api.mixins.json:LivingEntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:maxhealthfix.common.mixins.json:MixinLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:betterdeserttemples.mixins.json:PharaohKilledMixin,pl:mixin:APP:supplementaries.mixins.json:LivingEntityMixin,pl:mixin:APP:kitchenkarrot.mixins.json:MixinLivingEntity,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinLivingEntity,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:LavaSwimmingMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at com.github.alexthe666.alexsmobs.entity.EntityTiger$AIMelee.m_8037_(EntityTiger.java:626) ~[alexsmobs-1.18.6.jar%2358!/:1.18.6] {re:classloading}
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8037_(WrappedGoal.java:65) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:classloading}
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_186081_(GoalSelector.java:119) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_25373_(GoalSelector.java:110) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:768) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:goodall-common.mixins.json:MobEntityAccessor,pl:mixin:APP:goodall-common.mixins.json:MobEntityMixin,pl:mixin:APP:betteranimalsplus.mixins.json:MobAccessor,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorMob,pl:mixin:APP:tombstone.mixins.json:MobMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2877) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:obscure_api.mixins.json:LivingEntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:maxhealthfix.common.mixins.json:MixinLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:betterdeserttemples.mixins.json:PharaohKilledMixin,pl:mixin:APP:supplementaries.mixins.json:LivingEntityMixin,pl:mixin:APP:kitchenkarrot.mixins.json:MixinLivingEntity,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinLivingEntity,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:LavaSwimmingMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:551) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:goodall-common.mixins.json:MobEntityAccessor,pl:mixin:APP:goodall-common.mixins.json:MobEntityMixin,pl:mixin:APP:betteranimalsplus.mixins.json:MobAccessor,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorMob,pl:mixin:APP:tombstone.mixins.json:MobMixin,pl:mixin:A}
	at net.minecraft.world.entity.AgeableMob.m_8107_(AgeableMob.java:140) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.world.entity.animal.Animal.m_8107_(Animal.java:58) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:AnimalMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2624) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:obscure_api.mixins.json:LivingEntityMixin,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:maxhealthfix.common.mixins.json:MixinLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:betterdeserttemples.mixins.json:PharaohKilledMixin,pl:mixin:APP:supplementaries.mixins.json:LivingEntityMixin,pl:mixin:APP:kitchenkarrot.mixins.json:MixinLivingEntity,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinLivingEntity,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:LavaSwimmingMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:350) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:goodall-common.mixins.json:MobEntityAccessor,pl:mixin:APP:goodall-common.mixins.json:MobEntityMixin,pl:mixin:APP:betteranimalsplus.mixins.json:MobAccessor,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorMob,pl:mixin:APP:tombstone.mixins.json:MobMixin,pl:mixin:A}
	at com.github.alexthe666.alexsmobs.entity.EntityTiger.m_8119_(EntityTiger.java:332) ~[alexsmobs-1.18.6.jar%2358!/:1.18.6] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:691) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:immersive_weathering-common.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:643) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:358) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:immersive_weathering-common.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:338) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:immersive_weathering-common.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1042) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:377) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blueprint.mixins.json:DedicatedServerMixin,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:964) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:787) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:286) ~[server-1.18.2-20220404.173914-srg.jar%23144!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}

MOD LIST:

YUNG's Better Dungeons - 1.18.2-Forge-2.1.0
Player Animator - 1.0.2+1.18
Tinkers' Levelling Addon - 1.3.0
Just Enough Items (JEI) - 10.2.1.1005
Goodall - 1.0.2
YUNG's Better Ocean Monuments - 1.18.2-Forge-1.0.3
Library ferret - 4.0.0
Obscure API - 10
Incendium - 5.0.8
Hourglass - 1.18.2-1.2.1.0
Immersive Weathering - 1.18.2-3.0.3-forge
Journeymap - 5.9.7
Placebo - 6.6.7
Citadel - 1.11.3
Alex's Mobs - 1.18.6
Serene Seasons - 1.18.2-7.0.0.15
Finite Water - 1.18.2-0.1.1
YUNG's API - 1.18.2-Forge-2.2.9
MaxHealthFix - Forge-1.18.2-5.0.4
Phosphophyllite - 1.18.2-0.6.0-beta.1.6
Better Animals Plus - 1.18.2-11.0.10-forge
Bookshelf - Forge-1.18.2-13.3.56
Obscuria's Tooltips - 1.4.1
Kvadrat's LootBags - 1.0.7+Forge1.18.2
Apotheosis - 1.18.2-5.8.0
YUNG's Better Desert Temples - 1.18.2-Forge-1.3.1
Create: Steam 'n Rails - 1.3.5+forge-mc1.18.2
Simply Houses - 1.1.0-1.18.2-forge
Terralith - 1.18.2_v2.2.4
Blueprint - 1.18.2-5.5.0
CraftTweaker - Forge-1.18.2-9.1.208
YUNG's Better Nether Fortresses - 1.18.2-Forge-1.0.0
Cloth Config v4 API - 6.4.90-forge
Forge - 1.18.2-40.2.10-universal
Konkrete - 1.6.1_MC_1.18-1.18.2
Emotecraft - for-MC1.18.2-2.2.7-b.build.48-forge
Selene - 1.18.2-1.17.9
Supplementaries - 1.18.2-1.5.18
Zero CORE 2 - 1.18.2-2.1.35
Minecraft - 1.18.2-20220404.173914-srg
Upgrade Aquatic - 1.18.2-4.0.0
Tinkers' Construct - 1.18.2-3.6.4.113
KitchenKarrot - 1.18.2-0.3.7
EnchantmentDescriptions - Forge-1.18.2-10.0.12
The One Probe - 1.18-5.1.2
Geolosys - 1.18.2-7.0.10
Project Vibrant Journeys - 1.18.2-4.1.0
Do A Barrel Roll - 2.5.3+1.18.2-forge
Plasmo Voice - forge-1.18-1.2.19
CreativeCore - FORGE_v2.6.16_mc1.18.2
ChickenChunks - 1.18.2-2.9.2.95-universal
Domum Ornamentum - 1.18.2-1.0.77-ALPHA-universal
Iceberg - 1.18.2-forge-1.0.49
Flywheel - forge-1.18.2-0.6.8.a
Create - 1.18.2-0.5.1.b
Curios API - forge-1.18.2-5.0.9.1
Patchouli - 1.18.2-71.1
Mantle - 1.18.2-1.9.45
UI Library Mod - 1.18.2-0.0.71-ALPHA
Searchables - forge-1.18.2-1.0.1
AutoRegLib - 1.7-53
Quark - 3.2-358
Storage Drawers - 1.18.2-10.2.1
YUNG's Extras - 1.18.2-Forge-2.1.0
Better village - forge-1.18.2-3.1.0
YUNG's Better Strongholds - 1.18.2-Forge-2.1.0
Corail Tombstone - 7.6.5-1.18.2
Structurize - 1.18.2-1.0.424-ALPHA
Multi-Piston - 1.18.2-1.2.15-ALPHA
Quartz - 1.18.2-0.0.0-beta.1.4
MineColonies - 1.18.2-1.0.1337-ALPHA
MrCrayfish's Furniture Mod - 7.0.0-pre35
Architectury - 4.11.93-forge
FTB Library - forge-1802.3.11-build.177
Item Filters - forge-1802.2.8-build.50
FTB Teams - forge-1802.2.11-build.107
FTB Quests - forge-1802.3.14-build.191
Enhanced Celestials - 1.18.2-2.0.7
Obscuria's Essentials - Forge 1.18.2-3.2.0
Towns and Towers - forge-1.10.0.1+1.18.2
FastLeafDecay - 28
CodeChicken Lib - 1.18.2-4.1.4.488-universal
YUNG's Better Mineshafts - 1.18.2-Forge-2.2
GeckoLib - forge-1.18-3.0.57
Load My Resources - forge_1.0.4_MC_1.18-1.18.2
Aquamirae - 5.api10
CristelliB - forge-1.0.0

**Comment by AlexModGuy** [comment]
> bukkit.potion.PotionEffect

bukkit issue
