### ISSUE TITLE
1.20.1 Crashing when opening the second page of the guide book

### ISSUE THREAD

**Issue by Elisalil** [Alex-the-666/AlexsMobs#1740]
Game crashes every time i try to open the second page of the guide book

**Comment by AmbivalentSoul** [comment]
I've been having this issue too!

**Comment by turtton** [comment]
This issue caused in forge:`47.1.30` but update to `47.1.43`, it looks fixed.

CrashLog(in 47.1.30): 
```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023-07-27 17:54:46
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.EntityDimensions.m_20388_(float)" because "this.size" is null
	at com.github.alexthe666.alexsmobs.entity.EntityCachalotPart.m_6972_(EntityCachalotPart.java:82) ~[alexsmobs-1.22.5.jar%23171!/:1.22.5] {re:classloading}
	at net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3496) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:entityculling.mixins.json:CullableMixin,pl:mixin:APP:balm.mixins.json:EntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Entity.<init>(Entity.java:261) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:entityculling.mixins.json:CullableMixin,pl:mixin:APP:balm.mixins.json:EntityMixin,pl:mixin:A}
	at net.minecraftforge.entity.PartEntity.<init>(PartEntity.java:16) ~[forge-1.20.1-47.1.30-universal.jar%23191!/:?] {re:classloading}
	at com.github.alexthe666.alexsmobs.entity.EntityCachalotPart.<init>(EntityCachalotPart.java:28) ~[alexsmobs-1.22.5.jar%23171!/:1.22.5] {re:classloading}
	at com.github.alexthe666.alexsmobs.entity.EntityCachalotWhale.<init>(EntityCachalotWhale.java:109) ~[alexsmobs-1.22.5.jar%23171!/:1.22.5] {re:classloading}
	at net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:525) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,xf:fml:forge:forge_method_redirector,re:classloading,xf:fml:forge:forge_method_redirector}
	at com.github.alexthe666.citadel.client.gui.EntityLinkButton.m_87963_(EntityLinkButton.java:53) ~[citadel-2.4.2-1.20.1.jar%23174!/:2.4.2-1.20.1] {re:classloading}
	at net.minecraft.client.gui.components.AbstractWidget.m_88315_(AbstractWidget.java:70) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_88315_(Screen.java:119) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.github.alexthe666.citadel.client.gui.GuiBasicBook.m_88315_(GuiBasicBook.java:288) ~[citadel-2.4.2-1.20.1.jar%23174!/:2.4.2-1.20.1] {re:classloading}
	at com.github.alexthe666.alexsmobs.client.gui.GUIAnimalDictionary.m_88315_(GUIAnimalDictionary.java:33) ~[alexsmobs-1.22.5.jar%23171!/:1.22.5] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:423) ~[forge-1.20.1-47.1.30-universal.jar%23191!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:416) ~[forge-1.20.1-47.1.30-universal.jar%23191!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.30.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.30.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.30.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.30.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
```

**Comment by FinaFina233** [comment]
> This issue caused in forge:`47.1.30` but update to `47.1.43`, it looks fixed.
> 
> CrashLog(in 47.1.30):
> 
> ```
> ---- Minecraft Crash Report ----
> // I bet Cylons wouldn't have this problem.
> 
> Time: 2023-07-27 17:54:46
> Description: Rendering screen
> 
> java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.EntityDimensions.m_20388_(float)" because "this.size" is null
> 	at com.github.alexthe666.alexsmobs.entity.EntityCachalotPart.m_6972_(EntityCachalotPart.java:82) ~[alexsmobs-1.22.5.jar%23171!/:1.22.5] {re:classloading}
> 	at net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3496) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:entityculling.mixins.json:CullableMixin,pl:mixin:APP:balm.mixins.json:EntityMixin,pl:mixin:A}
> 	at net.minecraft.world.entity.Entity.<init>(Entity.java:261) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:entityculling.mixins.json:CullableMixin,pl:mixin:APP:balm.mixins.json:EntityMixin,pl:mixin:A}
> 	at net.minecraftforge.entity.PartEntity.<init>(PartEntity.java:16) ~[forge-1.20.1-47.1.30-universal.jar%23191!/:?] {re:classloading}
> 	at com.github.alexthe666.alexsmobs.entity.EntityCachalotPart.<init>(EntityCachalotPart.java:28) ~[alexsmobs-1.22.5.jar%23171!/:1.22.5] {re:classloading}
> 	at com.github.alexthe666.alexsmobs.entity.EntityCachalotWhale.<init>(EntityCachalotWhale.java:109) ~[alexsmobs-1.22.5.jar%23171!/:1.22.5] {re:classloading}
> 	at net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:525) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,xf:fml:forge:forge_method_redirector,re:classloading,xf:fml:forge:forge_method_redirector}
> 	at com.github.alexthe666.citadel.client.gui.EntityLinkButton.m_87963_(EntityLinkButton.java:53) ~[citadel-2.4.2-1.20.1.jar%23174!/:2.4.2-1.20.1] {re:classloading}
> 	at net.minecraft.client.gui.components.AbstractWidget.m_88315_(AbstractWidget.java:70) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.gui.screens.Screen.m_88315_(Screen.java:119) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at com.github.alexthe666.citadel.client.gui.GuiBasicBook.m_88315_(GuiBasicBook.java:288) ~[citadel-2.4.2-1.20.1.jar%23174!/:2.4.2-1.20.1] {re:classloading}
> 	at com.github.alexthe666.alexsmobs.client.gui.GUIAnimalDictionary.m_88315_(GUIAnimalDictionary.java:33) ~[alexsmobs-1.22.5.jar%23171!/:1.22.5] {re:classloading,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:423) ~[forge-1.20.1-47.1.30-universal.jar%23191!/:?] {re:classloading}
> 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:416) ~[forge-1.20.1-47.1.30-universal.jar%23191!/:?] {re:classloading}
> 	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.30.jar:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.30.jar:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.30.jar:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.30.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
> 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
> ```

Mine at 47.1.43 still crashes constantly

**Comment by dodo698** [comment]
same

**Comment by AlexModGuy** [comment]
dupe #1797
