### ISSUE TITLE
(1.20.1) Cachalot Whale not spawning on server

### ISSUE THREAD

**Issue by SerenaLeRulez** [Alex-the-666/AlexsMobs#1746]
I have a world in a dedicated server with some friends and not only I never saw one of these whales but I also often see this line of code appearing:

```
[14:02:30] [Server thread/WARN] [minecraft/NaturalSpawner]: Failed to create mob
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.EntityDimensions.m_20388_(float)" because "this.size" is null
        at com.github.alexthe666.alexsmobs.entity.EntityCachalotPart.m_6972_(EntityCachalotPart.java:82) ~[alexsmobs-1.22.5.jar%23207!/:1.22.5] {re:classloading}
        at net.minecraft.world.entity.Entity.getDimensionsForge(Entity.java:3496) ~[server-1.20.1-20230612.114412-srg.jar%23307!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:netherportalfix.mixins.json:EntityAccessor,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorEntity,pl:mixin:APP:balm.mixins.json:EntityMixin,pl:mixin:APP:supplementaries-common.mixins.json:EntityMixin,pl:mixin:APP:curios.mixins.json:AccessorEntity,pl:mixin:A}
        at net.minecraft.world.entity.Entity.<init>(Entity.java:261) ~[server-1.20.1-20230612.114412-srg.jar%23307!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:netherportalfix.mixins.json:EntityAccessor,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorEntity,pl:mixin:APP:balm.mixins.json:EntityMixin,pl:mixin:APP:supplementaries-common.mixins.json:EntityMixin,pl:mixin:APP:curios.mixins.json:AccessorEntity,pl:mixin:A}
        at net.minecraftforge.entity.PartEntity.<init>(PartEntity.java:16) ~[forge-1.20.1-47.1.28-universal.jar%23312!/:?] {re:classloading}
        at com.github.alexthe666.alexsmobs.entity.EntityCachalotPart.<init>(EntityCachalotPart.java:28) ~[alexsmobs-1.22.5.jar%23207!/:1.22.5] {re:classloading}
        at com.github.alexthe666.alexsmobs.entity.EntityCachalotWhale.<init>(EntityCachalotWhale.java:109) ~[alexsmobs-1.22.5.jar%23207!/:1.22.5] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:525) ~[server-1.20.1-20230612.114412-srg.jar%23307!/:?] {re:mixin,xf:fml:forge:forge_method_redirector,re:classloading,xf:fml:forge:forge_method_redirector,pl:mixin:APP:architectury-common.mixins.json:inject.MixinEntityType,pl:mixin:A}
        at net.minecraft.world.level.NaturalSpawner.m_46988_(NaturalSpawner.java:231) ~[server-1.20.1-20230612.114412-srg.jar%23307!/:?] {re:classloading,xf:fml:forge:forge_method_redirector}
        at net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:169) ~[server-1.20.1-20230612.114412-srg.jar%23307!/:?] {re:classloading,xf:fml:forge:forge_method_redirector}
        at net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23307!/:?] {re:classloading,xf:fml:forge:forge_method_redirector}
        at net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:108) ~[server-1.20.1-20230612.114412-srg.jar%23307!/:?] {re:classloading,xf:fml:forge:forge_method_redirector}
        at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:358) ~[server-1.20.1-20230612.114412-srg.jar%23307!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:312) ~[server-1.20.1-20230612.114412-srg.jar%23307!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:305) ~[server-1.20.1-20230612.114412-srg.jar%23307!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinServerLevel,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23307!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23307!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23307!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23307!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23307!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
```

and i think this might be related with the dictionary crash, since the error message says something about the "this.size" being null as well

**Comment by AlexModGuy** [comment]
dupe #1797
