### ISSUE TITLE
[1.20.1] The game crashes with the Transmutation Table

### ISSUE THREAD

**Issue by Roxber03** [Alex-the-666/AlexsMobs#1759]
The game crashes with the Transmutation Table :(
```java
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2023-08-05 13:25:28
Description: Rendering entry base

java.lang.IllegalArgumentException: Duplicate delegates
	at com.mojang.blaze3d.vertex.VertexMultiConsumer$Double.<init>(VertexMultiConsumer.java:44) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:classloading,xf:OptiFine:default}
	at com.mojang.blaze3d.vertex.VertexMultiConsumer.m_86168_(VertexMultiConsumer.java:20) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:classloading,xf:OptiFine:default}
	at com.github.alexthe666.alexsmobs.client.render.AMItemstackRenderer.m_108829_(AMItemstackRenderer.java:225) ~[alexsmobs-1.22.5.jar%23179!/:1.22.5] {re:classloading}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115143_(ItemRenderer.java:258) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.renderBase(ItemEntryDefinition.java:320) ~[RoughlyEnoughItems-12.0.634.jar%23195!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.renderBase(ItemEntryDefinition.java:250) ~[RoughlyEnoughItems-12.0.634.jar%23195!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderBatched(BatchedEntryRendererManager.java:199) ~[RoughlyEnoughItems-12.0.634.jar%23195!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:128) ~[RoughlyEnoughItems-12.0.634.jar%23195!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.renderEntries(PaginatedEntryListWidget.java:109) ~[RoughlyEnoughItems-12.0.634.jar%23195!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.m_88315_(EntryListWidget.java:196) ~[RoughlyEnoughItems-12.0.634.jar%23195!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:348) ~[RoughlyEnoughItems-12.0.634.jar%23195!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.m_88315_(ScreenOverlayImpl.java:244) ~[RoughlyEnoughItems-12.0.634.jar%23195!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.registry.screen.ScreenRegistryImpl$5.render(ScreenRegistryImpl.java:375) ~[RoughlyEnoughItems-12.0.634.jar%23195!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$onApplied$1(DefaultScreenOverlayRenderer.java:65) ~[RoughlyEnoughItems-12.0.634.jar%23195!/:?] {re:classloading}
	at dev.architectury.event.forge.EventHandlerImplClient.eventContainerScreenEvent(EventHandlerImplClient.java:152) ~[architectury-9.1.12-forge.jar%23181!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at dev.architectury.event.forge.__EventHandlerImplClient_eventContainerScreenEvent_Background.invoke(.dynamic) ~[architectury-9.1.12-forge.jar%23181!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_88315_(AbstractContainerScreen.java:93) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.EffectRenderingInventoryScreen.m_88315_(EffectRenderingInventoryScreen.java:28) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rei.mixins.json:MixinEffectRenderingInventoryScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.m_88315_(CreativeModeInventoryScreen.java:629) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:427) ~[forge-1.20.1-47.1.43-universal.jar%23205!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:420) ~[forge-1.20.1-47.1.43-universal.jar%23205!/:?] {re:classloading}
	at jdk.internal.reflect.GeneratedMethodAccessor18.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:741) ~[preview_OptiFine_1.20.1_HD_U_I6_pre6.jar%23206!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1402) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:tombstone.mixins.json:GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.43.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.vertex.VertexMultiConsumer$Double.<init>(VertexMultiConsumer.java:44) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:classloading,xf:OptiFine:default}
	at com.mojang.blaze3d.vertex.VertexMultiConsumer.m_86168_(VertexMultiConsumer.java:20) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:classloading,xf:OptiFine:default}
	at com.github.alexthe666.alexsmobs.client.render.AMItemstackRenderer.m_108829_(AMItemstackRenderer.java:225) ~[alexsmobs-1.22.5.jar%23179!/:1.22.5] {re:classloading}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115143_(ItemRenderer.java:258) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
-- Screen details --
Details:
	Screen name: net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen
Stacktrace:
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.screen(CrashReportUtils.java:50) ~[RoughlyEnoughItems-12.0.634.jar%23195!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.essential(CrashReportUtils.java:44) ~[RoughlyEnoughItems-12.0.634.jar%23195!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderBatched(BatchedEntryRendererManager.java:203) ~[RoughlyEnoughItems-12.0.634.jar%23195!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:128) ~[RoughlyEnoughItems-12.0.634.jar%23195!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.renderEntries(PaginatedEntryListWidget.java:109) ~[RoughlyEnoughItems-12.0.634.jar%23195!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.m_88315_(EntryListWidget.java:196) ~[RoughlyEnoughItems-12.0.634.jar%23195!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:348) ~[RoughlyEnoughItems-12.0.634.jar%23195!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.m_88315_(ScreenOverlayImpl.java:244) ~[RoughlyEnoughItems-12.0.634.jar%23195!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.registry.screen.ScreenRegistryImpl$5.render(ScreenRegistryImpl.java:375) ~[RoughlyEnoughItems-12.0.634.jar%23195!/:?] {re:classloading}
	at me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$onApplied$1(DefaultScreenOverlayRenderer.java:65) ~[RoughlyEnoughItems-12.0.634.jar%23195!/:?] {re:classloading}
	at dev.architectury.event.forge.EventHandlerImplClient.eventContainerScreenEvent(EventHandlerImplClient.java:152) ~[architectury-9.1.12-forge.jar%23181!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at dev.architectury.event.forge.__EventHandlerImplClient_eventContainerScreenEvent_Background.invoke(.dynamic) ~[architectury-9.1.12-forge.jar%23181!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_88315_(AbstractContainerScreen.java:93) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.EffectRenderingInventoryScreen.m_88315_(EffectRenderingInventoryScreen.java:28) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rei.mixins.json:MixinEffectRenderingInventoryScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.m_88315_(CreativeModeInventoryScreen.java:629) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:427) ~[forge-1.20.1-47.1.43-universal.jar%23205!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:420) ~[forge-1.20.1-47.1.43-universal.jar%23205!/:?] {re:classloading}
	at jdk.internal.reflect.GeneratedMethodAccessor18.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:741) ~[preview_OptiFine_1.20.1_HD_U_I6_pre6.jar%23206!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1402) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:tombstone.mixins.json:GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.43.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


-- Renderer details --
Details:
	Renderer name: me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListStackEntry
	Bounds: me.shedaniel.math.Rectangle@64bc069f[height=18,width=18,x=350,y=175]
	Notice mark: 0
	Interactable: true
	Interactable favorites: true
	Highlight enabled: true
	Tooltip enabled: true
	Background enabled: false
	Entries count: 1

-- Current Rendering Entry --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Entry type: minecraft:item
	Is empty: false
	Entry identifier: alexsmobs:transmutation_table

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition
	Item Type: transmutation_table
	Item Damage: 0
	Item NBT: null
	Item Foil: false

-- Screen details --
Details:
	Screen name: net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1256835136 bytes (1198 MiB) / 1979711488 bytes (1888 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 12
	Microarchitecture: Whiskey Lake
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Virtual Display Device
	Graphics card #0 vendor: Huawei
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=1.0.0.9
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9b41
	Graphics card #1 versionInfo: DriverVersion=27.20.100.8984
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.80
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.80
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 20277.52
	Virtual memory used (MB): 17072.61
	Swap memory total (MB): 12251.73
	Swap memory used (MB): 2844.21
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	OptiFine Version: OptiFine_1.20.1_HD_U_I6_pre6
	OptiFine Build: 20230727-130058
	Render Distance Chunks: 4
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.8984
	OpenGlRenderer: Intel(R) UHD Graphics
	OpenGlVendor: Intel
	CpuCount: 4
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.1.43.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.43.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.1.43.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.1.43.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.43.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		tombstone-8.5.1-1.20.1.jar                        |Corail Tombstone              |tombstone                     |8.5.1               |DONE      |Manifest: NOSIGNATURE
		open-parties-and-claims-forge-1.20.1-0.19.1.jar   |Open Parties and Claims       |openpartiesandclaims          |0.19.1              |DONE      |Manifest: NOSIGNATURE
		majrusz-library-1.20-4.3.2.jar                    |Majrusz Library               |mlib                          |4.3.2               |DONE      |Manifest: NOSIGNATURE
		architectury-9.1.12-forge.jar                     |Architectury                  |architectury                  |9.1.12              |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2-rc1+1.20.jar     |Player Animator               |playeranimator                |1.0.2-rc1+1.20      |DONE      |Manifest: NOSIGNATURE
		majruszs-difficulty-1.20-1.7.7.jar                |Majrusz's Progressive Difficul|majruszsdifficulty            |1.7.7               |DONE      |Manifest: NOSIGNATURE
		FallingTree-1.20.1-4.2.4.jar                      |FallingTree                   |fallingtree                   |4.2.4               |DONE      |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		RoughlyEnoughItems-12.0.634.jar                   |Roughly Enough Items (REI)    |roughlyenoughitems            |12.0.634            |DONE      |Manifest: NOSIGNATURE
		cloth-config-11.1.106-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.106            |DONE      |Manifest: NOSIGNATURE
		simplyswords-forge-1.51.0-1.20.1.jar              |Simply Swords                 |simplyswords                  |1.51.0-1.20.1       |DONE      |Manifest: NOSIGNATURE
		bettercombat-forge-1.7.2+1.20.1.jar               |Better Combat                 |bettercombat                  |1.7.2+1.20.1        |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.1.43-universal.jar                |Forge                         |forge                         |47.1.43             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		appleskin-forge-mc1.20.1-2.5.0.jar                |AppleSkin                     |appleskin                     |2.5.0+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		curios-forge-5.2.0-beta.3+1.20.1.jar              |Curios API                    |curios                        |5.2.0-beta.3+1.20.1 |DONE      |Manifest: NOSIGNATURE
		invhud.forge.1.20.1-3.4.17.jar                    |Inventory HUD+(Forge edition) |inventoryhud                  |3.4.17              |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_23.6.0_Forge_1.20.jar              |Xaero's Minimap               |xaerominimap                  |23.6.0              |DONE      |Manifest: NOSIGNATURE
		right-click-harvest-3.2.0+1.20.1-forge.jar        |Right Click Harvest           |rightclickharvest             |3.2.0+1.20.1-forge  |DONE      |Manifest: NOSIGNATURE
		DungeonsArise-1.20.1-2.1.56.1-beta.jar            |When Dungeons Arise           |dungeons_arise                |2.1.56.1-1.20.1     |DONE      |Manifest: NOSIGNATURE
		citadel-2.4.2-1.20.1.jar                          |Citadel                       |citadel                       |2.4.2               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.22.5.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.5              |DONE      |Manifest: NOSIGNATURE
		L_Enders_Cataclysm-1.28-1.20.1.jar                |Cataclysm Mod                 |cataclysm                     |1.0                 |DONE      |Manifest: NOSIGNATURE
		TravelersBackpack-1.20.1-9.1.4.jar                |Traveler's Backpack           |travelersbackpack             |9.1.4               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: a607139f-2a58-493b-bea9-773c30c2d341
	FML: 47.1
	Forge: net.minecraftforge:47.1.43
```

**Comment by Obesemicrowave** [comment]
im having this same issue

**Comment by GenDutchman** [comment]
Same issue here, has anyone solved?

**Comment by AlexModGuy** [comment]
dupe #1796
