### ISSUE TITLE
Server crashes some time after turning on

### ISSUE THREAD

**Issue by Rutyrek** [Alex-the-666/AlexsMobs#1762]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-08-07 19:29:31
Description: Ticking entity

java.lang.IllegalAccessError: class com.github.alexthe666.citadel.server.entity.collision.ICustomCollisions tried to access private field net.minecraft.world.entity.Entity.f_19793_ (com.github.alexthe666.citadel.server.entity.collision.ICustomCollisions is in module citadel@2.4.1 of loader 'TRANSFORMER' @6920b0bc; net.minecraft.world.entity.Entity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @6920b0bc)
	at com.github.alexthe666.citadel.server.entity.collision.ICustomCollisions.getAllowedMovementForEntity(ICustomCollisions.java:30) ~[citadel-2.4.1-1.20.jar%23110!/:2.4.1-1.20] {re:classloading}
	at com.github.alexthe666.alexsmobs.entity.EntityRockyRoller.m_20272_(EntityRockyRoller.java:316) ~[alexsmobs-1.22.5.jar%23107!/:1.22.5] {re:classloading}
	at net.minecraft.world.entity.Entity.m_6478_(Entity.java:632) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_21074_(LivingEntity.java:2189) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_7023_(LivingEntity.java:2126) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2599) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:536) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.monster.Monster.m_8107_(Monster.java:42) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2292) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:classloading,pl:accesstransformer:B}
	at com.github.alexthe666.alexsmobs.entity.EntityRockyRoller.m_8119_(EntityRockyRoller.java:118) ~[alexsmobs-1.22.5.jar%23107!/:1.22.5] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:273) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.citadel.server.entity.collision.ICustomCollisions.getAllowedMovementForEntity(ICustomCollisions.java:30) ~[citadel-2.4.1-1.20.jar%23110!/:2.4.1-1.20] {re:classloading}
	at com.github.alexthe666.alexsmobs.entity.EntityRockyRoller.m_20272_(EntityRockyRoller.java:316) ~[alexsmobs-1.22.5.jar%23107!/:1.22.5] {re:classloading}
	at net.minecraft.world.entity.Entity.m_6478_(Entity.java:632) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_21074_(LivingEntity.java:2189) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_7023_(LivingEntity.java:2126) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2599) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:536) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.monster.Monster.m_8107_(Monster.java:42) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2292) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:classloading,pl:accesstransformer:B}
	at com.github.alexthe666.alexsmobs.entity.EntityRockyRoller.m_8119_(EntityRockyRoller.java:118) ~[alexsmobs-1.22.5.jar%23107!/:1.22.5] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:A}
-- Entity being ticked --
Details:
	Entity Type: alexsmobs:rocky_roller (com.github.alexthe666.alexsmobs.entity.EntityRockyRoller)
	Entity ID: 687
	Entity Name: Rocky Roller
	Entity's Exact location: 85.50, 36.00, 7.50
	Entity's Block location: World: (85,36,7), Section: (at 5,4,7 in 5,2,0; chunk contains blocks 80,-64,0 to 95,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:273) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['Rutyr'/198, l='ServerLevel[world]', x=3.53, y=83.28, z=49.47]]
	Chunk stats: 3381
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,64,32), Section: (at 0,0,0 in 0,4,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2562 game time, 2562 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 40003 (now: false), thunder time: 50864 (now: false)
	Known server brands: forge
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:273) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 5.4.0-150-generic
	Java Version: 17.0.8, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 350592104 bytes (334 MiB) / 1561329664 bytes (1489 MiB) up to 2086666240 bytes (1990 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD EPYC 7713 64-Core Processor
	Identifier: AuthenticAMD Family 25 Model 1 Stepping 1
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Device
	Graphics card #0 vendor: Vendor (0x1234)
	Graphics card #0 VRAM (MB): 16.00
	Graphics card #0 deviceId: 0x1111
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 3310.61
	Virtual memory used (MB): 5124.05
	Swap memory total (MB): 512.00
	Swap memory used (MB): 0.00
	JVM Flags: 0 total; 
	Server Running: true
	Player Count: 1 / 20; [ServerPlayer['Rutyr'/198, l='ServerLevel[world]', x=3.53, y=83.28, z=49.47]]
	Data Packs: vanilla, mod:terrablender (incompatible), mod:forge, mod:aquaculture, mod:biomesoplenty (incompatible), mod:creativecore, mod:corpse, mod:citadel (incompatible), mod:alexsmobs (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.1.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.1.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.1.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		server-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.20-3.0.0.163.jar             |TerraBlender                  |terrablender                  |3.0.0.163           |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.1.0-universal.jar                 |Forge                         |forge                         |47.1.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Aquaculture-1.20.1-2.5.0.jar                      |Aquaculture 2                 |aquaculture                   |2.5.0               |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.20.1-18.0.0.592.jar               |Biomes O' Plenty              |biomesoplenty                 |18.0.0.592          |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.10.32_mc1.20.1.jar          |CreativeCore                  |creativecore                  |2.10.32             |DONE      |Manifest: NOSIGNATURE
		corpse-1.20.1-1.0.5.jar                           |Corpse                        |corpse                        |1.20.1-1.0.5        |DONE      |Manifest: NOSIGNATURE
		citadel-2.4.1-1.20.jar                            |Citadel                       |citadel                       |2.4.1               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.22.5.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.5              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 44e15a5c-dd17-4b6b-bc08-8cdfdf8f1f9a
	FML: 47.1
	Forge: net.minecraftforge:47.1.0

**Comment by AlexModGuy** [comment]
update citadel
