### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by Thoddius** [Alex-the-666/AlexsMobs#179]
alexsmobs-1.5.1.jar
forge-1.16.4-35.1.37.jar
minecraft_server.1.16.4.jar
Trashed prefs from version 1.5.0

Pertinent info:
[09Feb2021 04:46:12.618] [main/FATAL] [net.minecraft.server.Main/]: Failed to start the minecraft server
java.lang.NullPointerException: null
	at com.github.alexthe666.citadel.config.biome.SpawnBiomeData$SpawnBiomeEntry.matches(SpawnBiomeData.java:84) ~[citadel:1.6.0]
	at com.github.alexthe666.citadel.config.biome.SpawnBiomeData.matches(SpawnBiomeData.java:43) ~[citadel:1.6.0]
	at com.github.alexthe666.alexsmobs.config.BiomeConfig.test(BiomeConfig.java:75) ~[alexsmobs:1.5.1]
	at com.github.alexthe666.alexsmobs.world.AMWorldRegistry.onBiomesLoad(AMWorldRegistry.java:18) ~[alexsmobs:1.5.1]
	at com.github.alexthe666.alexsmobs.AlexsMobs.onBiomeLoadFromJSON(AlexsMobs.java:76) ~[alexsmobs:1.5.1]
	at net.minecraftforge.eventbus.ASMEventHandler_428_AlexsMobs_onBiomeLoadFromJSON_BiomeLoadingEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.enhanceBiome(ForgeHooks.java:916) ~[forge:?]
	at net.minecraft.world.biome.Biome.lambda$null$8(Biome.java:75) ~[?:?]
	at com.mojang.datafixers.util.Function8.lambda$null$6(Function8.java:22) ~[?:?]
	at com.mojang.datafixers.util.Function4.lambda$null$2(Function4.java:14) ~[?:?]
	at com.mojang.serialization.DataResult$Instance.ap2(DataResult.java:315) ~[?:?]
	at com.mojang.datafixers.kinds.Applicative.ap4(Applicative.java:84) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$7.decode(RecordCodecBuilder.java:404) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[?:?]
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[?:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[?:?]
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[?:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[?:?]
	at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[?:?]
	at net.minecraft.util.registry.WorldSettingsImport$IResourceAccess$1.func_241879_a(WorldSettingsImport.java:194) ~[?:?]
	at net.minecraft.util.registry.WorldSettingsImport.func_241805_a_(WorldSettingsImport.java:131) ~[?:?]
	at net.minecraft.util.registry.WorldSettingsImport.lambda$decode$5(WorldSettingsImport.java:105) ~[?:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[?:?]
	at net.minecraft.util.registry.WorldSettingsImport.func_241797_a_(WorldSettingsImport.java:104) ~[?:?]
	at net.minecraft.util.registry.DynamicRegistries.func_243610_a(DynamicRegistries.java:144) ~[?:?]
	at net.minecraft.util.registry.DynamicRegistries.func_243608_a(DynamicRegistries.java:132) ~[?:?]
	at net.minecraft.util.registry.WorldSettingsImport.func_244336_a(WorldSettingsImport.java:53) ~[?:?]
	at net.minecraft.util.registry.WorldSettingsImport.func_244335_a(WorldSettingsImport.java:48) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:138) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212-1-ojdkbuild]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212-1-ojdkbuild]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212-1-ojdkbuild]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212-1-ojdkbuild]
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.4-35.1.37.jar:35.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.4-35.1.37.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.4-35.1.37.jar:?]
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.4-35.1.37.jar:?]

**Comment by vlrtm123** [comment]
same forge-1.16.5d-36.0.15

**Comment by Alex-the-666** [comment]
https://www.curseforge.com/minecraft/mc-mods/citadel/files/3198842
