### ISSUE TITLE
[1.0.1] LavaVision crash ?

### ISSUE THREAD

**Issue by Daejangnamu** [Alex-the-666/AlexsMobs#18]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 20. 12. 9 오전 10:06
Description: Tesselating liquid in world

java.lang.NullPointerException: Tesselating liquid in world
	at net.minecraft.client.renderer.FluidBlockRenderer.func_228796_a_(FluidBlockRenderer.java:409) ~[?:?] {re:classloading,xf:OptiFine:default}
	at com.github.alexthe666.alexsmobs.client.render.LavaVisionFluidRenderer.func_228796_a_(LavaVisionFluidRenderer.java:256) ~[?:1.0.1] {re:classloading}
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_228794_a_(BlockRendererDispatcher.java:98) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:845) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:721) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$1(ChunkRenderDispatcher.java:180) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$$Lambda$6735/2030123.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1624) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.FluidBlockRenderer.func_228796_a_(FluidBlockRenderer.java:409) ~[?:?] {re:classloading,xf:OptiFine:default}
	at com.github.alexthe666.alexsmobs.client.render.LavaVisionFluidRenderer.func_228796_a_(LavaVisionFluidRenderer.java:256) ~[?:1.0.1] {re:classloading}
-- Block being tesselated --
Details:
	Block location: World: (1413,64,1863), Chunk: (at 5,4,7 in 88,116; contains blocks 1408,0,1856 to 1423,255,1871), Region: (2,3; contains chunks 64,96 to 95,127, blocks 1024,0,1536 to 1535,255,2047)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_228794_a_(BlockRendererDispatcher.java:98) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Daejangnamu'/85, l='ClientLevel', x=1439.83, y=73.14, z=1756.92]]
	Chunk stats: Client Chunk Cache: 625, 401
	Level dimension: my_dimensions:iceandfire
	Level spawn location: World: (32,67,-96), Chunk: (at 0,4,0 in 2,-6; contains blocks 32,0,-96 to 47,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 30087 game time, 30087 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$3(ChunkRenderDispatcher.java:186) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$$Lambda$6784/1426887756.accept(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1624) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1582983352 bytes (1509 MB) / 3355443200 bytes (3200 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.4_HD_U_G5.jar OptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.4-0.4.1.jar optiforge TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.0.jar fml TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.4-0.4.1.jar FakeOptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.4-0.4.1.jar optiforgewrapper TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.0
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.0-client.jar                    |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		OptiForge-MC1.16.4-0.4.1.jar                      |OptiForge                     |optiforge                     |0.4.1               |DONE      |NOSIGNATURE
		incontrol-1.16-5.0.3.jar                          |InControl                     |incontrol                     |1.16-5.0.3          |DONE      |NOSIGNATURE
		ftb-gui-library-1603.1.1.25.jar                   |FTB GUI Library               |ftbguilibrary                 |1603.1.1.25         |DONE      |NOSIGNATURE
		ftb-teams-1.0.1.12.jar                            |FTB Teams                     |ftbteams                      |1.0.1.12            |DONE      |NOSIGNATURE
		ftb-chunks-1603.2.0.45.jar                        |FTB Chunks                    |ftbchunks                     |1603.2.0.45         |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.0-universal.jar                 |Forge                         |forge                         |35.1.0              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Wyrmroost-1.16.3-1.2.7.jar                        |Wyrmroost                     |wyrmroost                     |1.16.3-1.2.7        |DONE      |NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |NOSIGNATURE
		citadel-1.5.3.jar                                 |Citadel                       |citadel                       |1.5.3               |DONE      |NOSIGNATURE
		alexsmobs-1.0.1.jar                               |Alex's Mobs                   |alexsmobs                     |1.0.1               |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.0.58.jar                           |Just Enough Items             |jei                           |7.6.0.58            |DONE      |NOSIGNATURE
	Crash Report UUID: 6adc8a14-70d3-4e45-b5b8-582a94646706
	Launched Version: 1.16.4-forge-35.1.0
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: ~~ERROR~~ IllegalStateException: Rendersystem called from wrong thread
	GL Caps: Using framebuffer using OpenGL 3.0

**Comment by Carro1001** [comment]
Can you try with optifine's default settings? and fast render turned off

**Comment by Carro1001** [comment]
And also without optiforge if you can

**Comment by Daejangnamu** [comment]
> And also without optiforge if you can

I'll test it tomorrow
