### ISSUE TITLE
Rainbow Jelly causes crash while rendering (happens when opening book as well as with the real mob)

### ISSUE THREAD

**Issue by Stickman036** [Alex-the-666/AlexsMobs#1816]
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 2023-09-27 02:00:24
Description: Rendering entity in world

java.lang.IllegalArgumentException: Duplicate delegates
	at com.mojang.blaze3d.vertex.VertexMultiConsumer$Double.<init>(VertexMultiConsumer.java:44) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:classloading,xf:OptiFine:default}
	at com.mojang.blaze3d.vertex.VertexMultiConsumer.m_86168_(VertexMultiConsumer.java:20) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:classloading,xf:OptiFine:default}
	at com.github.alexthe666.alexsmobs.client.render.RenderCombJelly$RainbowLayer.render(RenderCombJelly.java:61) ~[alexsmobs-1.22.6.jar%23171!/:1.22.6] {re:classloading}
	at com.github.alexthe666.alexsmobs.client.render.RenderCombJelly$RainbowLayer.m_6494_(RenderCombJelly.java:54) ~[alexsmobs-1.22.6.jar%23171!/:1.22.6] {re:classloading}
	at net.minecraft.client.renderer.entity.LivingEntityRenderer.m_7392_(LivingEntityRenderer.java:215) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:citadel.mixins.json:client.LivingEntityRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.MobRenderer.m_7392_(MobRenderer.java:55) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.entity.MobRenderer.m_7392_(MobRenderer.java:20) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:190) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.LevelRenderer.m_109517_(LevelRenderer.java:2312) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:citadel.mixins.json:client.LevelRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1865) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:citadel.mixins.json:client.LevelRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1651) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1279) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.1.43.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.vertex.VertexMultiConsumer$Double.<init>(VertexMultiConsumer.java:44) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:classloading,xf:OptiFine:default}
	at com.mojang.blaze3d.vertex.VertexMultiConsumer.m_86168_(VertexMultiConsumer.java:20) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:classloading,xf:OptiFine:default}
	at com.github.alexthe666.alexsmobs.client.render.RenderCombJelly$RainbowLayer.render(RenderCombJelly.java:61) ~[alexsmobs-1.22.6.jar%23171!/:1.22.6] {re:classloading}
	at com.github.alexthe666.alexsmobs.client.render.RenderCombJelly$RainbowLayer.m_6494_(RenderCombJelly.java:54) ~[alexsmobs-1.22.6.jar%23171!/:1.22.6] {re:classloading}
	at net.minecraft.client.renderer.entity.LivingEntityRenderer.m_7392_(LivingEntityRenderer.java:215) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:citadel.mixins.json:client.LivingEntityRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.MobRenderer.m_7392_(MobRenderer.java:55) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.entity.MobRenderer.m_7392_(MobRenderer.java:20) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:190) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.LevelRenderer.m_109517_(LevelRenderer.java:2312) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:citadel.mixins.json:client.LevelRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1865) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:citadel.mixins.json:client.LevelRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1651) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
-- Entity being rendered --
Details:
	Entity Type: alexsmobs:comb_jelly (com.github.alexthe666.alexsmobs.entity.EntityCombJelly)
	Entity ID: 153
	Entity Name: Kammgelee
	Entity's Exact location: 1630.50, 58.00, 515.87
	Entity's Block location: World: (1630,58,515), Section: (at 14,10,3 in 101,3,32; chunk contains blocks 1616,-64,512 to 1631,319,527), Region: (3,1; contains chunks 96,32 to 127,63, blocks 1536,-64,512 to 2047,319,1023)
	Entity's Momentum: 0.00, 0.00, 0.01
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:190) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.LevelRenderer.m_109517_(LevelRenderer.java:2312) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:citadel.mixins.json:client.LevelRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1865) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:citadel.mixins.json:client.LevelRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1651) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1279) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.1.43.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Renderer details --
Details:
	Assigned renderer: com.github.alexthe666.alexsmobs.client.render.RenderCombJelly@62b5a16f
	Location: 3.01,-4.01,30.14 - World: (3,-5,30), Section: (at 3,11,14 in 0,-1,1; chunk contains blocks 0,-64,16 to 15,319,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Rotation: -167.34375
	Delta: 0.42000294
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:190) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.LevelRenderer.m_109517_(LevelRenderer.java:2312) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:citadel.mixins.json:client.LevelRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1865) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:citadel.mixins.json:client.LevelRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1651) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1279) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.1.43.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Stickman036'/108, l='ClientLevel', x=1627.49, y=60.37, z=485.74]]
	Chunk stats: 6241, 526
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,79,32), Section: (at 0,15,0 in 0,4,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 4521843 game time, 5080726 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:590) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:mixin,xf:OptiFine:default,xf:fml:xaerominimap:xaero_clientworldclass,re:classloading,xf:OptiFine:default,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:citadel.mixins.json:client.ClientLevelMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:735) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.1.43.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.43.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, mod_resources

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 927619080 bytes (884 MiB) / 2579496960 bytes (2460 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-10900KF CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2489
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3742
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 30127.43
	Virtual memory used (MB): 19411.15
	Swap memory total (MB): 13824.00
	Swap memory used (MB): 482.88
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Launched Version: forge-47.1.43
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 537.42, NVIDIA Corporation
	Window size: 3840x2160
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Texture name does not refer to a texture object generated by OpenGL.' x 1
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fabulous
	Resource Packs: vanilla, mod_resources
	Current Language: de_de
	CPU: 20x Intel(R) Core(TM) i9-10900KF CPU @ 3.70GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Stickman036'/108, l='ServerLevel[Das Raphuhn]', x=1627.49, y=60.37, z=485.74]]
	Data Packs: vanilla, mod:fishingreal (incompatible), mod:giraffemod, mod:forge, mod:xaerominimap, mod:simpleplanes (incompatible), mod:underground_villages, mod:automobility (incompatible), mod:citadel (incompatible), mod:alexsmobs (incompatible), mod:guardvillagers (incompatible), mod:jei, mod:craftable_saddles (incompatible), mod:fallingtree (incompatible), mod:cloth_config (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	OptiFine Version: OptiFine_1.20.1_HD_U_I6_pre6
	OptiFine Build: 20230727-130058
	Render Distance Chunks: 36
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 537.42
	OpenGlRenderer: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 20
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.1.43.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.43.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.1.43.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.1.43.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.43.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		guardvillagers-1.20-1.6.1.jar                     |Guard Villagers               |guardvillagers                |1.20-1.6.1          |DONE      |Manifest: NOSIGNATURE
		simpleplanes-1.20.1-5.2.4.jar                     |Simple Planes                 |simpleplanes                  |1.20.1-5.2.4        |DONE      |Manifest: NOSIGNATURE
		UndergroundVillages-1.20.1-2.0.0.jar              |Underground Villages Mod      |underground_villages          |2.0.0               |DONE      |Manifest: NOSIGNATURE
		automobility-0.4.2+1.20.1-forge.jar               |Automobility                  |automobility                  |0.4.2+1.20.1-forge  |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.27.jar                    |Just Enough Items             |jei                           |15.2.0.27           |DONE      |Manifest: NOSIGNATURE
		Fishingreal-1.20.1-1.7.1.jar                      |Fishingreal                   |fishingreal                   |1.20.1-1.7.1        |DONE      |Manifest: NOSIGNATURE
		FallingTree-1.20.1-5.0.0b1.jar                    |FallingTree                   |fallingtree                   |5.0.0b1             |DONE      |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		giraffemod-1.1.4.jar                              |Giraffe Mod                   |giraffemod                    |1.1.4               |DONE      |Manifest: NOSIGNATURE
		cloth-config-11.1.106-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.106            |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.1.43-universal.jar                |Forge                         |forge                         |47.1.43             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Craftable Saddles [1.20 All]-1.4.jar              |Craftable Saddles             |craftable_saddles             |1.4                 |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_23.8.2_Forge_1.20.jar              |Xaero's Minimap               |xaerominimap                  |23.8.2              |DONE      |Manifest: NOSIGNATURE
		citadel-2.4.4-1.20.1.jar                          |Citadel                       |citadel                       |2.4.4               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.22.6.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.6              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 60d4a57a-5e06-4bc7-82d9-de5cd31414fd
	FML: 47.1
	Forge: net.minecraftforge:47.1.43

**Comment by RiyDoesNothing** [comment]
It's probably because of optifine

**Comment by Amberient** [comment]
the same thing is happening to me -- a fix would be welcome!

**Comment by MagmaLair** [comment]
For the mean time I have just turned off Rainbow Jelly spawns in the config. Can't use the book but the world doesn't crash.

**Comment by MoriQuendi23** [comment]
can confirm, had to disable the spawn completely and never been able to use the book.

**Comment by AlexModGuy** [comment]
dupe #1900
