### ISSUE TITLE
When spam clicking items in the transmutation table, Accessing LegacyRandomSource from multiple threads in Alex's Mobs version 1.22.6

### ISSUE THREAD

**Issue by Molioron** [Alex-the-666/AlexsMobs#1862]
Minecraft version: 1.20.1
Forge version: 47.2.4
Alex's Mobs version: 1.22.6

Might be a mod conflict with xaero's world map.
Despite the crash being fixed [here](https://github.com/AlexModGuy/AlexsMobs/issues/1753), the issue persists in 1.22.6.

```
Description: Accessing LegacyRandomSource from multiple threads

java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
	at net.minecraft.util.ThreadingDetector.m_199417_(ThreadingDetector.java:84) ~[client-1.20.1-20230612.114412-srg.jar%23246!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.LegacyRandomSource.m_64707_(LegacyRandomSource.java:49) ~[client-1.20.1-20230612.114412-srg.jar%23246!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.BitRandomSource.m_188503_(BitRandomSource.java:27) ~[client-1.20.1-20230612.114412-srg.jar%23246!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.level.NaturalSpawner.m_47062_(NaturalSpawner.java:277) ~[client-1.20.1-20230612.114412-srg.jar%23246!/:?] {re:mixin,xf:fml:forge:forge_method_redirector,re:classloading,xf:fml:forge:forge_method_redirector,pl:mixin:APP:alexscaves.mixins.json:NaturalSpawnerMixin,pl:mixin:A}
	at net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:116) ~[client-1.20.1-20230612.114412-srg.jar%23246!/:?] {re:mixin,xf:fml:forge:forge_method_redirector,re:classloading,xf:fml:forge:forge_method_redirector,pl:mixin:APP:alexscaves.mixins.json:NaturalSpawnerMixin,pl:mixin:A}
	at net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:108) ~[client-1.20.1-20230612.114412-srg.jar%23246!/:?] {re:mixin,xf:fml:forge:forge_method_redirector,re:classloading,xf:fml:forge:forge_method_redirector,pl:mixin:APP:alexscaves.mixins.json:NaturalSpawnerMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:358) ~[client-1.20.1-20230612.114412-srg.jar%23246!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:312) ~[client-1.20.1-20230612.114412-srg.jar%23246!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:305) ~[client-1.20.1-20230612.114412-srg.jar%23246!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinServerLevel,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23246!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23246!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23246!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23246!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23246!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,xf:fml:xaerominimap:xaero_minecraftserver,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
```

**Comment by DevDyna** [comment]
I can confirm that persist this issue on 1.22.6
