### ISSUE TITLE
alexsmobs-1.21.1 for Forge 1.19.2 Game freezes due to: Async chunk load took way too long

### ISSUE THREAD

**Issue by Minebrah** [Alex-the-666/AlexsMobs#1936]
A single server tick has taken 40001, more than 40000 milliseconds

https://gist.github.com/Minebrah/119a74bb384f8ba9d19075c8ff06d885

**Comment by lSherozl** [comment]
im having the same issue, I encountered yet again, another alex mobs elephant issue: [01:13:58] [Worker-Main-7/ERROR]: Async chunk load took way too long, this needs to be reported to the appropriate mod.
java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.handler$zdn000$bailIfServerDead(ServerChunkCache.java:2616) ~[client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java) ~[client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at net.minecraft.world.level.Level.m_6522_(Level.java:179) ~[client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at net.minecraft.world.level.Level.m_6325_(Level.java:5049) ~[client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at net.minecraft.world.level.Level.m_8055_(Level.java:5541) ~[client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at net.minecraft.world.level.LevelReader.m_46855_(LevelReader.java:153) ~[client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at net.minecraft.world.entity.Mob.m_6914_(Mob.java:806) ~[client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at com.github.alexthe666.alexsmobs.entity.EntityElephant.canSpawnWithTraderHere(EntityElephant.java:996) ~[alexsmobs-1.21.1.jar%23612!/:1.21.1]
	at com.github.alexthe666.alexsmobs.event.ServerEvents.onEntityJoinWorld(ServerEvents.java:494) ~[alexsmobs-1.21.1.jar%23612!/:1.21.1]
	at com.github.alexthe666.alexsmobs.event.__ServerEvents_onEntityJoinWorld_SpecialSpawn.invoke(.dynamic) ~[alexsmobs-1.21.1.jar%23612!/:1.21.1]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraftforge.event.ForgeEventFactory.doSpecialSpawn(ForgeEventFactory.java:201) ~[forge-1.19.2-43.3.5-universal.jar%231047!/:?]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.lambda$addEntitiesToWorld$5(StructureTemplate.java:423) ~[client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.addEntitiesToWorld(StructureTemplate.java:418) ~[client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.m_230328_(StructureTemplate.java:337) ~[client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at net.minecraft.world.level.levelgen.structure.pools.SinglePoolElement.m_213695_(SinglePoolElement.java:127) ~[client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.m_226509_(PoolElementStructurePiece.java:89) ~[client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.m_213694_(PoolElementStructurePiece.java:85) ~[client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at net.minecraft.world.level.levelgen.structure.StructureStart.m_226850_(StructureStart.java:89) ~[client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.m_223080_(ChunkGenerator.java:429) ~[client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar%23121!/:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(ChunkGenerator.java:428) ~[client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_223313_(ChunkStatus.java:145) ~[client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_223279_(ChunkStatus.java:292) ~[client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$25(ChunkMap.java:621) ~[client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar%23126!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:619) ~[client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) [client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) [client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) [client-1.19.2-20220805.130853-srg.jar%231042!/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[01:14:38] [ModernFix integrated server watchdog/ERROR]: A single server tick has taken 40011, more than 40000 milliseconds
[01:14:40] [ModernFix integrated server watchdog/ERROR]: Thread Dump:

**Comment by lSherozl** [comment]
My previous report Elephant Nukes the Server 1.19.2 #1803 was closed, which means either there was an updated mod file posted somewhere or the issue was not resolved, the best way to reproduce this issue is to just keep Tp around the world, I do it in intervals of 10000 each, eventually you will not load anymore chunks and it will freeze, OR, what happened in my case was I was searching for a biome in chunks that were loading fine, and then it froze after searching, so even looking up biomes causes it to crash on 1.19.2

**Comment by Brown-bricks** [comment]
Can confirm this issue is still present in 1.21.1.

**Comment by lSherozl** [comment]
> Can confirm this issue is still present in 1.21.1.

You mean 1.20.1?

**Comment by Brown-bricks** [comment]
Brief Update: Turning the doTraderSpawning gamerule to false may be a bandaid fix for 1.19.2 for now.
