### ISSUE TITLE
TRANSFORMER/alexsmobs

### ISSUE THREAD

**Issue by stevenGMain** [Alex-the-666/AlexsMobs#2011]
---- Minecraft Crash Report ----

// se me crasheo mi servidor por un problema con alex mobs, me puedes ayudar a eliminar la entidad que ocasiona el error?
//My server crashed due to a problem with Alex Mobs, can you help me eliminate the entity that causes the error?
// Who set us up the TNT?

Time: 3/20/24, 5:18 AM
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.item.ItemEntity.m_32060_()" because "dropped" is null
	at com.github.alexthe666.alexsmobs.entity.EntityCockroach.m_8119_(EntityCockroach.java:321) ~[alexsmobs-1.18.6.jar%2360!/:1.18.6] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:702) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:strawgolem.mixins.json:LoginMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:669) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:strawgolem.forge.mixins.json:GrowthMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:369) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:strawgolem.mixins.json:LoginMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:349) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:strawgolem.mixins.json:LoginMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1121) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:377) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1049) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:874) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:287) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:1583) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Suspected Mod: 
	Alex's Mobs (alexsmobs), Version: 1.18.6
		Issue tracker URL: https://github.com/Alex-the-666/AlexsMobs/issues
		at TRANSFORMER/alexsmobs@1.18.6/com.github.alexthe666.alexsmobs.entity.EntityCockroach.m_8119_(EntityCockroach.java:321)
Stacktrace:
	at com.github.alexthe666.alexsmobs.entity.EntityCockroach.m_8119_(EntityCockroach.java:321) ~[alexsmobs-1.18.6.jar%2360!/:1.18.6] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:702) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:strawgolem.mixins.json:LoginMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:669) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:strawgolem.forge.mixins.json:GrowthMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:369) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:strawgolem.mixins.json:LoginMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:349) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:strawgolem.mixins.json:LoginMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:A}
-- Entity being ticked --
Details:
	Entity Type: alexsmobs:cockroach (com.github.alexthe666.alexsmobs.entity.EntityCockroach)
	Entity ID: 27816
	Entity Name: Cockroach
	Entity's Exact location: -1982.14, 22.00, 1175.45
	Entity's Block location: World: (-1983,22,1175), Section: (at 1,6,7 in -124,1,73; chunk contains blocks -1984,-64,1168 to -1969,319,1183), Region: (-4,2; contains chunks -128,64 to -97,95, blocks -2048,-64,1024 to -1537,319,1535)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.world.level.Level.m_46653_(Level.java:669) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:strawgolem.forge.mixins.json:GrowthMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:369) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:strawgolem.mixins.json:LoginMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:349) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:strawgolem.mixins.json:LoginMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1121) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:377) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1049) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:874) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:287) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:1583) [?:?] {}

-- Affected level --
Details:
	All players: 3 total; [ServerPlayer['SenZ_K'/2491, l='ServerLevel[world]', x=-2030.45, y=69.00, z=1257.36], ServerPlayer['alexx'/1133, l='ServerLevel[world]', x=-2028.97, y=67.00, z=1263.74], ServerPlayer['stiiven119'/357, l='ServerLevel[world]', x=-2025.95, y=69.00, z=1256.38]]
	Chunk stats: 4610
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,75,48), Section: (at 0,11,0 in -2,4,3; chunk contains blocks -32,-64,48 to -17,319,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 356728 game time, 356728 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 153180 (now: false), thunder time: 13814 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1121) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:377) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1049) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:874) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:287) ~[server-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:1583) [?:?] {}

**Comment by stevenGMain** [comment]
logre eliminarla usando un mod que se llama badmobs el cual fuerza la eliminacion de creaturas, pero que creatura es el Cockroach? alguien lo sabe?
