### ISSUE TITLE
Flying Fish Boots Cause Log Spam

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/AlexsMobs#2100]
`MC 1.20.1` | `Alex's Mobs 1.22.8` | `NeoForged 47.1.106`

Random decimal values are printed into the console when flying fish boots are used:
![image](https://github.com/user-attachments/assets/e20c25e1-1d54-4e22-84a0-6142d4660282)

Did some work to StackDump the log, hence me figuring it out:
```java
+----------\
| Triggered by 0.0
| at com.diffplug.common.base.StringPrinter.lambda$stringsToLines$40(StringPrinter.java:256)
| at com.diffplug.common.base.StringPrinter$1.flushOutput(StringPrinter.java:138)
| at com.diffplug.common.base.StringPrinter$1.write(StringPrinter.java:113)
| at java.io.PrintStream.write(PrintStream.java:568)
| at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)
| at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:313)
| at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:111)
| at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:178)
| at java.io.PrintStream.writeln(PrintStream.java:723)
| at java.io.PrintStream.println(PrintStream.java:992)
| at com.github.alexthe666.alexsmobs.entity.util.FlyingFishBootsUtil.handler$dhb000$fishyVaribale(FlyingFishBootsUtil.java:533)
| at com.github.alexthe666.alexsmobs.entity.util.FlyingFishBootsUtil.tickFlyingFishBoots(FlyingFishBootsUtil.java:-1)
| at com.github.alexthe666.alexsmobs.event.ServerEvents.onLivingUpdateEvent(ServerEvents.java:719)
| at com.github.alexthe666.alexsmobs.event.__ServerEvents_onLivingUpdateEvent_LivingTickEvent.invoke(.dynamic:-1)
| at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
| at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
| at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
| at net.minecraftforge.common.ForgeHooks.onLivingTick(ForgeHooks.java:252)
| at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2256)
| at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337)
| at net.minecraft.world.entity.monster.Zombie.m_8119_(Zombie.java:210)
| at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693)
| at net.minecraft.world.level.Level.mixinextras$bridge$accept$176(Level.java:-1)
| at com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92)
| at net.minecraft.world.level.Level.wrapOperation$gkf000$catchTickingEntities$notTheCauseOfTickLag(Level.java:10040)
| at net.minecraft.world.level.Level.m_46653_(Level.java:479)
| at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343)
| at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54)
| at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323)
| at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893)
| at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
| at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89)
| at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
| at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
| at java.lang.Thread.run(Thread.java:833)
+----------/
```

**Comment by ghost** [comment]
Closing as I've since realised this is [caused by Alex's Mobs Interaction](https://github.com/CrimsonCrips/AlexsMobsInteraction/pull/28).
