### ISSUE TITLE
Singleplayer & Server Kick On Hit

### ISSUE THREAD

**Issue by Emberkade** [Alex-the-666/AlexsMobs#2166]
Whenever I attempt to hit a Giant Squid or get hit by a Giant Squid, the game automatically kicks me. This occurs in both singleplayer and on a server. No crash to desktop, no server crash, just this error on the disconnect screen:

Internal Exception: java.lang.IllegalArgumentException: Maybe a mod is trying to add entity in a non-server thread. This is probably not ImmPtl's issue

**Comment by Emberkade** [comment]
[Info: 2024-11-24 19:12:42.8068603: 0Q+xRg==: MinecraftJavaLoggingContext.cpp(65)] Game/Essential Logger (Netty Server IO #1) Error Network Exception Caught
java.lang.IllegalArgumentException: Maybe a mod is trying to add entity in a non-server thread. This is probably not ImmPtl's issue
	at MC-BOOTSTRAP/org.apache.commons.lang3@3.12.0/org.apache.commons.lang3.Validate.isTrue(Validate.java:158)
	at TRANSFORMER/immersive_portals@2.3.7/qouteall.imm_ptl.core.network.PacketRedirection.withForceRedirect(PacketRedirection.java:40)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ChunkMap$TrackedEntity.redirect$dkn000$onSendToOtherNearbyPlayers(ChunkMap.java:1993)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ChunkMap$TrackedEntity.m_140489_(ChunkMap.java:1307)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ChunkMap$TrackedEntity.m_140499_(ChunkMap.java:1313)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ChunkMap.m_140333_(ChunkMap.java:1203)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerChunkCache.m_8394_(ServerChunkCache.java:463)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerLevel.m_7605_(ServerLevel.java:986)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1126)
	at TRANSFORMER/alexsmobs@1.21.1/com.github.alexthe666.alexsmobs.entity.EntityGiantSquid.m_6469_(EntityGiantSquid.java:636)
	at TRANSFORMER/alexsmobs@1.21.1/com.github.alexthe666.alexsmobs.message.MessageHurtMultipart$Handler.handle(MessageHurtMultipart.java:69)
	at TRANSFORMER/forge@43.4.0/net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:115)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at TRANSFORMER/forge@43.4.0/net.minecraftforge.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:115)
	at TRANSFORMER/forge@43.4.0/net.minecraftforge.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:153)
	at TRANSFORMER/forge@43.4.0/net.minecraftforge.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:63)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.4.0/net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:68)
	at TRANSFORMER/forge@43.4.0/net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:77)
	at java.base/java.util.Optional.map(Optional.java:260)
	at TRANSFORMER/forge@43.4.0/net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:77)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_7423_(ServerGamePacketListenerImpl.java:1775)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:35)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:8)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.Connection.m_129517_(Connection.java:163)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.Connection.channelRead0(Connection.java:148)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.Connection.channelRead0(Connection.java:48)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
	at MC-BOOTSTRAP/io.netty.common@4.1.77.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at MC-BOOTSTRAP/io.netty.common@4.1.77.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at MC-BOOTSTRAP/io.netty.common@4.1.77.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at MC-BOOTSTRAP/io.netty.transport@4.1.77.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at MC-BOOTSTRAP/io.netty.common@4.1.77.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at MC-BOOTSTRAP/io.netty.common@4.1.77.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)
