### ISSUE TITLE
Tag issue

### ISSUE THREAD

**Issue by ModernGamingWorld** [Alex-the-666/AlexsMobs#333]
[08.04 00:29:20] [Server] [Worker-Main7/ERROR] [minecraft/TagCollectionReader]: Couldn't read entity_type tag list alexsmobs:komodo_dragon_targets from alexsmobs:tags/entity_types/komodo_dragon_targets.json in data pack alexsmobs-1.9.0.jar
[08.04 00:29:20] [Server] com.google.gson.JsonParseExceptioncom.google.gson.stream.MalformedJsonException: Unterminated array at line 6 column 6 path $.values[1]
[08.04 00:29:20] [Server] 	at net.minecraft.util.JSONUtils.func_188173_a(SourceFile:495) ~[?:?] {re:classloading}
[08.04 00:29:20] [Server] 	at net.minecraft.util.JSONUtils.func_193839_a(SourceFile:532) ~[?:?] {re:classloading}
[08.04 00:29:20] [Server] 	at net.minecraft.tags.TagCollectionReader.func_242223_a(SourceFile:56) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:TagCollectionReaderMixin,pl:mixin:A}
[08.04 00:29:20] [Server] 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) [?:?] {}
[08.04 00:29:20] [Server] 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) [?:?] {}
[08.04 00:29:20] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?] {}
[08.04 00:29:20] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?] {}
[08.04 00:29:20] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?] {re:computing_frames}
[08.04 00:29:20] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?] {re:computing_frames}
[08.04 00:29:20] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?] {}
[08.04 00:29:20] [Server] Caused bycom.google.gson.stream.MalformedJsonException: Unterminated array at line 6 column 6 path $.values[1]
[08.04 00:29:20] [Server] 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[08.04 00:29:20] [Server] 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:476) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[08.04 00:29:20] [Server] 	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[08.04 00:29:20] [Server] 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:730) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[08.04 00:29:20] [Server] 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[08.04 00:29:20] [Server] 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[08.04 00:29:20] [Server] 	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:910) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[08.04 00:29:20] [Server] 	at net.minecraft.util.JSONUtils.func_188173_a(SourceFile:493) ~[?:?] {re:classloading}
[08.04 00:29:20] [Server] 	... more

**Comment by Alex-the-666** [comment]
try re downloading the mod
