### ISSUE TITLE
Crash involving Optifine and lava vision

### ISSUE THREAD

**Issue by Misticblade7** [Alex-the-666/AlexsMobs#45]
While flying over ocean with optifine installed and the lava vision effect active, something caused my game to crash. The crash occurs again upon reloading the world. It does not occur when optifine is disabled. The following error is given in the crash log:

java.lang.NullPointerException: Tesselating liquid in world
	at net.minecraft.client.renderer.FluidBlockRenderer.func_228796_a_(FluidBlockRenderer.java:409) ~[?:?] {re:classloading,xf:OptiFine:default}
	at com.github.alexthe666.alexsmobs.client.render.LavaVisionFluidRenderer.func_228796_a_(LavaVisionFluidRenderer.java:256) ~[alexsmobs:1.0.1] {re:classloading}
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_228794_a_(BlockRendererDispatcher.java:98) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:845) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:721) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$1(ChunkRenderDispatcher.java:180) ~[?:?] {re:classloading,xf:OptiFine:default}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) ~[?:1.8.0_242] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) ~[?:1.8.0_242] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_242] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1646) ~[?:1.8.0_242] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_242] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_242] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_242] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_242] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_242] {}

I've pasted the full crash report here: https://pastebin.com/yvNKyYBp

I understand that issues related to optifine compatibility aren't always considered important, and that the issue likely lies with optifine itself, but I figured I'd post it here so you can be aware of it. Thanks for the mod :)

**Comment by Misticblade7** [comment]
I can confirm it's been fixed in v1.1.0, thanks Alex!
