### ISSUE TITLE
Platypus crash rerport

### ISSUE THREAD

**Issue by Vicus6** [Alex-the-666/AlexsMobs#468]
Hola, desde la ultima actualizacion del mob me se cierra por esto, me podeis ayudar?
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 3/06/21 16:08
Description: Exception generating new chunk

java.lang.NullPointerException: Exception generating new chunk
	at com.github.alexthe666.alexsmobs.entity.EntityPlatypus.canPlatypusSpawn(EntityPlatypus.java:74) ~[alexsmobs:1.10.1] {re:classloading}
	at net.minecraft.entity.EntitySpawnPlacementRegistry.func_223515_a(EntitySpawnPlacementRegistry.java:60) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:351) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.NoiseChunkGenerator.func_230354_a_(NoiseChunkGenerator.java:623) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_222602_b(ChunkStatus.java:89) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:240) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {re:classloading,re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:522) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_291] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_291] {}

**Comment by Kushagra-Srivastava** [comment]
Contact Perry the Platypus

**Comment by Vicus6** [comment]
Ya lo solucione gracias. 
Os mando el mob traducido a español de españa?, No consigo cambiar la directriz para que lea los  es_es.json, el objetivo es cambiar los textos de los progresos, y de algunos items, otros si los cambio
Por que no me deshovan los dragones de comodo?
Los sonidos del kanguro no se escuchan, ni el texto del subtitulo?
[traducciones mob alex.zip](https://github.com/Alex-the-666/AlexsMobs/files/6595878/traducciones.mob.alex.zip).
Gracias por la taencion.
Un Saludo
