### ISSUE TITLE
Frequent crashes after leashing Tasmanian Devil

### ISSUE THREAD

**Issue by xenodus** [Alex-the-666/AlexsMobs#477]
Got the following from crash log. Not sure if it's related but hope it helps.

-- Entity being ticked --
Details:
	Entity Type: alexsmobs:tasmanian_devil (com.github.alexthe666.alexsmobs.entity.EntityTasmanianDevil)
	Entity ID: 181
	Entity Name: Tasmanian Devil
	Entity's Exact location: 217.51, 64.00, -351.50
	Entity's Block location: World: (217,64,-352), Chunk: (at 9,4,0 in 13,-22; contains blocks 208,0,-352 to 223,255,-337), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.16, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterweather.mixins.json:MixinWorld,pl:mixin:APP:brazier-common.mixins.json:WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:oneplayersleeping.mixins.json:MixinOnePlayerSleeping,pl:mixin:APP:betterweather.mixins.json:server.MixinServerWorld,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:accessor.ServerWorldAccessor,pl:mixin:APP:cavesandcliffs.mixins.json:common.world.gen.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}

**Comment by AidanCorgi4556** [comment]
If youre using performant remove it.

**Comment by Alex-the-666** [comment]
^
