### ISSUE TITLE
Crash in modded server 

### ISSUE THREAD

**Issue by cplin1234** [Alex-the-666/AlexsMobs#491]
**Anytime I try to enter the server it crashes leaving this crash report:**

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 6/15/21 2:18 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at com.github.alexthe666.alexsmobs.entity.EntityLobster.canLobsterSpawn(EntityLobster.java:295) ~[alexsmobs:1.10.1] {re:classloading}
	at net.minecraft.entity.EntitySpawnPlacementRegistry.func_223515_a(EntitySpawnPlacementRegistry.java:60) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234975_a_(WorldEntitySpawner.java:218) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawner.java:165) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawner.java:124) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawner.java:110) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(ServerChunkProvider.java:359) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_292] {}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:346) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:321) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.alexsmobs.entity.EntityLobster.canLobsterSpawn(EntityLobster.java:295) ~[alexsmobs:1.10.1] {re:classloading}
	at net.minecraft.entity.EntitySpawnPlacementRegistry.func_223515_a(EntitySpawnPlacementRegistry.java:60) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234975_a_(WorldEntitySpawner.java:218) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawner.java:165) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawner.java:124) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawner.java:110) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(ServerChunkProvider.java:359) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_292] {}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:346) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:321) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['guzz2803'/1151, l='ServerLevel[world buena (si tira) 2]', x=198.50, y=64.00, z=178.50]]
	Chunk stats: ServerChunkCache: 2025
	Level dimension: minecraft:overworld
	Level spawn location: World: (192,64,177), Chunk: (at 0,4,1 in 12,11; contains blocks 192,0,176 to 207,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2827 game time, 2827 day time
	Level name: world buena (si tira) 2
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 77491 (now: false), thunder time: 76801 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 4.15.0-112-generic
	Java Version: 1.8.0_292, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 5366728200 bytes (5118 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 48
	JVM Flags: 20 total; -Xmx6144M -Xms6144M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/custom.jar object_holder_definalize PLUGINSERVICE 
		/custom.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/custom.jar capability_inject_definalize PLUGINSERVICE 
		/custom.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/custom.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.25
	FML Language Providers: 
		javafml@36.1
		minecraft@1
		kotori_scala@2.13.5-build-2
	Mod List: 
		mowziesmobs-1.5.17.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.17              |DONE      |Manifest: NOSIGNATURE
		DungeonsMod-1.16.3-1.3.20 (2).jar                 |Dungeons Mod                  |dungeonsmod                   |1.16.3-1.3.20       |DONE      |Manifest: NOSIGNATURE
		teleportmod_1.16.3-1.1.3.jar                      |Teleport++                    |teleportmod                   |1.1.3               |DONE      |Manifest: NOSIGNATURE
		infernal-expansion-forge-1.3.jar                  |Infernal Expansion            |infernalexp                   |Release 1.3         |DONE      |Manifest: NOSIGNATURE
		spiders-2.0-1.16.4-1.0.4.jar                      |Spiders 2.0                   |spiderstpo                    |1.0.4               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.0.104.jar                          |Just Enough Items             |jei                           |7.7.0.104           |DONE      |Manifest: NOSIGNATURE
		prefab-1.6.5.6.jar                                |Prefab                        |prefab                        |1.6.5.6             |DONE      |Manifest: NOSIGNATURE
		goblintraders-1.5.0-1.16.3.jar                    |Goblin Traders                |goblintraders                 |1.5.0               |DONE      |Manifest: NOSIGNATURE
		extrabows-v1.16.4+b3.jar                          |Extra Bows                    |extrabows                     |v1.16.4 b3          |DONE      |Manifest: NOSIGNATURE
		Inventory-Tweaks-Renewed-Mod-1.16.5.jar           |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        |DONE      |Manifest: NOSIGNATURE
		OresAboveDiamonds-1.16.4-v6.3.3.jar               |Ores Above Diamonds           |oresabovediamonds             |6.3.3               |DONE      |Manifest: NOSIGNATURE
		citadel-1.7.0-1.16.5.jar                          |Citadel                       |citadel                       |1.7.0               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.10.1 (1).jar                          |Alex's Mobs                   |alexsmobs                     |1.10.1              |DONE      |Manifest: NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.91-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.91     |DONE      |Manifest: NOSIGNATURE
		Bookshelf-1.16.5-10.1.11.jar                      |Bookshelf                     |bookshelf                     |10.1.11             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		u_team_core-1.16.5-3.2.1.195.jar                  |U Team Core                   |uteamcore                     |3.2.1.195           |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		Morpheus-1.16.5-4.2.70.jar                        |Morpheus                      |morpheus                      |4.2.70              |DONE      |Manifest: NOSIGNATURE
		additional_lights-1.16.4-2.1.3.jar                |Additional Lights             |additional_lights             |2.1.3               |DONE      |Manifest: NOSIGNATURE
		travellersboots-1.16.5-1.5.0-pre1.jar             |Traveller's Boots             |travellersboots               |1.5.0-pre1          |DONE      |Manifest: NOSIGNATURE
		PickUpNotifier-v1.2-1.16.3.jar                    |Pick Up Notifier              |pickupnotifier                |1.2                 |DONE      |Manifest: d3:cc:6f:1b:30:87:fa:d9:8f:91:15:20:27:63:95:aa:d5:cb:1b:5b:e6:36:cc:57:20:a9:b3:d4:d5:1a:5d:b8
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |Manifest: NOSIGNATURE
		carryon-1.16.5-1.15.5.15.jar                      |Carry On                      |carryon                       |1.15.5.15           |DONE      |Manifest: 8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		forge-1.16.5-36.1.25-universal.jar                |Forge                         |forge                         |36.1.25             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		tl_skin_cape_forge_1.16.5-1.19.jar                |TLSkinCape                    |tlskincape                    |1.19                |DONE      |Manifest: 19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		betterendforge-1.16.4-1.6.0.jar                   |BetterEnd Forge               |betterendforge                |1.16.4-1.6.0        |DONE      |Manifest: NOSIGNATURE
		structure_gel-1.16.5-1.7.7.jar                    |Structure Gel API             |structure_gel                 |1.7.7               |DONE      |Manifest: NOSIGNATURE
		ironchest-1.16.4-11.2.10.jar                      |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |DONE      |Manifest: NOSIGNATURE
		dungeonsarise1.16.5-1.2.72a.jar                   |Dungeons Arise                |dungeons_arise                |1.2.72a             |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.1.25-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		useful_backpacks-1.16.5-1.12.0.89.jar             |Useful Backpacks              |usefulbackpacks               |1.12.0.89           |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		repurposed_structures-1.16.5-2.7.2-forge.jar      |Repurposed Structures         |repurposed_structures         |1.16.5-2.7.2-forge  |DONE      |Manifest: NOSIGNATURE
		morevillagers-FORGE-1.16.5-1.5.1.jar              |More Villagers                |morevillagers                 |1.5.1               |DONE      |Manifest: NOSIGNATURE
		EndRemastered-R36.jar                             |End Remastered 3.6            |endrem                        |1.16.3              |DONE      |Manifest: NOSIGNATURE
		ironfurnaces-1.16.5-2.6.8.jar                     |Iron Furnaces                 |ironfurnaces                  |2.6.8               |DONE      |Manifest: NOSIGNATURE
		CreativeCore_v2.2.0_mc1.16.5.jar                  |CreativeCore                  |creativecore                  |2.0.0               |DONE      |Manifest: NOSIGNATURE
		extcaves-2.4.jar                                  |Extended Caves                |extcaves                      |2.4                 |DONE      |Manifest: NOSIGNATURE
		gaiadimension-1.16.5-1.3.3.jar                    |The Gaia Dimension            |gaiadimension                 |1.3.3               |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.1.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.1      |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_21.10.0.3_Forge_1.16.5.jar         |Xaero's Minimap               |xaerominimap                  |21.10.0.3           |DONE      |Manifest: NOSIGNATURE
		camera-1.16.5-1.0.6.jar                           |Camera Mod                    |camera                        |1.16.5-1.0.6        |DONE      |Manifest: NOSIGNATURE
		AppleTreesRev-Forge-1.16.5-v1.3.jar               |Apple Trees Revived           |appletreesrev                 |1.3                 |DONE      |Manifest: NOSIGNATURE
		malum-1.16.5-0.2.2.4.jar                          |Malum                         |malum                         |1.16.5-0.2.2.4      |DONE      |Manifest: NOSIGNATURE
		[1.16.5]+SecurityCraft+v1.8.21.1.jar              |SecurityCraft                 |securitycraft                 |v1.8.21.1           |DONE      |Manifest: NOSIGNATURE
		elevatorid-1.16.5-1.7.13.jar                      |Elevator Mod                  |elevatorid                    |1.16.5-1.7.13       |DONE      |Manifest: NOSIGNATURE
		tombstone-1.16-6.4.2.jar                          |Corail Tombstone              |tombstone                     |6.4.2               |DONE      |Manifest: NOSIGNATURE
		globalxp-1.16.5-v1.8.jar                          |Global XP                     |globalxp                      |v1.8                |DONE      |Manifest: NOSIGNATURE
		CAC+MOD+[1.16.5]+[2021.2-pre4].jar                |Caves And Cliffs mod [1.16.4] |caves_and_cliffs_mod          |MOD                 |DONE      |Manifest: NOSIGNATURE
		valhelsia_core-16.0.9.jar                         |Valhelsia Core                |valhelsia_core                |16.0.9              |DONE      |Manifest: NOSIGNATURE
		valhelsia_structures-1.16.5-0.1.2.jar             |Valhelsia Structures          |valhelsia_structures          |1.16.5-0.1.2        |DONE      |Manifest: NOSIGNATURE
		DynamicTrees-1.16.5-0.10.0-Beta14.jar             |Dynamic Trees                 |dynamictrees                  |1.16.5-0.10.0-Beta14|DONE      |Manifest: NOSIGNATURE
		TrinityWeapons-1.16.5-1.6.1.jar                   |TrinityWeapons                |trinity                       |1.6.1               |DONE      |Manifest: NOSIGNATURE
		farlanders-1.16.4-1.3.9.jar                       |The Farlanders                |farlanders                    |1.3.9               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 11b65935-7f7e-4138-bbe8-07a115d34aa8
	Player Count: 1 / 5; [ServerPlayerEntity['guzz2803'/1151, l='ServerLevel[world buena (si tira) 2]', x=198.50, y=64.00, z=178.50]]
	Data Packs: vanilla, mod:mowziesmobs (incompatible), mod:dungeonsmod, mod:teleportmod, mod:infernalexp (incompatible), mod:spiderstpo, mod:jei, mod:prefab, mod:goblintraders, mod:extrabows (incompatible), mod:invtweaks (incompatible), mod:oresabovediamonds (incompatible), mod:citadel (incompatible), mod:alexsmobs, mod:sereneseasons, mod:bookshelf, mod:uteamcore, mod:morpheus (incompatible), mod:additional_lights, mod:travellersboots, mod:pickupnotifier (incompatible), mod:waila, mod:carryon, mod:forge, mod:tlskincape (incompatible), mod:betterendforge, mod:structure_gel, mod:ironchest (incompatible), mod:dungeons_arise, mod:usefulbackpacks, mod:repurposed_structures, mod:morevillagers, mod:endrem, mod:ironfurnaces, mod:creativecore, mod:extcaves, mod:gaiadimension, mod:curios, mod:xaerominimap, mod:camera, mod:appletreesrev, mod:malum (incompatible), mod:securitycraft (incompatible), mod:elevatorid, mod:tombstone, mod:globalxp, mod:caves_and_cliffs_mod, mod:valhelsia_core, mod:valhelsia_structures, mod:dynamictrees, mod:trinity (incompatible), mod:farlanders (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Any idea of what is happening exatctly? I thing is alex mobs mod but I am not completely sure.**

**Comment by Alex-the-666** [comment]
fixed
