### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by Vicus6** [Alex-the-666/AlexsMobs#506]
Description: Rendering screen

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 142 column 9 path $.linked_page_buttons[19].text
	at com.google.gson.internal.Streams.parse(Streams.java:60) ~[gson-2.8.0.jar:?] {}
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65) ~[gson-2.8.0.jar:?] {}
	at net.minecraft.util.JSONUtils.func_188173_a(SourceFile:493) ~[?:?] {re:classloading}
	at net.minecraft.util.JSONUtils.func_193839_a(SourceFile:532) ~[?:?] {re:classloading}
	at com.github.alexthe666.citadel.client.gui.BookPage.deserialize(BookPage.java:44) ~[citadel:1.7.1-1.16.5] {re:classloading,pl:runtimedistcleaner:A}
	at com.github.alexthe666.citadel.client.gui.GuiBasicBook.generatePage(GuiBasicBook.java:540) ~[citadel:1.7.1-1.16.5] {re:classloading,pl:runtimedistcleaner:A}
	at com.github.alexthe666.citadel.client.gui.GuiBasicBook.func_230430_a_(GuiBasicBook.java:259) ~[citadel:1.7.1-1.16.5] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:299) ~[forge:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:492) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.1.32.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.32.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291] {}
	at net.minecraft.a.m.main(Unknown Source) [laulib-1.0.jar:?] {}

**Comment by Vicus6** [comment]
Perdon, Ya encontre mi error

**Comment by m87dy** [comment]
@Vicus6 Hola! tengo el mismo problema, como lo solucionaste?

**Comment by Vicus6** [comment]
Ola, en la línea 142 del archivo, hay un error, creo ke era una coma, i algo así, en comentario #534 está ya correcto y corre bn
