### ISSUE TITLE
1.17 Game crash on loading screen

### ISSUE THREAD

**Issue by Adolfester** [Alex-the-666/AlexsMobs#656]
I attach my crash report here

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2/10/21 00:30
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fmllegacy.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:69) ~[forge-1.17.1-37.0.73-universal.jar%2365!:?] {re:classloading}
	at net.minecraftforge.fmlclient.ClientModLoader.completeModLoading(ClientModLoader.java:183) ~[forge-1.17.1-37.0.73-universal.jar%2365!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:555) ~[client-1.17.1-20210706.113038-srg.jar%2361!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:361) ~[client-1.17.1-20210706.113038-srg.jar%2361!:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:549) ~[client-1.17.1-20210706.113038-srg.jar%2361!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.17.1-20210706.113038-srg.jar%2361!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:874) ~[client-1.17.1-20210706.113038-srg.jar%2361!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1039) ~[client-1.17.1-20210706.113038-srg.jar%2361!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:659) ~[client-1.17.1-20210706.113038-srg.jar%2361!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[client-1.17.1-20210706.113038-srg.jar%2361!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.0.73.jar%2322!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.github.alexthe666.citadel.Citadel.<clinit>(Citadel.java:58) ~[citadel-1.9.3-1.17.1-deobf.jar%2360!:?] {re:classloading}
-- MOD citadel --
Details:
	Mod File: citadel-1.9.3-1.17.1-deobf.jar
	Failure message: Citadel (citadel) has failed to load correctly
		java.lang.NoSuchMethodError: 'net.minecraft.world.item.Item$Properties net.minecraft.world.item.Item$Properties.stacksTo(int)'
	Mod Version: 1.9.3
	Mod Issue URL: https://github.com/Alex-the-666/Citadel/issues
	Exception message: java.lang.NoSuchMethodError: 'net.minecraft.world.item.Item$Properties net.minecraft.world.item.Item$Properties.stacksTo(int)'
Stacktrace:
	at com.github.alexthe666.citadel.Citadel.<clinit>(Citadel.java:58) ~[citadel-1.9.3-1.17.1-deobf.jar%2360!:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.17.1-37.0.73.jar%2363!:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.17.1-37.0.73.jar%2362!:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

-- MOD alexsmobs --
Details:
	Mod File: alexsmobs-1.13.0.jar
	Failure message: Alex's Mobs (alexsmobs) has failed to load correctly
		java.lang.AbstractMethodError: Receiver class com.github.alexthe666.alexsmobs.item.AMArmorMaterial does not define or inherit an implementation of the resolved method 'abstract int m_7365_(net.minecraft.world.entity.EquipmentSlot)' of interface net.minecraft.world.item.ArmorMaterial.
	Mod Version: 1.13.0
	Mod Issue URL: https://github.com/Alex-the-666/AlexsMobs/issues
	Exception message: java.lang.AbstractMethodError: Receiver class com.github.alexthe666.alexsmobs.item.AMArmorMaterial does not define or inherit an implementation of the resolved method 'abstract int m_7365_(net.minecraft.world.entity.EquipmentSlot)' of interface net.minecraft.world.item.ArmorMaterial.
Stacktrace:
	at net.minecraft.world.item.ArmorItem.<init>(ArmorItem.java:66) ~[client-1.17.1-20210706.113038-srg.jar%2361!:?] {re:classloading}
	at com.github.alexthe666.alexsmobs.item.ItemModArmor.<init>(ItemModArmor.java:36) ~[alexsmobs-1.13.0.jar%2359!:1.13.0] {re:classloading}
	at com.github.alexthe666.alexsmobs.item.AMItemRegistry.<clinit>(AMItemRegistry.java:59) ~[alexsmobs-1.13.0.jar%2359!:1.13.0] {re:classloading}
	at java.lang.Class.forName0(Native Method) ~[?:?] {}
	at java.lang.Class.forName(Class.java:466) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[javafmllanguage-1.17.1-37.0.73.jar%2363!:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[javafmllanguage-1.17.1-37.0.73.jar%2363!:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[javafmllanguage-1.17.1-37.0.73.jar%2363!:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.17.1-37.0.73.jar%2362!:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3048176376 bytes (2906 MiB) / 3422552064 bytes (3264 MiB) up to 3422552064 bytes (3264 MiB)
	CPUs: 2
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Celeron(R) N4000 CPU @ 1.10GHz
	Identifier: Intel64 Family 6 Model 122 Stepping 1
	Microarchitecture: Goldmont Plus
	Frequency (GHz): 1,09
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: Intel(R) UHD Graphics 600
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024,00
	Graphics card #0 deviceId: 0x3185
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8681
	Memory slot #0 capacity (MB): 2048,00
	Memory slot #0 clockSpeed (GHz): 2,40
	Memory slot #0 type: LPDDR4
	Memory slot #1 capacity (MB): 2048,00
	Memory slot #1 clockSpeed (GHz): 2,40
	Memory slot #1 type: LPDDR4
	Virtual memory max (MB): 13017,61
	Virtual memory used (MB): 8507,44
	Swap memory total (MB): 9097,82
	Swap memory used (MB): 1248,16
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmn128M -Xmx3236M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_inject_definalize PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.17.1-20210706.113038-srg.jar             |Minecraft                     |minecraft                     |1.17.1              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.17.1-37.0.73-universal.jar                |Forge                         |forge                         |37.0.73             |COMMON_SET|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		citadel-1.9.3-1.17.1-deobf.jar                    |Citadel                       |citadel                       |1.9.3               |ERROR     |Manifest: NOSIGNATURE
		alexsmobs-1.13.0.jar                              |Alex's Mobs                   |alexsmobs                     |1.13.0              |ERROR     |Manifest: NOSIGNATURE
	Crash Report UUID: 750dd7bd-e70e-4384-9322-56cef03e84f9
	FML: 37.0
	Forge: net.minecraftforge:37.0.73

**Comment by Alex-the-666** [comment]
update forge
