### ISSUE TITLE
Ticking entity crash

### ISSUE THREAD

**Issue by PlummetStudios** [Alex-the-666/AlexsMobs#756]
Not sure exactly what caused it but I'm in the new 1.18 update and crow caused me to get a ticking entity crash.
[crash-2021-12-04_09.51.39-server.txt](https://github.com/Alex-the-666/AlexsMobs/files/7654116/crash-2021-12-04_09.51.39-server.txt)

**Comment by ClownyTheClown** [comment]
Same issue for me
[crash-2021-12-04_14.56.34-server.txt](https://github.com/Alex-the-666/AlexsMobs/files/7654595/crash-2021-12-04_14.56.34-server.txt)

**Comment by Zerkweet** [comment]
[crash-2021-12-04_20.15.26-server.txt](https://github.com/Alex-the-666/AlexsMobs/files/7655205/crash-2021-12-04_20.15.26-server.txt)
 same for me

**Comment by esamudio** [comment]
whenever we go anywhere near a certain type of village, we get the same error reported above

```
05.12 01:56:45 [Server] Server thread/ERROR Encountered an unexpected exception
05.12 01:56:45 [Server] INFO net.minecraft.ReportedException: Ticking entity
05.12 01:56:45 [Server] INFO at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[server-1.18-20211130.085255-srg.jar%2372!:?]
05.12 01:56:45 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18-20211130.085255-srg.jar%2372!:?]
05.12 01:56:45 [Server] INFO at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18-20211130.085255-srg.jar%2372!:?]
05.12 01:56:45 [Server] INFO at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18-20211130.085255-srg.jar%2372!:?]
05.12 01:56:45 [Server] INFO at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18-20211130.085255-srg.jar%2372!:?]
05.12 01:56:45 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
05.12 01:56:45 [Server] INFO Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.core.BlockPos.m_7494_()" because "this.f_25602_" is null
05.12 01:56:45 [Server] INFO at net.minecraft.world.entity.ai.goal.MoveToBlockGoal.m_6669_(MoveToBlockGoal.java:75) ~[server-1.18-20211130.085255-srg.jar%2372!:?]
05.12 01:56:45 [Server] INFO at com.github.alexthe666.alexsmobs.entity.ai.CrowAICircleCrops.m_8037_(CrowAICircleCrops.java:59) ~[alexsmobs-1.14.2.jar%2337!:1.14.2]
05.12 01:56:45 [Server] INFO at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8037_(WrappedGoal.java:65) ~[server-1.18-20211130.085255-srg.jar%2372!:?]
05.12 01:56:45 [Server] INFO at net.minecraft.world.entity.ai.goal.GoalSelector.m_186081_(GoalSelector.java:119) ~[server-1.18-20211130.085255-srg.jar%2372!:?]
05.12 01:56:45 [Server] INFO at net.minecraft.world.entity.Mob.m_6140_(Mob.java:691) ~[server-1.18-20211130.085255-srg.jar%2372!:?]
05.12 01:56:45 [Server] INFO at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2496) ~[server-1.18-20211130.085255-srg.jar%2372!:?]
05.12 01:56:45 [Server] INFO at net.minecraft.world.entity.Mob.m_8107_(Mob.java:495) ~[server-1.18-20211130.085255-srg.jar%2372!:?]
05.12 01:56:45 [Server] INFO at net.minecraft.world.entity.AgeableMob.m_8107_(AgeableMob.java:127) ~[server-1.18-20211130.085255-srg.jar%2372!:?]
05.12 01:56:45 [Server] INFO at net.minecraft.world.entity.animal.Animal.m_8107_(Animal.java:54) ~[server-1.18-20211130.085255-srg.jar%2372!:?]
05.12 01:56:45 [Server] INFO at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2243) ~[server-1.18-20211130.085255-srg.jar%2372!:?]
05.12 01:56:45 [Server] INFO at net.minecraft.world.entity.Mob.m_8119_(Mob.java:307) ~[server-1.18-20211130.085255-srg.jar%2372!:?]
05.12 01:56:45 [Server] INFO at com.github.alexthe666.alexsmobs.entity.EntityCrow.m_8119_(EntityCrow.java:300) ~[alexsmobs-1.14.2.jar%2337!:1.14.2]
05.12 01:56:45 [Server] INFO at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:646) ~[server-1.18-20211130.085255-srg.jar%2372!:?]
05.12 01:56:45 [Server] INFO at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[server-1.18-20211130.085255-srg.jar%2372!:?]
05.12 01:56:45 [Server] INFO at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:313) ~[server-1.18-20211130.085255-srg.jar%2372!:?]
05.12 01:56:45 [Server] INFO at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.18-20211130.085255-srg.jar%2372!:?]
05.12 01:56:45 [Server] INFO at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:293) ~[server-1.18-20211130.085255-srg.jar%2372!:?]
05.12 01:56:45 [Server] INFO at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[server-1.18-20211130.085255-srg.jar%2372!:?]
05.12 01:56:45 [Server] INFO ... 5 more
```

**Comment by emanuele246gi** [comment]
Me too
