### ISSUE TITLE
Null pointer crash

### ISSUE THREAD

**Issue by eractnod** [Alex-the-666/AlexsMobs#775]
Was walking towards a village when game crashed.  Have a Null pointer error.  Tried logging back in and crashed again for same error.  Had to remove mod to get back into the world. 
MC 1.18.0
Forge 38.0.15
Alex 1.14.3

java.lang.NullPointerException: Cannot invoke "net.minecraft.core.BlockPos.m_7494_()" because "this.f_25602_" is null
	at net.minecraft.world.entity.ai.goal.MoveToBlockGoal.m_6669_(MoveToBlockGoal.java:75) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading}
	at net.minecraft.world.entity.ai.goal.MoveToBlockGoal.m_8037_(MoveToBlockGoal.java:85) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading}
	at com.github.alexthe666.alexsmobs.entity.ai.AnimalAILootChests.m_8037_(AnimalAILootChests.java:113) ~[alexsmobs-1.14.3.jar%2352!:1.14.3] {re:classloading}
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8037_(WrappedGoal.java:65) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading}
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_186081_(GoalSelector.java:119) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:691) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2496) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:495) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.AgeableMob.m_8107_(AgeableMob.java:127) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading}
	at net.minecraft.world.entity.animal.Animal.m_8107_(Animal.java:54) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2243) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:307) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading,pl:accesstransformer:B}
	at com.github.alexthe666.alexsmobs.entity.EntityRaccoon.m_8119_(EntityRaccoon.java:331) ~[alexsmobs-1.14.3.jar%2352!:1.14.3] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:646) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:313) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:293) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:86) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.entity.ai.goal.MoveToBlockGoal.m_6669_(MoveToBlockGoal.java:75) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading}
	at net.minecraft.world.entity.ai.goal.MoveToBlockGoal.m_8037_(MoveToBlockGoal.java:85) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading}
	at com.github.alexthe666.alexsmobs.entity.ai.AnimalAILootChests.m_8037_(AnimalAILootChests.java:113) ~[alexsmobs-1.14.3.jar%2352!:1.14.3] {re:classloading}
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8037_(WrappedGoal.java:65) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading}
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_186081_(GoalSelector.java:119) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:691) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2496) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:495) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.AgeableMob.m_8107_(AgeableMob.java:127) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading}
	at net.minecraft.world.entity.animal.Animal.m_8107_(Animal.java:54) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2243) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:307) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading,pl:accesstransformer:B}
	at com.github.alexthe666.alexsmobs.entity.EntityRaccoon.m_8119_(EntityRaccoon.java:331) ~[alexsmobs-1.14.3.jar%2352!:1.14.3] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:646) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:313) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:293) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading,pl:accesstransformer:B}
-- Entity being ticked --
Details:
	Entity Type: alexsmobs:raccoon (com.github.alexthe666.alexsmobs.entity.EntityRaccoon)
	Entity ID: 292
	Entity Name: Raccoon
	Entity's Exact location: -143.63, 65.88, 886.14
	Entity's Block location: World: (-144,65,886), Section: (at 0,1,6 in -9,4,55; chunk contains blocks -144,-64,880 to -129,319,895), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,-64,512 to -1,319,1023)
	Entity's Momentum: -0.04, -0.08, 0.02
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:313) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:293) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:86) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['Eractnod'/268, l='ServerLevel[World 1]', x=-124.00, y=65.00, z=858.59]]
	Chunk stats: 4985
	Level dimension: minecraft:overworld
	Level spawn location: World: (288,74,-16), Section: (at 0,10,0 in 18,4,-1; chunk contains blocks 288,-64,-16 to 303,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 22979 game time, 22979 day time
	Level name: World 1
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 93684 (now: false), thunder time: 120188 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:86) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18-20211130.085255-srg.jar%23110!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

**Comment by eractnod** [comment]
I reloaded the mod and set raccoon steals from chest to false to see if I can keep the mod for now.

**Comment by vvindication** [comment]
also having this same problem on a LAN server with the same versions of Minecraft, Forge, and the mod.
here's my crash log as well.

java.lang.NullPointerException: Cannot invoke "net.minecraft.core.BlockPos.m_7494_()" because "this.f_25602_" is null
	at net.minecraft.world.entity.ai.goal.MoveToBlockGoal.m_6669_(MoveToBlockGoal.java:75) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:classloading}
	at net.minecraft.world.entity.ai.goal.MoveToBlockGoal.m_8037_(MoveToBlockGoal.java:85) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:classloading}
	at com.github.alexthe666.alexsmobs.entity.ai.AnimalAILootChests.m_8037_(AnimalAILootChests.java:113) ~[alexsmobs-1.14.3.jar%2352!:1.14.3] {re:classloading}
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8037_(WrappedGoal.java:65) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:classloading}
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_186081_(GoalSelector.java:119) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:classloading}
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:691) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2496) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,re:classloading,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:495) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.AgeableMob.m_8107_(AgeableMob.java:127) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.animal.Animal.m_8107_(Animal.java:54) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2243) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,re:classloading,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:307) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at com.github.alexthe666.alexsmobs.entity.EntityRaccoon.m_8119_(EntityRaccoon.java:331) ~[alexsmobs-1.14.3.jar%2352!:1.14.3] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:646) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:313) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:293) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:86) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.entity.ai.goal.MoveToBlockGoal.m_6669_(MoveToBlockGoal.java:75) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:classloading}
	at net.minecraft.world.entity.ai.goal.MoveToBlockGoal.m_8037_(MoveToBlockGoal.java:85) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:classloading}
	at com.github.alexthe666.alexsmobs.entity.ai.AnimalAILootChests.m_8037_(AnimalAILootChests.java:113) ~[alexsmobs-1.14.3.jar%2352!:1.14.3] {re:classloading}
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8037_(WrappedGoal.java:65) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:classloading}
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_186081_(GoalSelector.java:119) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:classloading}
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:691) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2496) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,re:classloading,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:495) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.AgeableMob.m_8107_(AgeableMob.java:127) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.animal.Animal.m_8107_(Animal.java:54) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2243) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,re:classloading,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:307) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at com.github.alexthe666.alexsmobs.entity.EntityRaccoon.m_8119_(EntityRaccoon.java:331) ~[alexsmobs-1.14.3.jar%2352!:1.14.3] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:646) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:313) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:293) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
-- Entity being ticked --
Details:
	Entity Type: alexsmobs:raccoon (com.github.alexthe666.alexsmobs.entity.EntityRaccoon)
	Entity ID: 24226
	Entity Name: Raccoon
	Entity's Exact location: 64.76, 97.25, 879.69
	Entity's Block location: World: (64,97,879), Section: (at 0,1,15 in 4,6,54; chunk contains blocks 64,-64,864 to 79,319,879), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,-64,512 to 511,319,1023)
	Entity's Momentum: -0.04, 0.00, 0.01
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:313) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:293) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:86) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


-- Affected level --
Details:
	All players: 2 total; [ServerPlayer['vvindication'/13797, l='ServerLevel[November's End]', x=-85.35, y=64.00, z=-108.70], ServerPlayer['goober9000'/14839, l='ServerLevel[November's End]', x=-4.50, y=68.00, z=860.50]]
	Chunk stats: 6637
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,71,0), Section: (at 0,7,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 5118510 game time, 5552862 day time
	Level name: November's End
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 62933 (now: false), thunder time: 132537 (now: false)
	Known server brands: vanilla, forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:86) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18-20211130.085255-srg.jar%2361!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
