### ISSUE TITLE
Having a server tick loop error with the rocky roller mob

### ISSUE THREAD

**Issue by TheMcMeme** [Alex-the-666/AlexsMobs#799]
Hello, currently having a problem with this mob, which ends up crashing my server... I would just disable the mob, but they are so adorable I love them. Not sure if there is a problem with another mod or not, but here is the crash log:

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 12/21/21, 4:41 AM
Description: Exception in server tick loop

java.lang.NoSuchFieldError: clientRoll
	at com.github.alexthe666.alexsmobs.entity.EntityRockyRoller.<init>(EntityRockyRoller.java:56) ~[alexsmobs-1.15.0.jar%2337!:1.15.0] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:458) ~[server-1.18.1-20211210.034407-srg.jar%2363!:?] {re:classloading,re:mixin}
	at net.minecraft.world.entity.EntityType.m_20655_(EntityType.java:339) ~[server-1.18.1-20211210.034407-srg.jar%2363!:?] {re:classloading,re:mixin}
	at net.minecraft.world.entity.EntityType.m_20600_(EntityType.java:328) ~[server-1.18.1-20211210.034407-srg.jar%2363!:?] {re:classloading,re:mixin}
	at net.minecraft.world.entity.EntityType.m_20592_(EntityType.java:323) ~[server-1.18.1-20211210.034407-srg.jar%2363!:?] {re:classloading,re:mixin}
	at net.minecraft.world.item.SpawnEggItem.m_6225_(SpawnEggItem.java:83) ~[server-1.18.1-20211210.034407-srg.jar%2363!:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:574) ~[forge-1.18.1-39.0.7-universal.jar%2367!:?] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:212) ~[server-1.18.1-20211210.034407-srg.jar%2363!:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack}
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:347) ~[server-1.18.1-20211210.034407-srg.jar%2363!:?] {re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:975) ~[server-1.18.1-20211210.034407-srg.jar%2363!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30) ~[server-1.18.1-20211210.034407-srg.jar%2363!:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.18.1-20211210.034407-srg.jar%2363!:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[server-1.18.1-20211210.034407-srg.jar%2363!:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%2363!:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%2363!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%2363!:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.18.1-20211210.034407-srg.jar%2363!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.18.1-20211210.034407-srg.jar%2363!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%2363!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[server-1.18.1-20211210.034407-srg.jar%2363!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%2363!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.18.1-20211210.034407-srg.jar%2363!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[server-1.18.1-20211210.034407-srg.jar%2363!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[server-1.18.1-20211210.034407-srg.jar%2363!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2363!:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (amd64) version 4.18.0-305.19.1.el8_4.x86_64
	Java Version: 17.0.1, Red Hat, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Red Hat, Inc.
	Memory: 1379466752 bytes (1315 MiB) / 4160749568 bytes (3968 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 2
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 84898.98
	Virtual memory used (MB): 107073.63
	Swap memory total (MB): 20478.99
	Swap memory used (MB): 2204.11
	JVM Flags: 2 total; -Xmx4096M -Xms2662M
	Server Running: true
	Player Count: 1 / 100; [ServerPlayer['TheMcMeme'/88, l='ServerLevel[pkjllovescock]', x=59.62, y=64.00, z=88.68]]
	Data Packs: vanilla, mod:domum_ornamentum (incompatible), mod:blockui, mod:xaerominimap, mod:timber (incompatible), mod:croptopia, mod:clumps (incompatible), mod:xaeroworldmap, mod:fastbench (incompatible), mod:placebo (incompatible), mod:citadel (incompatible), mod:alexsmobs (incompatible), mod:elevatorid, mod:jobsplus, mod:structurize, mod:multipiston (incompatible), mod:minecolonies (incompatible), mod:fastfurnace (incompatible), mod:cfm (incompatible), mod:ottercraft, mod:fpsreducer, mod:beyond_earth (incompatible), mod:forge, mod:appleskin (incompatible), mod:geckolib3 (incompatible), mod:chococraft, mod:drinkbeer (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		server-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: NOSIGNATURE
		domum_ornamentum-1.18-1.0.31-ALPHA-universal.jar  |Domum Ornamentum              |domum_ornamentum              |1.18-1.0.31-ALPHA   |DONE      |Manifest: NOSIGNATURE
		blockui-1.18-0.0.34-ALPHA.jar                     |UI Library Mod                |blockui                       |1.18-0.0.34-ALPHA   |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_21.22.5_Forge_1.18.jar             |Xaero's Minimap               |xaerominimap                  |21.22.5             |DONE      |Manifest: NOSIGNATURE
		timber-1.18.1-3.0.0.jar                           |Timber Mod                    |timber                        |3.0.0               |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.18-FORGE-1.7.4.jar                    |Croptopia                     |croptopia                     |1.7.4               |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.18.1-8.0.3.jar                     |Clumps                        |clumps                        |8.0.3               |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.18.7_Forge_1.18.jar              |Xaero's World Map             |xaeroworldmap                 |1.18.7              |DONE      |Manifest: NOSIGNATURE
		FastWorkbench-1.18.1-6.0.0.jar                    |Fast Workbench                |fastbench                     |6.0.0               |DONE      |Manifest: NOSIGNATURE
		Placebo-1.18.1-6.0.2.jar                          |Placebo                       |placebo                       |6.0.2               |DONE      |Manifest: NOSIGNATURE
		citadel-1.10.5-1.18.jar                           |Citadel                       |citadel                       |1.10.5              |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.15.0.jar                              |Alex's Mobs                   |alexsmobs                     |1.15.0              |DONE      |Manifest: NOSIGNATURE
		elevatorid-1.18-1.8.3.jar                         |Elevator Mod                  |elevatorid                    |1.18-1.8.3          |DONE      |Manifest: NOSIGNATURE
		jobsplus-0.1.3.jar                                |Jobs+                         |jobsplus                      |0.1.3               |DONE      |Manifest: NOSIGNATURE
		structurize-1.18.1-1.0.319-BETA.jar               |Structurize                   |structurize                   |1.18.1-1.0.319-BETA |DONE      |Manifest: NOSIGNATURE
		multi-piston-1.18-1.2.2-ALPHA.jar                 |Multi-Piston                  |multipiston                   |1.18-1.2.2-ALPHA    |DONE      |Manifest: NOSIGNATURE
		minecolonies-1.18.1-1.0.278-RELEASE.jar           |MineColonies                  |minecolonies                  |1.18.1-1.0.278-RELEA|DONE      |Manifest: NOSIGNATURE
		FastFurnace-1.18.1-6.0.1.jar                      |FastFurnace                   |fastfurnace                   |6.0.1               |DONE      |Manifest: NOSIGNATURE
		furniture-7.0.0-pre27-1.18.1.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre27         |DONE      |Manifest: NOSIGNATURE
		Ottercraft-forge-1.18-1.1.2.jar                   |Ottercraft                    |ottercraft                    |1.1.0               |DONE      |Manifest: NOSIGNATURE
		FpsReducer-forge-1.25-mc1.18.jar                  |FPS Reducer                   |fpsreducer                    |1.25-mc1.18         |DONE      |Manifest: NOSIGNATURE
		Beyond-Earth-1.18.1-5.7.jar                       |Beyond Earth                  |beyond_earth                  |5.7                 |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.7-universal.jar                 |Forge                         |forge                         |39.0.7              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		appleskin-forge-mc1.18-2.2.0.jar                  |AppleSkin                     |appleskin                     |2.2.0               |DONE      |Manifest: NOSIGNATURE
		geckolib-1.18-forge-3.0.3.jar                     |GeckoLib                      |geckolib3                     |3.0.3               |DONE      |Manifest: NOSIGNATURE
		chococraft-1.18.1-0.2.1.jar                       |Chococraft 4                  |chococraft                    |0.2.1               |DONE      |Manifest: NOSIGNATURE
		drinkbeer-v2.3.5 for 1.18.1.jar                   |Drink Beer                    |drinkbeer                     |2.3.5               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: bbad10ac-523d-4588-b832-c029e96e9fec
	FML: 39.0
	Forge: net.minecraftforge:39.0.7

**Comment by Gbergz** [comment]
Same problem here.

### Versions:
Minecraft: 1.18.1
Forge: 39.0.5
Alex's Mobs: 1.15.0 | https://www.curseforge.com/minecraft/mc-mods/alexs-mobs/files/3574880
Citadel: 1.10.5 | https://www.curseforge.com/minecraft/mc-mods/citadel/files/3574790

Crash-Report: https://gist.github.com/Gbergz/be4cd5854a5792f468dbecaadeeb6178
