### ISSUE TITLE
Crashing when trying to open a book

### ISSUE THREAD

**Issue by leonartt** [Alex-the-666/AlexsMobs#802]
Hi,
My setup:
Server: spigot_1.18.jar (Java 17)
Client: Forge 1.18
alexsmobs-1.15.0.jar
citadel-1.10.5-1.18.jar
Whenever trying to open Alex's book the game client is crashing.

**Comment by leonartt** [comment]
[13:21:50] [Render thread/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Rendering screen
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:898) ~[client-1.18-20211130.085255-srg.jar%2364!:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1040) ~[client-1.18-20211130.085255-srg.jar%2364!:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18-20211130.085255-srg.jar%2364!:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18-20211130.085255-srg.jar%2364!:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18-38.0.17.jar%2323!:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.tags.Tag.m_6497_()" because "this.f_43959_" is null
	at net.minecraft.world.item.crafting.Ingredient$TagValue.m_6223_(Ingredient.java:257) ~[client-1.18-20211130.085255-srg.jar%2364!:?]
	at net.minecraft.world.item.crafting.Ingredient.lambda$new$4(Ingredient.java:50) ~[client-1.18-20211130.085255-srg.jar%2364!:?]
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
	at net.minecraft.world.item.crafting.Ingredient.<init>(Ingredient.java:50) ~[client-1.18-20211130.085255-srg.jar%2364!:?]
	at net.minecraft.world.item.crafting.Ingredient.m_43938_(Ingredient.java:151) ~[client-1.18-20211130.085255-srg.jar%2364!:?]
	at com.github.alexthe666.alexsmobs.entity.EntityCapuchinMonkey.<init>(EntityCapuchinMonkey.java:84) ~[alexsmobs-1.15.0.jar%2359!:1.15.0]
	at net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:458) ~[client-1.18-20211130.085255-srg.jar%2364!:?]
	at com.github.alexthe666.citadel.client.gui.EntityLinkButton.m_6303_(EntityLinkButton.java:47) ~[citadel-1.10.5-1.18.jar%2360!:1.10.5-1.18]
	at net.minecraft.client.gui.components.AbstractWidget.m_6305_(AbstractWidget.java:64) ~[client-1.18-20211130.085255-srg.jar%2364!:?]
	at net.minecraft.client.gui.screens.Screen.m_6305_(Screen.java:103) ~[client-1.18-20211130.085255-srg.jar%2364!:?]
	at com.github.alexthe666.citadel.client.gui.GuiBasicBook.m_6305_(GuiBasicBook.java:288) ~[citadel-1.10.5-1.18.jar%2360!:1.10.5-1.18]
	at com.github.alexthe666.alexsmobs.client.gui.GUIAnimalDictionary.m_6305_(GUIAnimalDictionary.java:43) ~[alexsmobs-1.15.0.jar%2359!:1.15.0]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:371) ~[forge-1.18-38.0.17-universal.jar%2368!:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:364) ~[forge-1.18-38.0.17-universal.jar%2368!:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.18-20211130.085255-srg.jar%2364!:?]
	... 16 more
