### ISSUE TITLE
1.18.1 Server Crashes when being around Rocky Roller

### ISSUE THREAD

**Issue by AmyUndead** [Alex-the-666/AlexsMobs#806]
I dont really have much to add, everything you need to know is in the title lol

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 12/21/21, 6:52 PM
Description: Exception ticking world

java.lang.NoSuchFieldError: clientRoll
	at com.github.alexthe666.alexsmobs.entity.EntityRockyRoller.<init>(EntityRockyRoller.java:56) ~[alexsmobs-1.15.0.jar%2337!:1.15.0] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:458) ~[server-1.18.1-20211210.034407-srg.jar%2349!:?] {re:classloading,re:mixin}
	at net.minecraft.world.level.NaturalSpawner.m_46988_(NaturalSpawner.java:239) ~[server-1.18.1-20211210.034407-srg.jar%2349!:?] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:175) ~[server-1.18.1-20211210.034407-srg.jar%2349!:?] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:124) ~[server-1.18.1-20211210.034407-srg.jar%2349!:?] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:114) ~[server-1.18.1-20211210.034407-srg.jar%2349!:?] {re:classloading}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:355) ~[server-1.18.1-20211210.034407-srg.jar%2349!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[server-1.18.1-20211210.034407-srg.jar%2349!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[server-1.18.1-20211210.034407-srg.jar%2349!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[server-1.18.1-20211210.034407-srg.jar%2349!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%2349!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%2349!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%2349!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2349!:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

**Comment by Spectre-AFK** [comment]
I get the same issue when running my server.

**Comment by cobaltw** [comment]
Same crash here, it's happened at least four times

**Comment by Andiq** [comment]
Same

**Comment by Andiq** [comment]
This can be quickly fixed by removing the dripstone cave spawn biome so it doesnt spawn.

**Comment by AlexModGuy** [comment]
should be fixed
