### ISSUE TITLE
[1.16.5]ServerCrash caused by Grizzly Bear pathfinding

### ISSUE THREAD

**Issue by EverettSummer** [Alex-the-666/AlexsMobs#848]
```
---- Minecraft Crash Report ----
// Don't do that.

Time: 1/11/22 3:55 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
        at net.minecraft.pathfinding.PathNavigator.func_75484_a(PathNavigator.java:163) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:pathing.PathNavigatorMixin,pl:mixin:A}
        at net.minecraft.pathfinding.PathNavigator.func_75492_a(PathNavigator.java:142) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:pathing.PathNavigatorMixin,pl:mixin:A}
        at net.minecraft.entity.CreatureEntity.func_110159_bB(SourceFile:572) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:entity.CreatureEntityMixin,pl:mixin:A}
        at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:302) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at com.github.alexthe666.alexsmobs.entity.EntityGrizzlyBear.func_70071_h_(EntityGrizzlyBear.java:260) ~[alexsmobs:1.11.1] {re:classloading}
        at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at net.minecraft.pathfinding.PathNavigator.func_75484_a(PathNavigator.java:163) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:pathing.PathNavigatorMixin,pl:mixin:A}
        at net.minecraft.pathfinding.PathNavigator.func_75492_a(PathNavigator.java:142) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:pathing.PathNavigatorMixin,pl:mixin:A}
        at net.minecraft.entity.CreatureEntity.func_110159_bB(SourceFile:572) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:entity.CreatureEntityMixin,pl:mixin:A}
        at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:302) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at com.github.alexthe666.alexsmobs.entity.EntityGrizzlyBear.func_70071_h_(EntityGrizzlyBear.java:260) ~[alexsmobs:1.11.1] {re:classloading}
        at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Entity being ticked --
Details:
        Entity Type: alexsmobs:grizzly_bear (com.github.alexthe666.alexsmobs.entity.EntityGrizzlyBear)
        Entity ID: 90
        Entity Name: Grizzly Bear
        Entity's Exact location: 12775.90, 69.00, 524.01
        Entity's Block location: World: (12775,69,524), Chunk: (at 7,4,12 in 798,32; contains blocks 12768,0,512 to 12783,255,527), Region: (24,1; contains chunks 768,32 to 799,63, blocks 12288,0,512 to 12799,255,1023)
        Entity's Momentum: 0.00, -0.08, 0.00
        Entity's Passengers: []
        Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
        at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}


-- Affected level --
Details:
        All players: 1 total; [ServerPlayerEntity['insc_polaris'/75, l='ServerLevel[New World3]', x=12777.25, y=74.50, z=585.21]]
        Chunk stats: ServerChunkCache: 5274
        Level dimension: minecraft:overworld
        Level spawn location: World: (7424,67,456), Chunk: (at 0,4,8 in 464,28; contains blocks 7424,0,448 to 7439,255,463), Region: (14,0; contains chunks 448,0 to 479,31, blocks 7168,0,0 to 7679,255,511)
        Level time: 318584621 game time, 339542349 day time
        Level name: New World3
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
        Level weather: Rain time: 67459 (now: false), thunder time: 140943 (now: false)
        Known server brands: forge
        Level was modded: true
        Level storage version: 0x04ABD - Anvil
Stacktrace:
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282] {}


-- System Details --
Details:
        Minecraft Version: 1.16.5
        Minecraft Version ID: 1.16.5
        Operating System: Linux (amd64) version 5.4.0-89-generic
        Java Version: 1.8.0_282, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 1896312672 bytes (1808 MB) / 3758096384 bytes (3584 MB) up to 11811160064 bytes (11264 MB)
        CPUs: 8
        JVM Flags: 8 total; -Xms4G -Xmx12G -XX:NewSize=2G -XX:MaxNewSize=4G -XX:SurvivorRatio=2 -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+AggressiveOpts
        ModLauncher: 8.0.9+86+master.3cf110c
        ModLauncher launch target: fmlserver
        ModLauncher naming: srg
        ModLauncher services: 
                /mixin-0.8.4.jar mixin PLUGINSERVICE 
                /eventbus-4.0.0.jar eventbus PLUGINSERVICE 
                /forge-1.16.5-36.2.20.jar object_holder_definalize PLUGINSERVICE 
                /forge-1.16.5-36.2.20.jar runtime_enum_extender PLUGINSERVICE 
                /accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
                /forge-1.16.5-36.2.20.jar capability_inject_definalize PLUGINSERVICE 
                /forge-1.16.5-36.2.20.jar runtimedistcleaner PLUGINSERVICE 
                /mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
                /forge-1.16.5-36.2.20.jar fml TRANSFORMATIONSERVICE 
        FML: 36.2
        Forge: net.minecraftforge:36.2.20
        FML Language Providers: 
                javafml@36.2
                minecraft@1
        Mod List: 
                forge-1.16.5-36.2.20-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
                valhelsia_structures-16.0.5.jar                   |Valhelsia Structures          |valhelsia_structures          |16.0.5              |DONE      |Manifest: NOSIGNATURE
                moregamerules-1.16.3-1.2.2.jar                    |More Gamerules                |moregamerules                 |1.16.3-1.2.2        |DONE      |Manifest: NOSIGNATURE
                DeathCounter-1.16.3-1.2.1.jar                     |Death Counter                 |deathcounter                  |1.2.1               |DONE      |Manifest: NOSIGNATURE
                jei-1.16.5-7.7.1.136.jar                          |Just Enough Items             |jei                           |7.7.1.136           |DONE      |Manifest: NOSIGNATURE
                astikorcarts-1.16.5-1.1.1.jar                     |AstikorCarts                  |astikorcarts                  |1.1.1               |DONE      |Manifest: NOSIGNATURE
                lycanitesmobs-1.16.5-2.3.3.3.jar                  |Lycanites Mobs                |lycanitesmobs                 |1.16.5-2.3.3.3      |DONE      |Manifest: NOSIGNATURE
                jeiintegration_1.16.5-7.0.1.15.jar                |JEI Integration               |jeiintegration                |7.0.1.15            |DONE      |Manifest: NOSIGNATURE
                Neat+1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |DONE      |Manifest: NOSIGNATURE
                TerraForged-1.16.4-0.2.9.jar                      |TerraForged                   |terraforged                   |0.2.9               |DONE      |Manifest: 7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
                ftb-backups-2.1.1.6.jar                           |FTB Backups                   |ftbbackups                    |2.1.1.6             |DONE      |Manifest: NOSIGNATURE
                Controlling-7.0.0.14.jar                          |Controlling                   |controlling                   |7.0.0.14            |DONE      |Manifest: NOSIGNATURE
                Placebo-1.16.4-4.4.1.jar                          |Placebo                       |placebo                       |4.4.1               |DONE      |Manifest: NOSIGNATURE
                citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |DONE      |Manifest: NOSIGNATURE
                alexsmobs-1.11.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.11.1              |DONE      |Manifest: NOSIGNATURE
                StorageDrawers-1.16.3-8.2.2.jar                   |Storage Drawers               |storagedrawers                |8.2.2               |DONE      |Manifest: NOSIGNATURE
                performant-1.16.2-5-3.72m.jar                     |Performant                    |performant                    |3.56m               |DONE      |Manifest: NOSIGNATURE
                YungsApi-1.16.4-Forge-6.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-6      |DONE      |Manifest: NOSIGNATURE
                structurize-0.13.252-ALPHA-universal.jar          |Structurize                   |structurize                   |0.13.252-ALPHA      |DONE      |Manifest: NOSIGNATURE
                Bookshelf-1.16.5-10.0.7.jar                       |Bookshelf                     |bookshelf                     |10.0.7              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
                EnchantmentDescriptions-1.16.5-7.0.3.jar          |EnchantmentDescriptions       |enchdesc                      |7.0.3               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
                AmbientEnvironment-4.0.0.6.jar                    |Ambient Environment           |ambientenvironment            |4.0.0.6             |DONE      |Manifest: NOSIGNATURE
                worldedit-mod-7.2.4.jar                           |WorldEdit                     |worldedit                     |7.2.4+5723-e3bfc64  |DONE      |Manifest: NOSIGNATURE
                minecolonies-1.16.5-1.0.332-ALPHA.jar             |MineColonies                  |minecolonies                  |1.16.5-1.0.332-ALPHA|DONE      |Manifest: NOSIGNATURE
                colonyward-1.0.0.jar                              |Colony Ward                   |colonyward                    |mod_version         |DONE      |Manifest: NOSIGNATURE
                moreoverlays-1.18.13-mc1.16.5.jar                 |More Overlays Updated         |moreoverlays                  |1.18.13-mc1.16.5    |DONE      |Manifest: NOSIGNATURE
                iceandfire-2.1.9-1.16.5.jar                       |Ice and Fire                  |iceandfire                    |2.1.9-1.16.5        |DONE      |Manifest: NOSIGNATURE
                Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |Manifest: NOSIGNATURE
                WAWLA-1.16.5-8.0.1.jar                            |WAWLA                         |wawla                         |8.0.1               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
                betterwithminecolonies-1.16.4-1.16.17.jar         |Better With Minecolonies      |betterwithminecolonies        |1.16.4-1.16.17      |DONE      |Manifest: NOSIGNATURE
                Toast-Control-1.16.4-4.3.1.jar                    |Toast Control                 |toastcontrol                  |4.3.1               |DONE      |Manifest: NOSIGNATURE
                CraftTweaker-1.16.5-7.1.0.196.jar                 |CraftTweaker                  |crafttweaker                  |7.1.0.196           |DONE      |Manifest: NOSIGNATURE
                smallships-1.16.5-1.10.3.jar                      |Small Ships Mod               |smallships                    |1.10.3              |DONE      |Manifest: NOSIGNATURE
                Ambience-1.16.4-1.0.1.jar                         |Ambience - Extras             |ambience                      |1.16.4-1.0.1        |DONE      |Manifest: NOSIGNATURE
                forge-1.16.5-36.2.20-universal.jar                |Forge                         |forge                         |36.2.20             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
                Waddles-1.16.5-0.8.12.jar                         |Waddles                       |waddles                       |1.16.5-0.8.12       |DONE      |Manifest: NOSIGNATURE
                AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |Manifest: NOSIGNATURE
                FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |DONE      |Manifest: NOSIGNATURE
                exoticbirds-1.16.4-1.1.0.jar                      |Exotic Birds                  |exoticbirds                   |1.1.0               |DONE      |Manifest: NOSIGNATURE
                CosmeticArmorReworked-1.16.5-v1b.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v1b          |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
                BetterMineshafts-Forge-1.16.4-2.0.3.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.3        |DONE      |Manifest: NOSIGNATURE
                WailaHarvestability-mc1.16.x-forge-1.1.14.jar     |Waila Harvestability          |wailaharvestability           |1.1.14              |DONE      |Manifest: NOSIGNATURE
                supertools-1.16.5-4.4.jar                         |Vanilla+ Tools                |supertools                    |version             |DONE      |Manifest: NOSIGNATURE
                lumberjack-2.1.4.jar                              |LumberJack                    |lumberjack                    |2.1.4               |DONE      |Manifest: NOSIGNATURE
        Crash Report UUID: d099b15f-dd57-49e5-83ce-676e42f32b5b
        Player Count: 1 / 20; [ServerPlayerEntity['insc_polaris'/75, l='ServerLevel[New World3]', x=12777.25, y=74.50, z=585.21]]
        Data Packs: vanilla, mod:valhelsia_structures (incompatible), mod:deathcounter, mod:jei, mod:astikorcarts, mod:jeiintegration, mod:neat (incompatible), mod:terraforged, mod:controlling, mod:placebo (incompatible), mod:storagedrawers (incompatible), mod:yungsapi, mod:structurize, mod:bookshelf, mod:enchdesc, mod:ambientenvironment, mod:minecolonies (incompatible), mod:moreoverlays, mod:waila, mod:wawla, mod:betterwithminecolonies (incompatible), mod:toastcontrol (incompatible), mod:forge, mod:appleskin, mod:fastleafdecay (incompatible), mod:cosmeticarmorreworked (incompatible), mod:bettermineshafts, mod:wailaharvestability, mod:supertools (incompatible), mod:lumberjack, mod:crafttweaker, mod:worldedit (incompatible), mod:smallships, mod:citadel (incompatible), mod:alexsmobs, mod:iceandfire (incompatible), mod:waddles, mod:exoticbirds, mod:ftbbackups (incompatible), mod:ambience, mod:moregamerules, mod:lycanitesmobs, mod:colonyward, mod:performant (incompatible)
        Is Modded: Definitely; Server brand changed to 'forge'
```

**Comment by AlexModGuy** [comment]
bug is caused by performant - please report it to them
