### ISSUE TITLE
Crash " java.lang.NoSuchFieldError: DIRT " 

### ISSUE THREAD

**Issue by Diribang** [Alex-the-666/AlexsMobs#865]
My game is Crashing and i dont know why. I assume its alexs mod, because of the report : 

java.lang.NoSuchFieldError: DIRT
	at com.github.alexthe666.alexsmobs.entity.EntityFly.canFlySpawn(EntityFly.java:115) ~[alexsmobs-1.15.1.jar%2352!:1.15.1] {re:classloading}
	at net.minecraft.world.entity.SpawnPlacements.m_21759_(SpawnPlacements.java:63) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.NaturalSpawner.m_46995_(NaturalSpawner.java:226) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:174) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:124) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:114) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:classloading}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:355) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:86) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

**Comment by isuke01** [comment]
Yep I got the same issue

**Comment by mdomas1** [comment]
Same issue started a day ago

**Comment by ADZ-Development** [comment]
Same - everyone has mentioned to revert back to forge 39.0.17 because that's when forge removed their forge:DIRT reference which is what is causing this apparently.  I'm curious why I only started noticing this issue a day ago as well though.  I've been using this mod for quite some time with forge 39.0.19 and it wasn't an issue until recently.

**Comment by loco789** [comment]
Same

**Comment by MistaSquishy** [comment]
I've had the same issue with Alex's Mobs 1.15.1 file. But the 1.16.0 release seems to have fixed the issue. (only just updated it and it seems alright so far.)

**Comment by yumdek** [comment]
same issue here
