### ISSUE TITLE
Random crash, fly?

### ISSUE THREAD

**Issue by Numiansus** [Alex-the-666/AlexsMobs#881]
Many crashes with this:

```
detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.github.alexthe666.alexsmobs.entity.EntityFly.canFlySpawn(EntityFly.java:115) ~[alexsmobs-1.15.1.jar%2359!/:1.15.1] {re:classloading}
	at net.minecraft.world.entity.SpawnPlacements.m_21759_(SpawnPlacements.java:63) ~[client-1.18.1-20211210.034407-srg.jar%2395!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.NaturalSpawner.m_46995_(NaturalSpawner.java:226) ~[client-1.18.1-20211210.034407-srg.jar%2395!/:?] {re:mixin,re:classloading,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorldEntitySpawner,pl:mixin:APP:enhancedcelestials.mixins.json:access.WorldEntitySpawnerAccess,pl:mixin:A}
	at net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:174) ~[client-1.18.1-20211210.034407-srg.jar%2395!/:?] {re:mixin,re:classloading,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorldEntitySpawner,pl:mixin:APP:enhancedcelestials.mixins.json:access.WorldEntitySpawnerAccess,pl:mixin:A}
	at net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:124) ~[client-1.18.1-20211210.034407-srg.jar%2395!/:?] {re:mixin,re:classloading,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorldEntitySpawner,pl:mixin:APP:enhancedcelestials.mixins.json:access.WorldEntitySpawnerAccess,pl:mixin:A}
	at net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:114) ~[client-1.18.1-20211210.034407-srg.jar%2395!/:?] {re:mixin,re:classloading,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorldEntitySpawner,pl:mixin:APP:enhancedcelestials.mixins.json:access.WorldEntitySpawnerAccess,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:355) ~[client-1.18.1-20211210.034407-srg.jar%2395!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[client-1.18.1-20211210.034407-srg.jar%2395!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[client-1.18.1-20211210.034407-srg.jar%2395!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:A}

```

**Comment by yumdek** [comment]
I have the same problem right now. But a while ago, when I was playing with less mods the issue never appeared.
if anyone have a solution that doesn't include deleting half my mods, it would be apreciated
