### ISSUE TITLE
TemptGoal crash report.

### ISSUE THREAD

**Issue by iAmNoobAtMinecraft** [Alex-the-666/AlexsMobs#904]
I was playing on my world when i suddendly crashed for no reason.
this is the crash report.
i don't really know what happened right here so i need an explanation.

---- Minecraft Crash Report ----
// You're mean.

Time: 04/02/22 18.24
Description: Exception ticking world

java.lang.IllegalArgumentException: Unsupported mob type for TemptGoal
	at net.minecraft.entity.ai.goal.TemptGoal.<init>(SourceFile:40) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:TemptGoalMixin,pl:mixin:A}
	at pam.pamhc2crops.entities.ai.MoreTemptation.<init>(MoreTemptation.java:9) ~[?:1.0.2] {re:classloading}
	at pam.pamhc2crops.events.TemptationTask.onEntitySpawn(TemptationTask.java:198) ~[?:1.0.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_582_TemptationTask_onEntitySpawn_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3271/1348630655.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraft.world.server.ServerWorld.func_217440_f(ServerWorld.java:829) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betternether.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager.lambda$null$25(ChunkManager.java:763) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.world.server.ChunkManager$$Lambda$16524/85802831.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.datafixers.util.Either$$Lambda$14787/27294024.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$func_219200_b$26(ChunkManager.java:733) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.world.server.ChunkManager$$Lambda$16521/447208470.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$16445/140454782.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:189) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213166_h(ServerChunkProvider.java:519) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:151) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(ServerChunkProvider.java:527) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_217234_d(ServerChunkProvider.java:272) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:722) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:167) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$16272/1377619144.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.ai.goal.TemptGoal.<init>(SourceFile:40) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:TemptGoalMixin,pl:mixin:A}
	at pam.pamhc2crops.entities.ai.MoreTemptation.<init>(MoreTemptation.java:9) ~[?:1.0.2] {re:classloading}
	at pam.pamhc2crops.events.TemptationTask.onEntitySpawn(TemptationTask.java:198) ~[?:1.0.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_582_TemptationTask_onEntitySpawn_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3271/1348630655.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraft.world.server.ServerWorld.func_217440_f(ServerWorld.java:829) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betternether.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager.lambda$null$25(ChunkManager.java:763) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.world.server.ChunkManager$$Lambda$16524/85802831.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.datafixers.util.Either$$Lambda$14787/27294024.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$func_219200_b$26(ChunkManager.java:733) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.world.server.ChunkManager$$Lambda$16521/447208470.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$16445/140454782.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:189) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213166_h(ServerChunkProvider.java:519) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:151) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(ServerChunkProvider.java:527) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_217234_d(ServerChunkProvider.java:272) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:722) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['GiottoPuzza'/228, l='ServerLevel[:Troll:]', x=245.70, y=52.89, z=4063.83]]
	Chunk stats: ServerChunkCache: 5988
	Level dimension: minecraft:overworld
	Level spawn location: World: (-128,63,-171), Chunk: (at 0,3,5 in -8,-11; contains blocks -128,0,-176 to -113,255,-161), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 5050770 game time, 61368 day time
	Level name: :Troll:
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 44807 (now: false), thunder time: 55543 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:854) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$16272/1377619144.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3123492880 bytes (2978 MB) / 7583301632 bytes (7232 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 6
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.20.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.20.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.20
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.20-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		pamhc2trees-1.16.3-1.0.1.jar                      |Pam's HarvestCraft 2 Fruit Tre|pamhc2trees                   |1.0.1               |DONE      |Manifest: NOSIGNATURE
		pamhc2crops-1.16.3-1.0.2.jar                      |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             |DONE      |Manifest: NOSIGNATURE
		AoA3-3.5.4-1.16.5.jar                             |Advent of Ascension           |aoa3                          |3.5.4               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.129.jar                          |Just Enough Items             |jei                           |7.7.1.129           |DONE      |Manifest: NOSIGNATURE
		pamhc2foodextended-1.16.3-1.0.2.jar               |Pam's HarvestCraft 2 Food Exte|pamhc2foodextended            |version             |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.16.5-10.0.21.448.jar                   |Mekanism                      |mekanism                      |10.0.21             |DONE      |Manifest: NOSIGNATURE
		BetterNether_Reforged-1.0.2.jar                   |Better Nether Reforged        |betternether                  |1.0                 |DONE      |Manifest: NOSIGNATURE
		Craftable+Saddles+[1.16+All]-1.3.jar              |Craftable Saddles             |craftable_saddles             |1.3                 |DONE      |Manifest: NOSIGNATURE
		whisperwoods-1.16.5-2.0.2.jar                     |Whisperwoods                  |whisperwoods                  |2.0.2               |DONE      |Manifest: NOSIGNATURE
		flywheel-1.16-0.2.4.jar                           |Flywheel                      |flywheel                      |1.16-0.2.4          |DONE      |Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2d.jar                       |Create                        |create                        |v0.3.2d             |DONE      |Manifest: NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.2.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |DONE      |Manifest: NOSIGNATURE
		journeymap-1.16.5-5.7.1.jar                       |Journeymap                    |journeymap                    |5.7.1               |DONE      |Manifest: NOSIGNATURE
		citadel-1.6.3.jar                                 |Citadel                       |citadel                       |1.6.3               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.10.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.10.1              |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |DONE      |Manifest: NOSIGNATURE
		betteranimals-1.16.4-5.5.0.jar                    |Cyber's Better Animal Models  |betteranimals                 |5.5.0               |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-6.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-6      |DONE      |Manifest: NOSIGNATURE
		betteranimalsplus-1.16.5-10.2.0.jar               |Better Animals Plus           |betteranimalsplus             |10.2.0              |DONE      |Manifest: NOSIGNATURE
		bedspreads-forge-1.16.4-5.1.0.1.jar               |Bedspreads                    |bedspreads                    |1.16.4-5.1.0.1      |DONE      |Manifest: NOSIGNATURE
		iceandfire-2.1.6-1.16.4.jar                       |Ice and Fire                  |iceandfire                    |2.1.6-1.16.4        |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.16.5-10.0.21.448.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.21             |DONE      |Manifest: NOSIGNATURE
		byg-1.2.9.jar                                     |Oh The Biomes You'll Go       |byg                           |1.2.9               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.20-universal.jar                |Forge                         |forge                         |36.2.20             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Quark-r2.4-316.jar                                |Quark                         |quark                         |r2.4-316            |DONE      |Manifest: NOSIGNATURE
		DynamicTrees-1.16.5-0.10.0-Beta25.jar             |Dynamic Trees                 |dynamictrees                  |1.16.5-0.10.0-Beta25|DONE      |Manifest: NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |DONE      |Manifest: NOSIGNATURE
		betterendforge-1.16.4-1.6.0.jar                   |BetterEnd Forge               |betterendforge                |1.16.4-1.6.0        |DONE      |Manifest: NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.4.2.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.4.2      |DONE      |Manifest: b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		xptome-1.16.5-v2.1.2.jar                          |XP Tome                       |xpbook                        |v2.1.2              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 5f4c0f4d-0aa8-460e-9b70-dca2497a3e87
	Player Count: 1 / 8; [ServerPlayerEntity['GiottoPuzza'/228, l='ServerLevel[:Troll:]', x=245.70, y=52.89, z=4063.83]]
	Data Packs: vanilla, mod:pamhc2trees (incompatible), mod:pamhc2crops (incompatible), mod:mekanismgenerators, mod:jei, mod:byg, mod:mekanism, mod:forge, mod:flywheel, mod:create, mod:pamhc2foodcore (incompatible), mod:journeymap (incompatible), mod:citadel (incompatible), mod:iceandfire (incompatible), mod:yungsapi, mod:betternether, mod:dynamictrees, mod:bettermineshafts, mod:betterendforge, mod:dsurround, mod:autoreglib (incompatible), mod:quark (incompatible), mod:aoa3 (incompatible), mod:craftable_saddles (incompatible), mod:pamhc2foodextended (incompatible), mod:alexsmobs, mod:betteranimals (incompatible), mod:betteranimalsplus (incompatible), mod:bedspreads, mod:whisperwoods, mod:xpbook
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 20
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 457.51
	OpenGlRenderer: GeForce GTX 1650/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6

**Comment by iAmNoobAtMinecraft** [comment]
also my discord in EnormousSimp#0001.
i wont be active a lot here so feel free to DM me.

**Comment by AlexModGuy** [comment]
> pam.pamhc2crops.entities.ai.MoreTemptation
