### ISSUE TITLE
alexs mobs keeps crashing with wiki zoomer 

### ISSUE THREAD

**Issue by baddybadger5** [Alex-the-666/AlexsMobs#932]
everytime i click on the entity zoomer it just crashes

**Comment by AlexModGuy** [comment]
crash log?

**Comment by baddybadger5** [comment]
ok

**Comment by baddybadger5** [comment]
The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag com.github.alexthe666.wikizoomer.tileentity.TileEntityZoomerBase.save(net.minecraft.nbt.CompoundTag)'
Exit Code: -1

**Comment by baddybadger5** [comment]
java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag com.github.alexthe666.wikizoomer.tileentity.TileEntityZoomerBase.save(net.minecraft.nbt.CompoundTag)'
	at com.github.alexthe666.wikizoomer.tileentity.TileEntityZoomerBase.m_6836_(TileEntityZoomerBase.java:91) ~[wikizoomer-1.1.0-1.18.1.jar%23120!/:1.1.0-1.18.1] {re:classloading}
	at com.github.alexthe666.wikizoomer.tileentity.TileEntityEntityZoomer.m_6836_(TileEntityEntityZoomer.java:34) ~[wikizoomer-1.1.0-1.18.1.jar%23120!/:1.1.0-1.18.1] {re:classloading}
	at com.github.alexthe666.wikizoomer.BlockZoomer.m_6227_(BlockZoomer.java:81) ~[wikizoomer-1.1.0-1.18.1.jar%23120!/:1.1.0-1.18.1] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:695) ~[client-1.18.1-20211210.034407-srg.jar%23123!/:?] {re:mixin,re:classloading,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105262_(MultiPlayerGameMode.java:297) ~[client-1.18.1-20211210.034407-srg.jar%23123!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.m_105262_(PlayerControllerOF.java:96) ~[OptiFine_1.18.1_HD_U_H4.jar%23128!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1554) ~[client-1.18.1-20211210.034407-srg.jar%23123!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1833) ~[client-1.18.1-20211210.034407-srg.jar%23123!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1651) ~[client-1.18.1-20211210.034407-srg.jar%23123!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1015) ~[client-1.18.1-20211210.034407-srg.jar%23123!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%23123!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23123!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.75.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.github.alexthe666.wikizoomer.tileentity.TileEntityZoomerBase.m_6836_(TileEntityZoomerBase.java:91) ~[wikizoomer-1.1.0-1.18.1.jar%23120!/:1.1.0-1.18.1] {re:classloading}
	at com.github.alexthe666.wikizoomer.tileentity.TileEntityEntityZoomer.m_6836_(TileEntityEntityZoomer.java:34) ~[wikizoomer-1.1.0-1.18.1.jar%23120!/:1.1.0-1.18.1] {re:classloading}
	at com.github.alexthe666.wikizoomer.BlockZoomer.m_6227_(BlockZoomer.java:81) ~[wikizoomer-1.1.0-1.18.1.jar%23120!/:1.1.0-1.18.1] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:695) ~[client-1.18.1-20211210.034407-srg.jar%23123!/:?] {re:mixin,re:classloading,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105262_(MultiPlayerGameMode.java:297) ~[client-1.18.1-20211210.034407-srg.jar%23123!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.m_105262_(PlayerControllerOF.java:96) ~[OptiFine_1.18.1_HD_U_H4.jar%23128!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1554) ~[client-1.18.1-20211210.034407-srg.jar%23123!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1833) ~[client-1.18.1-20211210.034407-srg.jar%23123!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['baddybadger5'/305, l='ClientLevel', x=72.76, y=64.00, z=89.81]]
	Chunk stats: 529, 322
	Level dimension: minecraft:overworld
	Level spawn location: World: (70,63,60), Section: (at 6,15,12 in 4,3,3; chunk contains blocks 64,-64,48 to 79,319,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 715 game time, 715 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:517) ~[client-1.18.1-20211210.034407-srg.jar%23123!/:?] {re:mixin,xf:OptiFine:default,re:computing_frames,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:terrablender.mixins.json:client.MixinClientLevel,pl:mixin:APP:create.mixins.json:DestroyProgressMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2248) ~[client-1.18.1-20211210.034407-srg.jar%23123!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:682) ~[client-1.18.1-20211210.034407-srg.jar%23123!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23123!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.75.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources, quark-emote-pack

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 901130528 bytes (859 MiB) / 4219469824 bytes (4024 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1650 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f95
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9649
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9bc4
	Graphics card #1 versionInfo: DriverVersion=26.20.100.7985
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 28459.00
	Virtual memory used (MB): 22469.14
	Swap memory total (MB): 12288.00
	Swap memory used (MB): 670.03
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m
	Launched Version: forge-39.0.75
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1650 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 496.49, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['baddybadger5'/305, l='ServerLevel[New World]', x=72.76, y=64.00, z=89.81]]
	Data Packs: vanilla, mod:treechop (incompatible), mod:quarkoddities (incompatible), mod:unusualfishmod, mod:caveore (incompatible), mod:treeharvester, mod:jei, mod:prefab, mod:conjurer_illager (incompatible), mod:soaringstructures2 (incompatible), mod:goblintraders (incompatible), mod:kingvillager (incompatible), mod:placebo (incompatible), mod:comforts, mod:citadel, mod:alexsmobs (incompatible), mod:naturescompass (incompatible), mod:artifacts, mod:sereneseasons (incompatible), mod:guardvillagers (incompatible), mod:crockpot, mod:snuffles, mod:wikizoomer (incompatible), mod:hedgehog, mod:restored_earth, mod:forge, mod:supplementaries (incompatible), mod:structure_gel, mod:selene (incompatible), mod:dungeons_arise, mod:castle_in_the_sky (incompatible), mod:farmersdelight, mod:morevillagers (incompatible), mod:terrablender, mod:spark (incompatible), mod:majrusz_library (incompatible), mod:flywheel, mod:create, mod:curios, mod:croptopia, mod:collective, mod:autoreglib (incompatible), mod:quark (incompatible), mod:effective_fg, mod:worldedit, mod:majruszs_difficulty (incompatible), mod:constructionwand, mod:hunterillager, mod:appleskin, mod:ferritecore (incompatible), mod:aquaculture (incompatible), mod:enchantwithmob, mod:fastleafdecay, mod:expandability (incompatible), mod:cosmeticarmorreworked (incompatible), mod:geckolib3 (incompatible), mod:winteroverhaul, mod:creeperoverhaul
	OptiFine Version: OptiFine_1.18.1_HD_U_H4
	OptiFine Build: 20211212-175054
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 496.49
	OpenGlRenderer: NVIDIA GeForce GTX 1650 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
	ModLauncher: 9.1.0+9.1.0+main.6690ee51
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		TreeChop-1.18.1-0.15.5.jar                        |HT's TreeChop                 |treechop                      |0.15.5              |DONE      |Manifest: NOSIGNATURE
		QuarkOddities-1.18.jar                            |Quark Oddities                |quarkoddities                 |1.18                |DONE      |Manifest: NOSIGNATURE
		unusualfishmod-0.2.2.jar                          |Unusual Fish Mod              |unusualfishmod                |0.2.2               |DONE      |Manifest: NOSIGNATURE
		caveore-1.18.1-2.1.jar                            |CaveOre Mod                   |caveore                       |1.18.1-2.1          |DONE      |Manifest: NOSIGNATURE
		treeharvester_1.18.1-4.2.jar                      |Tree Harvester                |treeharvester                 |4.2                 |DONE      |Manifest: NOSIGNATURE
		jei-1.18.1-9.3.2.92.jar                           |Just Enough Items             |jei                           |9.3.2.92            |DONE      |Manifest: NOSIGNATURE
		prefab-1.8.1.3.jar                                |Prefab                        |prefab                        |1.8.1.3             |DONE      |Manifest: NOSIGNATURE
		the-conjurer-1.18.1-1.1.1.jar                     |The Conjurer                  |conjurer_illager              |1.1.1               |DONE      |Manifest: NOSIGNATURE
		Soaring-Structures-2-1.18.1-2.2.jar               |Soaring Structures 2          |soaringstructures2            |1.18.1 - 2.2        |DONE      |Manifest: NOSIGNATURE
		goblintraders-1.7.0-1.18.1.jar                    |Goblin Traders                |goblintraders                 |1.7.0               |DONE      |Manifest: NOSIGNATURE
		kingvillager-1.9.1.jar                            |The King of the Villagers     |kingvillager                  |1.9.1               |DONE      |Manifest: NOSIGNATURE
		Placebo-1.18.1-6.1.0.jar                          |Placebo                       |placebo                       |6.1.0               |DONE      |Manifest: NOSIGNATURE
		comforts-forge-1.18-5.0.0.1.jar                   |Comforts                      |comforts                      |1.18-5.0.0.1        |DONE      |Manifest: NOSIGNATURE
		citadel-1.10.10-1.18.jar                          |Citadel                       |citadel                       |1.10.10             |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.17.0.jar                              |Alex's Mobs                   |alexsmobs                     |1.17.0              |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.18.1-1.9.4-forge.jar             |Nature's Compass              |naturescompass                |1.18.1-1.9.4-forge  |DONE      |Manifest: NOSIGNATURE
		artifacts-1.18.1-4.0.2.jar                        |Artifacts                     |artifacts                     |1.18.1-4.0.2        |DONE      |Manifest: NOSIGNATURE
		SereneSeasons-1.18.1-6.0.0.10-universal.jar       |Serene Seasons                |sereneseasons                 |1.18.1-6.0.0.10     |DONE      |Manifest: NOSIGNATURE
		guardvillagers-1.18.1.4.0.jar                     |Guard Villagers               |guardvillagers                |1.4.0               |DONE      |Manifest: NOSIGNATURE
		CrockPot-1.18.1-1.1.1-release.jar                 |Crock Pot                     |crockpot                      |1.1.1-release       |DONE      |Manifest: NOSIGNATURE
		snuffles-1.0.1.jar                                |Snuffles                      |snuffles                      |1.0.1               |DONE      |Manifest: NOSIGNATURE
		wikizoomer-1.1.0-1.18.1.jar                       |Wiki Zoomer                   |wikizoomer                    |1.1.0               |DONE      |Manifest: NOSIGNATURE
		hedgehog-1.1.2.jar                                |Hedgehog                      |hedgehog                      |1.1.2               |DONE      |Manifest: NOSIGNATURE
		restored_earth-1.18.1-1.4.0.jar                   |Restored Earth                |restored_earth                |1.4.0               |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.75-universal.jar                |Forge                         |forge                         |39.0.75             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		supplementaries-1.18.1-1.1.11.jar                 |Supplementaries               |supplementaries               |1.1.11              |DONE      |Manifest: NOSIGNATURE
		structure_gel-1.18.1-2.1.3.jar                    |Structure Gel API             |structure_gel                 |2.1.3               |DONE      |Manifest: NOSIGNATURE
		selene-1.18-1.12.0.jar                            |Selene                        |selene                        |1.18-1.12.0         |DONE      |Manifest: NOSIGNATURE
		DungeonsArise-1.18.1-2.1.49d-beta.jar             |When Dungeons Arise           |dungeons_arise                |2.1.49d-1.18.1      |DONE      |Manifest: NOSIGNATURE
		castle_in_the_sky-1.18.1-0.3.1.jar                |Castle in the sky             |castle_in_the_sky             |1.18.1              |DONE      |Manifest: NOSIGNATURE
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.18.1-1.0.3.jar                   |Farmer's Delight              |farmersdelight                |1.18.1-1.0.3        |DONE      |Manifest: NOSIGNATURE
		morevillagers-FORGE-1.18.1-3.1.2.jar              |More Villagers                |morevillagers                 |3.1.2               |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.1-1.1.0.73.jar            |TerraBlender                  |terrablender                  |1.18.1-1.1.0.73     |DONE      |Manifest: NOSIGNATURE
		spark-1.8.6-forge.jar                             |spark                         |spark                         |1.8.6               |DONE      |Manifest: NOSIGNATURE
		majrusz-library-1.18.1-2.7.1.jar                  |Majrusz Library               |majrusz_library               |2.7.1               |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.6.0.jar                     |Flywheel                      |flywheel                      |1.18-0.6.0          |DONE      |Manifest: NOSIGNATURE
		create-mc1.18.1_v0.4d.jar                         |Create                        |create                        |0.4d                |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.1-5.0.6.0.jar                   |Curios API                    |curios                        |1.18.1-5.0.6.0      |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.18-FORGE-1.8.0.jar                    |Croptopia                     |croptopia                     |1.8.0               |DONE      |Manifest: NOSIGNATURE
		collective-1.18.1-4.0.jar                         |Collective                    |collective                    |4.0                 |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |DONE      |Manifest: NOSIGNATURE
		Quark-3.1-336.jar                                 |Quark                         |quark                         |3.1-336             |DONE      |Manifest: NOSIGNATURE
		effective_for_forge-1.001.jar                     |Effective (Forge)             |effective_fg                  |1.0                 |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.9.jar                           |WorldEdit                     |worldedit                     |7.2.9+e20e013       |DONE      |Manifest: NOSIGNATURE
		majruszs-difficulty-1.18.1-1.4.1.jar              |Majrusz's Progressive Difficul|majruszs_difficulty           |1.4.1               |DONE      |Manifest: NOSIGNATURE
		constructionwand-1.18.1-2.6.jar                   |Construction Wand             |constructionwand              |1.18.1-2.6          |DONE      |Manifest: NOSIGNATURE
		HunterIllager-1.18.1-3.1.6.jar                    |Hunter Illager                |hunterillager                 |1.18.1-3.1.6        |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.18-2.3.0.jar                  |AppleSkin                     |appleskin                     |2.3.0+mc1.18        |DONE      |Manifest: NOSIGNATURE
		ferritecore-4.1.1-forge.jar                       |Ferrite Core                  |ferritecore                   |4.1.1               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		Aquaculture-1.18.1-2.3.3.jar                      |Aquaculture 2                 |aquaculture                   |1.18.1-2.3.3        |DONE      |Manifest: NOSIGNATURE
		enchantwithmob-1.18.1-3.3.0.jar                   |Enchant With Mob              |enchantwithmob                |1.18.1-3.3.0        |DONE      |Manifest: NOSIGNATURE
		FastLeafDecay-27.2.jar                            |FastLeafDecay                 |fastleafdecay                 |27.2                |DONE      |Manifest: NOSIGNATURE
		expandability-5.0.0-forge.jar                     |ExpandAbility                 |expandability                 |5.0.0               |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.18.1-v1a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.18.1-v1a          |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		geckolib-1.18-forge-3.0.11.jar                    |GeckoLib                      |geckolib3                     |3.0.11              |DONE      |Manifest: NOSIGNATURE
		winteroverhaul-1.0.0.jar                          |Winter Overhaul               |winteroverhaul                |1.0.0               |DONE      |Manifest: NOSIGNATURE
		creeperoverhaul-1.18.1-0.3.0-forge.jar            |Creeper Overhaul              |creeperoverhaul               |0.3.0               |DONE      |Manifest: NOSIGNATURE
	Flywheel Backend: Off
	Crash Report UUID: 55f67c91-8cae-4575-b036-3c0763fae7a3
	FML: 39.0
	Forge: net.minecraftforge:39.0.75
