### ISSUE TITLE
AlexsMobs crashes minecraft at the loading screen

### ISSUE THREAD

**Issue by Teaspoonies** [Alex-the-666/AlexsMobs#993]
I've been trying to start a modded server and have been testing mods to add to it. Alex'sMobs was the first one I tried, and i'm not sure exactly why it isn't working. Any suggestions? This is from trying it in singleplayer with a fresh install

---- Minecraft Crash Report ----
// My bad.

Time: 3/12/22, 4:35 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.0.12-universal.jar%2358!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:169) ~[forge-1.18.2-40.0.12-universal.jar%2358!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:555) ~[client-1.18.2-20220228.144236-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:397) ~[client-1.18.2-20220228.144236-srg.jar%2354!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:549) ~[client-1.18.2-20220228.144236-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.18.2-20220228.144236-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:877) ~[client-1.18.2-20220228.144236-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220228.144236-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220228.144236-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220228.144236-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.2-40.0.12.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.core.MappedRegistry.m_205921_(MappedRegistry.java:78) ~[client-1.18.2-20220228.144236-srg.jar%2354!/:?] {re:classloading}
-- MOD alexsmobs --
Details:
	Caused by 0: java.lang.ExceptionInInitializerError
		at net.minecraftforge.fml.DistExecutor.unsafeRunForDist(DistExecutor.java:174) ~[fmlcore-1.18.2-40.0.12.jar%2355!/:?] {}
		at net.minecraftforge.fml.DistExecutor.runForDist(DistExecutor.java:157) ~[fmlcore-1.18.2-40.0.12.jar%2355!/:?] {}
		at com.github.alexthe666.alexsmobs.AlexsMobs.<clinit>(AlexsMobs.java:45) ~[alexsmobs-1.17.1.jar%2352!/:1.17.1] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.2-40.0.12.jar%2356!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.2-40.0.12.jar%2355!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: alexsmobs-1.17.1.jar
	Failure message: Alex's Mobs (alexsmobs) has failed to load correctly
		java.lang.ExceptionInInitializerError: null
	Mod Version: 1.17.1
	Mod Issue URL: https://github.com/Alex-the-666/AlexsMobs/issues
	Exception message: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:loot_condition_type / alexsmobs:matches_banana_tag])
Stacktrace:
	at net.minecraft.core.MappedRegistry.m_205921_(MappedRegistry.java:78) ~[client-1.18.2-20220228.144236-srg.jar%2354!/:?] {re:classloading}
	at net.minecraft.core.MappedRegistry.m_205857_(MappedRegistry.java:87) ~[client-1.18.2-20220228.144236-srg.jar%2354!/:?] {re:classloading}
	at net.minecraft.core.MappedRegistry.m_203704_(MappedRegistry.java:83) ~[client-1.18.2-20220228.144236-srg.jar%2354!/:?] {re:classloading}
	at net.minecraft.core.MappedRegistry.m_203505_(MappedRegistry.java:128) ~[client-1.18.2-20220228.144236-srg.jar%2354!/:?] {re:classloading}
	at net.minecraft.core.Registry.m_194579_(Registry.java:564) ~[client-1.18.2-20220228.144236-srg.jar%2354!/:?] {re:classloading}
	at net.minecraft.core.Registry.m_122965_(Registry.java:560) ~[client-1.18.2-20220228.144236-srg.jar%2354!/:?] {re:classloading}
	at com.github.alexthe666.alexsmobs.CommonProxy.registerLootCondition(CommonProxy.java:56) ~[alexsmobs-1.17.1.jar%2352!/:1.17.1] {re:classloading}
	at com.github.alexthe666.alexsmobs.CommonProxy.<clinit>(CommonProxy.java:30) ~[alexsmobs-1.17.1.jar%2352!/:1.17.1] {re:classloading}
	at net.minecraftforge.fml.DistExecutor.unsafeRunForDist(DistExecutor.java:174) ~[fmlcore-1.18.2-40.0.12.jar%2355!/:?] {}
	at net.minecraftforge.fml.DistExecutor.runForDist(DistExecutor.java:157) ~[fmlcore-1.18.2-40.0.12.jar%2355!/:?] {}
	at com.github.alexthe666.alexsmobs.AlexsMobs.<clinit>(AlexsMobs.java:45) ~[alexsmobs-1.17.1.jar%2352!/:1.17.1] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.2-40.0.12.jar%2356!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.2-40.0.12.jar%2355!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 676237080 bytes (644 MiB) / 1509949440 bytes (1440 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b81
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1179
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.67
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.67
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37581.43
	Virtual memory used (MB): 13179.55
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.2-20220228.144236-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.18.2-40.0.12-universal.jar                |Forge                         |forge                         |40.0.12             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		citadel-1.11.1-1.18.2.jar                         |Citadel                       |citadel                       |1.11.1              |COMMON_SET|Manifest: NOSIGNATURE
		alexsmobs-1.17.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.17.1              |ERROR     |Manifest: NOSIGNATURE
	Crash Report UUID: 2a14ed5c-b2e6-4b43-ae82-905c117683ec
	FML: 40.0
	Forge: net.minecraftforge:40.0.12

**Comment by isaaclepes** [comment]
Having exact same error on Forge 40.0.13.

```
	Mod File: alexsmobs-1.17.1.jar
	Failure message: Alex's Mobs (alexsmobs) has failed to load correctly
		java.lang.ExceptionInInitializerError: null
	Mod Version: 1.17.1
	Mod Issue URL: https://github.com/Alex-the-666/AlexsMobs/issues
	Exception message: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:loot_condition_type / alexsmobs:matches_banana_tag])
```
![image](https://user-images.githubusercontent.com/54421422/158079379-66b06c30-10d0-41eb-b8bc-19f121375f12.png)

Citadel version 1.11.1-1.18.2

It must be something with the 1.18.2 update, as it still works fine on 1.18.1.

**Comment by Teaspoonies** [comment]
Yeah. I ended up going down to Forge 39.1.2 and MC 1.18.1 to get the mod goin'. Will just have to wait for updates, I suppose.

**Comment by AlexModGuy** [comment]
mod is not for 1.18.2 yet. mojang changed many things!
